// Computer Architecture questions extracted from edumaster app.js



const CA_INTRO_QUESTIONS = [
  { q: "What is computer architecture?", options: ["Hardware design", "Software design", "The design and organization of computer systems", "Programming"], answer: 2, explanation: "Computer architecture encompasses the design and organization of computer systems, including hardware and software interaction." },
  { q: "Key components of a computer system include:", options: ["CPU, memory, I/O", "Only CPU", "Only memory", "Only I/O"], answer: 0, explanation: "The main components are CPU (Central Processing Unit), memory, and input/output devices." },
  { q: "Von Neumann architecture features:", options: ["Separate memories", "Stored-program concept", "No memory", "Only hardware"], answer: 1, explanation: "Von Neumann architecture stores both data and instructions in the same memory." },
  { q: "Harvard architecture has:", options: ["One memory", "Separate instruction and data memories", "No separation", "Only data"], answer: 1, explanation: "Harvard architecture separates instruction memory from data memory for parallel access." },
  { q: "Performance metrics include:", options: ["Throughput only", "Latency only", "Throughput, latency, bandwidth", "None"], answer: 2, explanation: "Key performance metrics are throughput (instructions per second), latency (time per instruction), and bandwidth (data transfer rate)." },
  { q: "Levels of abstraction in computer architecture:", options: ["Hardware only", "Hardware, microarchitecture, ISA, OS, application", "Software only", "None"], answer: 1, explanation: "Abstraction levels range from hardware to application software." },
  { q: "ISA stands for:", options: ["Internal System Architecture", "Instruction Set Architecture", "Integrated System Array", "None"], answer: 1, explanation: "ISA defines the interface between hardware and software, including instructions and registers." },
  { q: "Microarchitecture implements:", options: ["Software", "ISA in hardware", "OS", "Applications"], answer: 1, explanation: "Microarchitecture is the hardware implementation of the ISA." },
  { q: "Bus systems include:", options: ["Data bus only", "Address bus only", "Data, address, control buses", "None"], answer: 2, explanation: "Buses transfer data, addresses, and control signals between components." },
  { q: "Cache memory is used for:", options: ["Slow access", "Fast access to frequently used data", "No purpose", "Only storage"], answer: 1, explanation: "Cache provides fast access to frequently used data, reducing memory latency." },
  { q: "Parallel processing involves:", options: ["Sequential execution", "Multiple processors executing simultaneously", "One processor", "No execution"], answer: 1, explanation: "Parallel processing uses multiple processors to execute tasks concurrently." },
  { q: "RISC stands for:", options: ["Reduced Instruction Set Computer", "Random Instruction Set Computer", "Rapid Instruction Set Computer", "None"], answer: 0, explanation: "RISC architectures use a small set of simple instructions for efficiency." },
  { q: "CISC stands for:", options: ["Complex Instruction Set Computer", "Compact Instruction Set Computer", "Central Instruction Set Computer", "None"], answer: 0, explanation: "CISC architectures have complex instructions that perform multiple operations." },
  { q: "Pipelining improves:", options: ["Memory", "CPU performance by overlapping instruction execution", "I/O", "None"], answer: 1, explanation: "Pipelining allows multiple instructions to be processed simultaneously in different stages." },
  { q: "Branch prediction is used to:", options: ["Slow down", "Predict branch outcomes to reduce stalls", "Increase stalls", "None"], answer: 1, explanation: "Branch prediction anticipates jump directions to keep the pipeline full." },
  { q: "Memory hierarchy includes:", options: ["Registers only", "Registers, cache, main memory, disk", "Disk only", "None"], answer: 1, explanation: "Memory hierarchy provides different speeds and sizes for optimal performance." },
  { q: "Virtual memory allows:", options: ["No paging", "Programs to use more memory than physically available", "Less memory", "None"], answer: 1, explanation: "Virtual memory uses disk space to extend physical memory via paging." },
  { q: "Interrupts are:", options: ["Ignored", "Signals that alter normal program flow", "Normal flow", "None"], answer: 1, explanation: "Interrupts allow the CPU to respond to events asynchronously." },
  { q: "Multicore processors have:", options: ["One core", "Multiple cores on a single chip", "No cores", "External cores"], answer: 1, explanation: "Multicore processors integrate multiple processing cores for parallel execution." },
  { q: "Amdahl's law relates to:", options: ["Serial parts", "The speedup from parallelization", "No speedup", "None"], answer: 1, explanation: "Amdahl's law calculates maximum speedup based on parallelizable fraction." },
  { q: "Flynn's taxonomy classifies:", options: ["Memory", "Computer architectures by instruction and data streams", "I/O", "None"], answer: 1, explanation: "Flynn's taxonomy (SISD, SIMD, MISD, MIMD) categorizes parallel architectures." },
  { q: "Superscalar architecture:", options: ["One instruction per cycle", "Multiple instructions per cycle", "No instructions", "None"], answer: 1, explanation: "Superscalar processors execute multiple instructions per clock cycle." },
  { q: "Out-of-order execution:", options: ["Sequential", "Executes instructions as resources become available", "In order", "None"], answer: 1, explanation: "Out-of-order execution improves performance by avoiding dependencies." },
  { q: "Speculative execution:", options: ["Guesses wrong", "Executes instructions ahead, discarding if wrong", "No execution", "None"], answer: 1, explanation: "Speculative execution predicts and executes branches, rolling back if incorrect." },
  { q: "Cache coherence is important in:", options: ["Single core", "Multiprocessor systems", "No processors", "None"], answer: 1, explanation: "Cache coherence ensures consistent data in multiprocessor caches." },
  { q: "NUMA stands for:", options: ["Non-Uniform Memory Access", "Uniform Memory Access", "No Memory Access", "None"], answer: 0, explanation: "NUMA systems have varying memory access times based on location." },
  { q: "SMP stands for:", options: ["Single Memory Processor", "Symmetric Multiprocessing", "Asymmetric Multiprocessing", "None"], answer: 1, explanation: "SMP systems have multiple processors sharing memory symmetrically." },
  { q: "Vector processors are optimized for:", options: ["Scalar operations", "Data-parallel operations on arrays", "Single data", "None"], answer: 1, explanation: "Vector processors handle SIMD operations efficiently." },
  { q: "GPU stands for:", options: ["General Processing Unit", "Graphics Processing Unit", "No unit", "None"], answer: 1, explanation: "GPUs are specialized for parallel graphics and general-purpose computing." },
  { q: "Quantum computing uses:", options: ["Bits", "Qubits for superposition and entanglement", "No bits", "None"], answer: 1, explanation: "Quantum computers use quantum bits (qubits) for parallel computation." }
];

const CA_NUM_QUESTIONS = [
  { q: "Binary system base is:", options: ["10", "2", "8", "16"], answer: 1, explanation: "Binary uses base 2 with digits 0 and 1." },
  { q: "Decimal to binary conversion:", options: ["Divide by 2", "Divide by 10", "Multiply by 2", "None"], answer: 0, explanation: "Repeated division by 2 gives binary digits." },
  { q: "Hexadecimal uses digits:", options: ["0-9", "0-9, A-F", "0-7", "0-1"], answer: 1, explanation: "Hex uses 0-9 and A-F for 16 values." },
  { q: "Octal base is:", options: ["2", "8", "10", "16"], answer: 1, explanation: "Octal uses base 8 with digits 0-7." },
  { q: "Two's complement represents:", options: ["Positive only", "Negative numbers", "Unsigned", "None"], answer: 1, explanation: "Two's complement is used for signed binary numbers." },
  { q: "Binary addition of 1+1:", options: ["0 carry 0", "1 carry 0", "0 carry 1", "1 carry 1"], answer: 2, explanation: "1 + 1 = 0 with carry 1 in binary." },
  { q: "BCD stands for:", options: ["Binary Coded Decimal", "Binary Computer Decimal", "None", "Decimal"], answer: 0, explanation: "BCD represents decimal digits in binary." },
  { q: "Floating-point standard is:", options: ["IEEE 754", "IEEE 802", "None", "754"], answer: 0, explanation: "IEEE 754 defines floating-point representation." },
  { q: "Mantissa in float is:", options: ["Exponent", "Significand", "Sign", "None"], answer: 1, explanation: "Mantissa is the significand part of a float." },
  { q: "Bias in exponent is:", options: ["0", "127 for single precision", "255", "None"], answer: 1, explanation: "Exponent is biased by 127 in IEEE 754 single precision." },
  { q: "ASCII is:", options: ["Binary", "7-bit character code", "8-bit", "None"], answer: 1, explanation: "ASCII uses 7 bits for character encoding." },
  { q: "Unicode supports:", options: ["English only", "Multiple languages", "One language", "None"], answer: 1, explanation: "Unicode is a universal character encoding." },
  { q: "Gray code differs by:", options: ["Multiple bits", "One bit between consecutive", "No bits", "None"], answer: 1, explanation: "Gray code changes only one bit between numbers." },
  { q: "Binary multiplication:", options: ["Same as decimal", "Shifts and adds", "No multiplication", "None"], answer: 1, explanation: "Binary multiplication uses shifts and adds." },
  { q: "Hex to binary:", options: ["Direct", "4 bits per hex digit", "8 bits", "None"], answer: 1, explanation: "Each hex digit converts to 4 binary bits." },
  { q: "Binary to hex:", options: ["4 bits to 1 hex", "8 bits", "Direct", "None"], answer: 0, explanation: "Group 4 binary bits into one hex digit." },
  { q: "Signed magnitude has:", options: ["No sign", "Sign bit + magnitude", "Complement", "None"], answer: 1, explanation: "Signed magnitude uses a sign bit and positive magnitude." },
  { q: "One's complement flips:", options: ["All bits", "Bits except sign", "Sign only", "None"], answer: 0, explanation: "One's complement inverts all bits." },
  { q: "Two's complement is:", options: ["One's +1", "One's complement +1", "No +1", "None"], answer: 1, explanation: "Two's complement is one's complement plus one." },
  { q: "Overflow in addition occurs when:", options: ["Carry in", "Carry out from MSB differs from carry in", "No carry", "None"], answer: 1, explanation: "Overflow happens if MSB carry in/out differ." },
  { q: "Underflow in subtraction:", options: ["No borrow", "Borrow from MSB", "No underflow", "None"], answer: 1, explanation: "Underflow occurs when borrowing from MSB." },
  { q: "Fixed-point numbers have:", options: ["Floating point", "Fixed decimal point", "No point", "None"], answer: 1, explanation: "Fixed-point has a fixed position for the decimal." },
  { q: "Binary fractions use:", options: ["Negative powers", "Positive powers", "No fractions", "None"], answer: 0, explanation: "Binary fractions use 2^-n for decimal part." },
  { q: "Big-endian stores:", options: ["LSB first", "MSB first", "Random", "None"], answer: 1, explanation: "Big-endian places most significant byte first." },
  { q: "Little-endian stores:", options: ["MSB first", "LSB first", "Random", "None"], answer: 1, explanation: "Little-endian places least significant byte first." },
  { q: "Parity bit is for:", options: ["Error detection", "Error correction", "No error", "None"], answer: 0, explanation: "Parity checks for single-bit errors." },
  { q: "Checksum is:", options: ["Sum of bits", "Sum of bytes", "No sum", "None"], answer: 1, explanation: "Checksum sums data for error detection." },
  { q: "Hamming code corrects:", options: ["No errors", "Single-bit errors", "Multiple", "None"], answer: 1, explanation: "Hamming code detects and corrects single errors." },
  { q: "Binary division:", options: ["Same as decimal", "Shifts and subtracts", "No division", "None"], answer: 1, explanation: "Binary division uses shifts and subtracts." },
  { q: "Binary square root:", options: ["Easy", "Iterative method", "No square root", "None"], answer: 1, explanation: "Binary square root uses iterative algorithms." }
];

const CA_BOOL_QUESTIONS = [
  { q: "Boolean algebra deals with:", options: ["Numbers", "True/false values", "Strings", "None"], answer: 1, explanation: "Boolean algebra uses true and false." },
  { q: "AND gate output is 1 when:", options: ["Any input 1", "Both inputs 1", "Any input 0", "None"], answer: 1, explanation: "AND is 1 only if both inputs are 1." },
  { q: "OR gate output is 1 when:", options: ["Both 0", "At least one input 1", "Both 1", "None"], answer: 1, explanation: "OR is 1 if any input is 1." },
  { q: "NOT gate inverts:", options: ["Input", "Output", "Nothing", "None"], answer: 0, explanation: "NOT flips the input value." },
  { q: "NAND is:", options: ["AND + NOT", "OR + NOT", "NOT only", "None"], answer: 0, explanation: "NAND is NOT of AND." },
  { q: "NOR is:", options: ["NOT of OR", "NOT of AND", "OR only", "None"], answer: 0, explanation: "NOR is NOT of OR." },
  { q: "XOR is 1 when:", options: ["Inputs same", "Inputs different", "Both 1", "None"], answer: 1, explanation: "XOR is 1 if inputs differ." },
  { q: "XNOR is 1 when:", options: ["Different", "Same inputs", "Both 0", "None"], answer: 1, explanation: "XNOR is 1 if inputs are same." },
  { q: "De Morgan's law: ¬(A∧B) = ", options: ["¬A∧¬B", "¬A∨¬B", "A∧B", "None"], answer: 0, explanation: "De Morgan: NOT of AND is OR of NOTs." },
  { q: "De Morgan's law: ¬(A∨B) = ", options: ["¬A∨¬B", "¬A∧¬B", "A∨B", "None"], answer: 1, explanation: "NOT of OR is AND of NOTs." },
  { q: "Boolean expression simplification uses:", options: ["Algebra", "K-maps", "Both", "None"], answer: 2, explanation: "Both algebraic and Karnaugh map methods." },
  { q: "Truth table for AND:", options: ["00:0,01:0,10:0,11:1", "00:0,01:1,10:1,11:1", "00:1,01:1,10:1,11:0", "None"], answer: 0, explanation: "AND truth table: only 11 gives 1." },
  { q: "Combinational circuit:", options: ["Has memory", "No memory, output depends on input", "Has feedback", "None"], answer: 1, explanation: "Combinational circuits have no state." },
  { q: "Sequential circuit:", options: ["No memory", "Has memory elements", "No feedback", "None"], answer: 1, explanation: "Sequential circuits have flip-flops for state." },
  { q: "Half adder adds:", options: ["Two bits", "Two 1-bit numbers", "Three bits", "None"], answer: 1, explanation: "Half adder sums two bits with carry." },
  { q: "Full adder adds:", options: ["Two bits", "Three bits with carry in", "Four bits", "None"], answer: 1, explanation: "Full adder includes carry in." },
  { q: "Multiplexer selects:", options: ["One input", "One of multiple inputs", "All inputs", "None"], answer: 1, explanation: "Mux chooses one input based on select lines." },
  { q: "Decoder converts:", options: ["Binary to decimal", "Binary to one-hot", "Decimal to binary", "None"], answer: 1, explanation: "Decoder activates one output line." },
  { q: "Flip-flop is:", options: ["Combinational", "Sequential element", "Gate", "None"], answer: 1, explanation: "Flip-flops store state." },
  { q: "SR flip-flop has inputs:", options: ["Set, Reset", "Clock, Data", "Enable", "None"], answer: 0, explanation: "SR has S and R inputs." },
  { q: "D flip-flop stores:", options: ["Input", "Data input on clock", "Previous", "None"], answer: 1, explanation: "D FF captures D on clock edge." },
  { q: "JK flip-flop is:", options: ["Same as SR", "Versatile with toggle", "Simple", "None"], answer: 1, explanation: "JK can toggle and has no forbidden state." },
  { q: "T flip-flop:", options: ["Toggles", "Sets", "Resets", "None"], answer: 0, explanation: "T FF toggles on each clock." },
  { q: "Counter counts:", options: ["Up", "Up or down", "Random", "None"], answer: 1, explanation: "Counters can be up, down, or bidirectional." },
  { q: "Register is:", options: ["Single bit", "Group of flip-flops", "Gate", "None"], answer: 1, explanation: "Register stores multiple bits." },
  { q: "Shift register shifts:", options: ["Left", "Left or right", "No shift", "None"], answer: 1, explanation: "Shift registers move bits." },
  { q: "State machine has:", options: ["States, transitions", "No states", "Only inputs", "None"], answer: 0, explanation: "FSM has states and transitions." },
  { q: "Moore machine output depends on:", options: ["Input", "State only", "Both", "None"], answer: 1, explanation: "Moore outputs depend on state." },
  { q: "Mealy machine output depends on:", options: ["State", "State and input", "Neither", "None"], answer: 1, explanation: "Mealy outputs depend on state and input." },
  { q: "Boolean function F = A + BC is:", options: ["SOP", "POS", "Both", "None"], answer: 0, explanation: "Sum of products form." }
];

const CA_KMAP_QUESTIONS = [
  { q: "K-map simplifies:", options: ["Numbers", "Boolean expressions", "Circuits", "None"], answer: 1, explanation: "K-maps minimize Boolean functions." },
  { q: "2-variable K-map has:", options: ["2 cells", "4 cells", "8 cells", "None"], answer: 1, explanation: "2 variables: 4 combinations." },
  { q: "3-variable K-map has:", options: ["4 cells", "8 cells", "16 cells", "None"], answer: 1, explanation: "3 variables: 8 cells." },
  { q: "4-variable K-map has:", options: ["8 cells", "16 cells", "32 cells", "None"], answer: 1, explanation: "4 variables: 16 cells." },
  { q: "K-map grouping:", options: ["1s only", "Adjacent 1s in powers of 2", "0s", "None"], answer: 1, explanation: "Group 1,2,4,8 adjacent cells." },
  { q: "Don't care in K-map:", options: ["Must be 1", "Can be 0 or 1", "Ignored", "None"], answer: 1, explanation: "Don't cares optimize grouping." },
  { q: "SOP from K-map:", options: ["Product terms", "Sum of products", "POS", "None"], answer: 1, explanation: "K-map gives minimized SOP." },
  { q: "POS from K-map:", options: ["Sum terms", "Product of sums", "SOP", "None"], answer: 1, explanation: "Grouping 0s gives POS." },
  { q: "K-map adjacency:", options: ["Edges only", "Wrap around edges", "No wrap", "None"], answer: 1, explanation: "Top/bottom and left/right wrap." },
  { q: "Prime implicant is:", options: ["Small group", "Largest possible group", "Any group", "None"], answer: 1, explanation: "Prime implicants are maximal groups." },
  { q: "Essential prime implicant:", options: ["Covers unique 1", "Any implicant", "No unique", "None"], answer: 0, explanation: "Essential covers 1s not covered elsewhere." },
  { q: "K-map for F = AB + AC:", options: ["Group corners", "Group edges", "No group", "None"], answer: 0, explanation: "AB and AC share A, group accordingly." },
  { q: "3-var K-map variables:", options: ["A,B", "A,B,C", "A,B,C,D", "None"], answer: 1, explanation: "3 variables: A,B,C." },
  { q: "Gray code in K-map:", options: ["Binary", "Adjacent differ by 1 bit", "Random", "None"], answer: 1, explanation: "K-map uses Gray code labeling." },
  { q: "Minimized expression:", options: ["Longer", "Shorter", "Same", "None"], answer: 1, explanation: "Minimization reduces literals." },
  { q: "K-map for XOR:", options: ["Diagonal", "Checkerboard", "All 1s", "None"], answer: 0, explanation: "XOR has 1s on diagonal." },
  { q: "K-map for AND:", options: ["One cell", "Corner cell", "All cells", "None"], answer: 1, explanation: "AND is 1 only for all 1s." },
  { q: "K-map for OR:", options: ["All except one", "All cells", "One cell", "None"], answer: 1, explanation: "OR is 0 only for all 0s." },
  { q: "4-var K-map shape:", options: ["Square", "Rectangle 4x4", "Circle", "None"], answer: 1, explanation: "4 variables: 4x4 grid." },
  { q: "K-map simplification reduces:", options: ["Gates", "Logic gates needed", "Variables", "None"], answer: 1, explanation: "Fewer terms mean fewer gates." },
  { q: "Overlapping groups in K-map:", options: ["Not allowed", "Allowed for coverage", "Forbidden", "None"], answer: 1, explanation: "Groups can overlap." },
  { q: "K-map for majority function:", options: ["3 of 4", "At least 3 variables 1", "All 1", "None"], answer: 1, explanation: "Majority: 3 or more 1s." },
  { q: "K-map entry:", options: ["0 or 1", "0,1,X", "Only 1", "None"], answer: 1, explanation: "Cells are 0,1, or X (don't care)." },
  { q: "K-map variable order:", options: ["Random", "Standard Gray code", "Binary", "None"], answer: 1, explanation: "Variables follow Gray code sequence." },
  { q: "5-variable K-map:", options: ["4x4", "Two 4x4 maps", "8x8", "None"], answer: 1, explanation: "5 variables use two 4x4 maps." },
  { q: "K-map for parity:", options: ["Even 1s", "Odd number of 1s", "Even", "None"], answer: 1, explanation: "Parity checks odd/even 1s." },
  { q: "K-map minimization is:", options: ["Exact", "Heuristic", "Random", "None"], answer: 0, explanation: "K-map gives exact minimization." },
  { q: "K-map for constant 1:", options: ["All cells", "One cell", "No cells", "None"], answer: 0, explanation: "Constant 1 is all 1s." },
  { q: "K-map for constant 0:", options: ["All 1s", "All 0s", "One 0", "None"], answer: 1, explanation: "Constant 0 is all 0s." },
  { q: "K-map tool is for:", options: ["Programming", "Logic minimization", "Arithmetic", "None"], answer: 1, explanation: "K-maps minimize logic expressions." }
];

const CA_ILP_QUESTIONS = [
  { q: "ILP stands for:", options: ["Instruction Level Parallelism", "Internal Level Processing", "None", "Parallel"], answer: 0, explanation: "ILP executes multiple instructions simultaneously." },
  { q: "Pipelining divides execution into:", options: ["One stage", "Multiple stages", "No stages", "None"], answer: 1, explanation: "Pipelining has fetch, decode, execute, etc." },
  { q: "Superscalar executes:", options: ["One per cycle", "Multiple per cycle", "None", "One"], answer: 1, explanation: "Superscalar issues multiple instructions per cycle." },
  { q: "Data dependency:", options: ["No issue", "RAW, WAR, WAW", "Only RAW", "None"], answer: 1, explanation: "Dependencies limit parallelism." },
  { q: "RAW dependency:", options: ["Write after read", "Read after write", "Write after write", "None"], answer: 1, explanation: "Read after write: later read depends on earlier write." },
  { q: "WAR dependency:", options: ["Read after write", "Write after read", "Write after write", "None"], answer: 1, explanation: "Write after read: write changes value read earlier." },
  { q: "WAW dependency:", options: ["Write after write", "Read after write", "Write after read", "None"], answer: 0, explanation: "Write after write: later write overwrites earlier." },
  { q: "Forwarding resolves:", options: ["Control hazards", "Data hazards", "Structural", "None"], answer: 1, explanation: "Forwarding passes results directly." },
  { q: "Branch prediction predicts:", options: ["Taken or not", "Data", "Memory", "None"], answer: 0, explanation: "Predicts if branch is taken." },
  { q: "Speculative execution:", options: ["Executes wrong", "Executes ahead, discards if wrong", "No execution", "None"], answer: 1, explanation: "Executes predicted path speculatively." },
  { q: "Out-of-order execution:", options: ["In order", "As resources available", "Sequential", "None"], answer: 1, explanation: "Executes ready instructions first." },
  { q: "Register renaming avoids:", options: ["WAW, WAR", "RAW", "All", "None"], answer: 0, explanation: "Renaming eliminates false dependencies." },
  { q: "VLIW stands for:", options: ["Very Long Instruction Word", "Variable Length Instruction Word", "None", "Word"], answer: 0, explanation: "VLIW packs multiple operations in one instruction." },
  { q: "SIMD is:", options: ["Single instruction, multiple data", "Multiple instruction, single data", "None", "Data"], answer: 0, explanation: "SIMD applies one operation to multiple data." },
  { q: "Vector processors use:", options: ["Scalar", "Vector operations", "Single data", "None"], answer: 1, explanation: "Vector processors handle array operations." },
  { q: "Loop unrolling increases:", options: ["Dependencies", "ILP by reducing loop overhead", "Hazards", "None"], answer: 1, explanation: "Unrolling exposes more parallelism." },
  { q: "Software pipelining:", options: ["Hardware", "Reorders instructions across iterations", "No reorder", "None"], answer: 1, explanation: "Software pipelining overlaps loop iterations." },
  { q: "Branch delay slot:", options: ["No delay", "Instruction after branch executes", "Before", "None"], answer: 1, explanation: "Delay slot instruction always executes." },
  { q: "Predicated execution:", options: ["No condition", "Executes based on predicate", "Always", "None"], answer: 1, explanation: "Predicates control execution." },
  { q: "ILP limit is:", options: ["Infinite", "Limited by dependencies and resources", "Zero", "None"], answer: 1, explanation: "Dependencies and hardware limit ILP." },
  { q: "Tomasulo's algorithm handles:", options: ["Out-of-order", "Register renaming and hazards", "In-order", "None"], answer: 1, explanation: "Tomasulo enables dynamic scheduling." },
  { q: "Reorder buffer:", options: ["No reorder", "Buffers out-of-order completion", "In-order", "None"], answer: 1, explanation: "Reorder buffer commits in order." },
  { q: "Scoreboarding:", options: ["No score", "Tracks hazards for in-order issue", "Out-of-order", "None"], answer: 1, explanation: "Scoreboarding controls instruction issue." },
  { q: "Hyperthreading provides:", options: ["Multiple cores", "Multiple threads per core", "One thread", "None"], answer: 1, explanation: "Hyperthreading shares resources for two threads." },
  { q: "Multicore increases:", options: ["Clock speed", "Parallelism via multiple cores", "Single core", "None"], answer: 1, explanation: "Multicore adds more processing units." },
  { q: "Amdahl's law applies to:", options: ["Parallel speedup", "Serial fraction limits speedup", "No limit", "None"], answer: 1, explanation: "Serial parts limit overall speedup." },
  { q: "Gustafson's law:", options: ["Same as Amdahl", "Speedup scales with problem size", "No scale", "None"], answer: 1, explanation: "Larger problems have more parallelism." },
  { q: "Cache coherence in ILP:", options: ["Not needed", "Ensures consistent data", "Inconsistent", "None"], answer: 1, explanation: "Coherence maintains data consistency." },
  { q: "Memory disambiguation:", options: ["No memory", "Determines if loads/stores conflict", "Always conflict", "None"], answer: 1, explanation: "Disambiguation checks memory dependencies." },
  { q: "ILP techniques include:", options: ["Pipelining only", "Pipelining, superscalar, out-of-order, speculation", "None", "One"], answer: 1, explanation: "Multiple techniques exploit ILP." }
];

const CA_PIPE_QUESTIONS = [
  { q: "Pipeline stages include:", options: ["Fetch only", "Fetch, decode, execute, memory, writeback", "Execute only", "None"], answer: 1, explanation: "Classic 5-stage pipeline." },
  { q: "Pipeline hazard types:", options: ["Structural", "Data, control, structural", "Data only", "None"], answer: 1, explanation: "Three main hazard types." },
  { q: "Structural hazard:", options: ["Data conflict", "Resource conflict", "Control conflict", "None"], answer: 1, explanation: "Resource unavailable for instruction." },
  { q: "Data hazard:", options: ["Resource", "Dependency on previous result", "Branch", "None"], answer: 1, explanation: "Data dependency stalls pipeline." },
  { q: "Control hazard:", options: ["Data", "Branch changes PC", "Resource", "None"], answer: 1, explanation: "Branches disrupt sequential fetch." },
  { q: "Forwarding bypasses:", options: ["Memory", "Register file for data hazards", "Cache", "None"], answer: 1, explanation: "Forwarding sends results directly." },
  { q: "Stall inserts:", options: ["NOP", "Bubble in pipeline", "No bubble", "None"], answer: 1, explanation: "Stall adds NOP to resolve hazard." },
  { q: "Branch prediction accuracy:", options: ["Always wrong", "Percentage correct", "Never", "None"], answer: 1, explanation: "Higher accuracy reduces stalls." },
  { q: "Static prediction:", options: ["Dynamic", "Always taken or not", "Runtime", "None"], answer: 0, explanation: "Static uses fixed strategy." },
  { q: "Dynamic prediction uses:", options: ["Fixed", "History of branches", "No history", "None"], answer: 1, explanation: "Dynamic learns from past behavior." },
  { q: "BTB stands for:", options: ["Branch Target Buffer", "Branch Table Buffer", "None", "Buffer"], answer: 0, explanation: "BTB caches branch targets." },
  { q: "Pipeline depth:", options: ["Stages", "Number of stages", "Width", "None"], answer: 1, explanation: "More stages increase depth." },
  { q: "Superpipelining:", options: ["Fewer stages", "More stages for higher frequency", "Same", "None"], answer: 1, explanation: "Superpipelining subdivides stages." },
  { q: "CPI in pipelined:", options: ["1", "Ideal 1, actual >1 due to stalls", "0", "None"], answer: 1, explanation: "Stalls increase CPI above 1." },
  { q: "Throughput:", options: ["Instructions per cycle", "IPC", "Same as CPI", "None"], answer: 1, explanation: "Throughput is instructions per cycle." },
  { q: "Pipeline speedup:", options: ["No speedup", "Depth times, minus overhead", "Half", "None"], answer: 1, explanation: "Speedup ≈ pipeline depth." },
  { q: "Loop unrolling in pipeline:", options: ["Increases hazards", "Reduces loop overhead", "No effect", "None"], answer: 1, explanation: "Unrolling exposes more ILP." },
  { q: "Delayed branch:", options: ["No delay", "Executes instruction after branch", "Before", "None"], answer: 1, explanation: "Delayed branch always executes slot." },
  { q: "Branch folding:", options: ["No fold", "Combines branch with operation", "Separate", "None"], answer: 1, explanation: "Folding integrates branch." },
  { q: "Exception in pipeline:", options: ["Ignored", "Requires precise interrupts", "Approximate", "None"], answer: 1, explanation: "Pipeline needs precise state for exceptions." },
  { q: "Precise interrupt:", options: ["Approximate", "Commits only completed instructions", "All", "None"], answer: 1, explanation: "Precise interrupts commit in order." },
  { q: "Reorder buffer for:", options: ["In-order", "Out-of-order completion", "No order", "None"], answer: 1, explanation: "Reorder buffer handles out-of-order." },
  { q: "Pipeline flush:", options: ["No flush", "Clears pipeline on misprediction", "Fills", "None"], answer: 1, explanation: "Flush discards wrong-path instructions." },
  { q: "Superscalar pipeline:", options: ["One wide", "Multiple instructions per stage", "Narrow", "None"], answer: 1, explanation: "Superscalar has multiple execution units." },
  { q: "VLIW pipeline:", options: ["Hardware scheduled", "Software scheduled", "No schedule", "None"], answer: 1, explanation: "VLIW relies on compiler scheduling." },
  { q: "Pipeline bubble:", options: ["Data", "NOP propagating through", "No bubble", "None"], answer: 1, explanation: "Bubble is idle slot from stall." },
  { q: "Data forwarding distance:", options: ["Far", "Shortens dependency latency", "Lengthens", "None"], answer: 1, explanation: "Forwarding reduces stall cycles." },
  { q: "Control dependence:", options: ["Data", "Branch outcome", "Resource", "None"], answer: 1, explanation: "Control depends on branch result." },
  { q: "Speculative execution risk:", options: ["No risk", "Wrong path execution wastes resources", "Correct", "None"], answer: 1, explanation: "Misprediction discards work." },
  { q: "Pipeline optimization:", options: ["No opt", "Reduce stalls, increase depth, forwarding", "Increase stalls", "None"], answer: 2, explanation: "Optimizations minimize stalls and maximize throughput." }
];

const CA_MIPS_QUESTIONS = [
  { q: "MIPS is:", options: ["CISC", "RISC architecture", "No type", "None"], answer: 1, explanation: "MIPS is a classic RISC ISA." },
  { q: "MIPS registers:", options: ["16", "32 general-purpose", "64", "None"], answer: 1, explanation: "MIPS has 32 GPRs." },
  { q: "MIPS instruction formats:", options: ["One", "R, I, J types", "Two", "None"], answer: 1, explanation: "Three main formats." },
  { q: "R-type instruction:", options: ["Immediate", "Register operands", "Jump", "None"], answer: 1, explanation: "R-type uses registers." },
  { q: "I-type instruction:", options: ["Register", "Immediate operand", "Jump", "None"], answer: 1, explanation: "I-type has immediate." },
  { q: "J-type instruction:", options: ["Register", "Immediate", "Jump target", "None"], answer: 2, explanation: "J-type for jumps." },
  { q: "MIPS load/store:", options: ["Register to register", "Memory to register", "Register to memory", "None"], answer: 1, explanation: "Load/store architecture." },
  { q: "MIPS addressing:", options: ["Register only", "Base + offset", "Absolute", "None"], answer: 1, explanation: "Base register + offset." },
  { q: "MIPS assembly add:", options: ["add $d, $s, $t", "add $d, $s, imm", "No add", "None"], answer: 0, explanation: "Add registers." },
  { q: "MIPS addi:", options: ["add $d, $s, $t", "add $d, $s, imm", "No addi", "None"], answer: 1, explanation: "Add immediate." },
  { q: "MIPS lw:", options: ["Load word", "lw $t, offset($s)", "No lw", "None"], answer: 1, explanation: "Load word from memory." },
  { q: "MIPS sw:", options: ["Store word", "sw $t, offset($s)", "No sw", "None"], answer: 0, explanation: "Store word to memory." },
  { q: "MIPS beq:", options: ["Branch if equal", "beq $s, $t, label", "No beq", "None"], answer: 1, explanation: "Branch on equal." },
  { q: "MIPS j:", options: ["Jump register", "j label", "No j", "None"], answer: 1, explanation: "Jump to label." },
  { q: "MIPS jal:", options: ["Jump and link", "jal label", "No jal", "None"], answer: 0, explanation: "Jump and save return address." },
  { q: "MIPS jr:", options: ["Jump", "jr $ra", "No jr", "None"], answer: 1, explanation: "Jump to register." },
  { q: "MIPS syscall:", options: ["System call", "syscall", "No syscall", "None"], answer: 0, explanation: "Invoke OS service." },
  { q: "MIPS $zero register:", options: ["Any value", "Always 0", "Variable", "None"], answer: 1, explanation: "$zero is hardwired to 0." },
  { q: "MIPS $ra:", options: ["Return address", "Argument", "Temporary", "None"], answer: 0, explanation: "Return address for jal." },
  { q: "MIPS $sp:", options: ["Stack pointer", "Frame pointer", "Global", "None"], answer: 0, explanation: "Stack pointer." },
  { q: "MIPS $gp:", options: ["Global pointer", "Stack", "Return", "None"], answer: 0, explanation: "Global data pointer." },
  { q: "MIPS $fp:", options: ["Frame pointer", "Stack pointer", "Global", "None"], answer: 0, explanation: "Frame pointer." },
  { q: "MIPS $v0, $v1:", options: ["Arguments", "Return values", "Temporaries", "None"], answer: 1, explanation: "Return values." },
  { q: "MIPS $a0-$a3:", options: ["Return", "Arguments", "Saved", "None"], answer: 1, explanation: "Argument registers." },
  { q: "MIPS $t0-$t9:", options: ["Saved", "Temporaries", "Arguments", "None"], answer: 1, explanation: "Temporary registers." },
  { q: "MIPS $s0-$s7:", options: ["Temporaries", "Saved registers", "Arguments", "None"], answer: 1, explanation: "Saved across calls." },
  { q: "MIPS pipeline:", options: ["No pipeline", "5-stage pipeline", "1-stage", "None"], answer: 1, explanation: "MIPS has 5-stage pipeline." },
  { q: "MIPS delay slot:", options: ["No delay", "Instruction after branch executes", "Before", "None"], answer: 1, explanation: "Branch delay slot." },
  { q: "MIPS endianness:", options: ["Little", "Big-endian", "Both", "None"], answer: 1, explanation: "MIPS is big-endian." },
  { q: "MIPS floating-point:", options: ["No FP", "Separate coprocessor", "Integrated", "None"], answer: 1, explanation: "MIPS has FP coprocessor." }
];

const CA_DIGITAL_QUESTIONS = [
  { q: "Digital computer uses:", options: ["Analog", "Discrete values", "Continuous", "None"], answer: 1, explanation: "Digital uses binary signals." },
  { q: "ALU performs:", options: ["I/O", "Arithmetic and logic", "Memory", "None"], answer: 1, explanation: "ALU is arithmetic-logic unit." },
  { q: "Control unit:", options: ["Executes", "Generates control signals", "Stores", "None"], answer: 1, explanation: "Control unit sequences operations." },
  { q: "Memory hierarchy:", options: ["One level", "Registers, cache, RAM, disk", "No hierarchy", "None"], answer: 1, explanation: "Multiple levels for speed/cost." },
  { q: "Cache levels:", options: ["L1 only", "L1, L2, L3", "No levels", "None"], answer: 1, explanation: "Multiple cache levels." },
  { q: "RAM is:", options: ["Read-only", "Random access memory", "Sequential", "None"], answer: 1, explanation: "RAM allows random access." },
  { q: "ROM is:", options: ["Writable", "Read-only memory", "Volatile", "None"], answer: 1, explanation: "ROM is non-volatile read-only." },
  { q: "Bus system:", options: ["No bus", "Data, address, control buses", "One bus", "None"], answer: 1, explanation: "Buses interconnect components." },
  { q: "I/O devices:", options: ["CPU only", "Keyboard, display, disk", "Memory", "None"], answer: 1, explanation: "I/O interfaces peripherals." },
  { q: "Interrupt controller:", options: ["No interrupts", "Manages interrupts", "Executes", "None"], answer: 1, explanation: "Handles device interrupts." },
  { q: "DMA stands for:", options: ["Direct Memory Access", "Dynamic Memory Allocation", "None", "Access"], answer: 0, explanation: "DMA transfers data without CPU." },
  { q: "Von Neumann bottleneck:", options: ["No bottleneck", "Shared memory bus", "Separate", "None"], answer: 1, explanation: "Shared bus limits performance." },
  { q: "Harvard architecture:", options: ["Shared memory", "Separate I and D memories", "One memory", "None"], answer: 1, explanation: "Harvard has separate memories." },
  { q: "Multiprocessor:", options: ["One CPU", "Multiple CPUs", "No CPU", "None"], answer: 1, explanation: "Multiple processors." },
  { q: "SMP is:", options: ["Asymmetric", "Symmetric multiprocessing", "No symmetry", "None"], answer: 1, explanation: "SMP shares memory equally." },
  { q: "NUMA:", options: ["Uniform access", "Non-uniform memory access", "No access", "None"], answer: 1, explanation: "Memory access time varies." },
  { q: "Vector processor:", options: ["Scalar", "Handles vectors", "Single data", "None"], answer: 1, explanation: "Optimized for array operations." },
  { q: "GPU is:", options: ["CPU", "Graphics processing unit", "Memory", "None"], answer: 1, explanation: "GPU for parallel graphics." },
  { q: "FPGA is:", options: ["Fixed", "Field-programmable gate array", "Software", "None"], answer: 1, explanation: "FPGA is reconfigurable hardware." },
  { q: "ASIC is:", options: ["Programmable", "Application-specific integrated circuit", "General", "None"], answer: 1, explanation: "ASIC is custom hardware." },
  { q: "Embedded system:", options: ["General", "Special-purpose computer", "No purpose", "None"], answer: 1, explanation: "Embedded for specific tasks." },
  { q: "Real-time system:", options: ["No timing", "Meets deadlines", "Flexible", "None"], answer: 1, explanation: "Real-time has timing constraints." },
  { q: "Microcontroller:", options: ["No memory", "CPU + memory + I/O on chip", "External", "None"], answer: 1, explanation: "Microcontroller is integrated." },
  { q: "DSP is:", options: ["General", "Digital signal processor", "Analog", "None"], answer: 1, explanation: "DSP for signal processing." },
  { q: "Quantum computer:", options: ["Bits", "Qubits", "No bits", "None"], answer: 1, explanation: "Uses quantum bits." },
  { q: "Neural processor:", options: ["No AI", "Accelerates neural networks", "General", "None"], answer: 1, explanation: "For AI computations." },
  { q: "Memory controller:", options: ["No control", "Manages memory access", "CPU", "None"], answer: 1, explanation: "Controls memory operations." },
  { q: "Northbridge:", options: ["South", "Connects CPU to memory", "I/O", "None"], answer: 0, explanation: "Northbridge for high-speed." },
  { q: "Southbridge:", options: ["North", "Connects to I/O devices", "Memory", "None"], answer: 1, explanation: "Southbridge for peripherals." },
  { q: "PCIe is:", options: ["Old bus", "High-speed serial bus", "Parallel", "None"], answer: 1, explanation: "PCIe is modern bus standard." }
];

const CA_CONTROL_QUESTIONS = [
  { q: "Control unit design:", options: ["Hardwired", "Microprogrammed", "Both", "None"], answer: 2, explanation: "Two main approaches." },
  { q: "Hardwired control:", options: ["ROM", "Combinational logic + FSM", "RAM", "None"], answer: 1, explanation: "Uses gates and flip-flops." },
  { q: "Microprogrammed control:", options: ["Logic", "ROM with microinstructions", "Gates", "None"], answer: 1, explanation: "Uses microcode in ROM." },
  { q: "FSM in control:", options: ["No state", "Finite state machine", "Infinite", "None"], answer: 1, explanation: "FSM controls sequencing." },
  { q: "Control signals:", options: ["Random", "Enable registers, ALU ops", "Data", "None"], answer: 1, explanation: "Signals control operations." },
  { q: "Instruction cycle:", options: ["One phase", "Fetch, decode, execute", "No cycle", "None"], answer: 1, explanation: "Phases of execution." },
  { q: "Fetch phase:", options: ["Execute", "Get instruction from memory", "Decode", "None"], answer: 1, explanation: "Fetch instruction." },
  { q: "Decode phase:", options: ["Fetch", "Interpret instruction", "Execute", "None"], answer: 1, explanation: "Determine operation." },
  { q: "Execute phase:", options: ["Decode", "Perform operation", "Fetch", "None"], answer: 1, explanation: "Carry out instruction." },
  { q: "Microinstruction:", options: ["Macro", "Low-level control word", "High-level", "None"], answer: 1, explanation: "Microinstruction controls hardware." },
  { q: "Microprogram:", options: ["One instruction", "Sequence of microinstructions", "No sequence", "None"], answer: 1, explanation: "Microprogram implements ISA." },
  { q: "Horizontal microcode:", options: ["Vertical", "Wide, explicit signals", "Narrow", "None"], answer: 1, explanation: "Horizontal has many bits." },
  { q: "Vertical microcode:", options: ["Wide", "Compact, decoded", "Explicit", "None"], answer: 1, explanation: "Vertical is encoded." },
  { q: "Nanoprogramming:", options: ["Micro", "Even lower level", "Macro", "None"], answer: 1, explanation: "Nanocode for microinstructions." },
  { q: "Control store:", options: ["RAM", "ROM for microcode", "Cache", "None"], answer: 1, explanation: "Stores microprogram." },
  { q: "PLA in control:", options: ["No PLA", "Programmable logic array", "Fixed", "None"], answer: 1, explanation: "PLA implements logic." },
  { q: "Sequencer:", options: ["No sequence", "Controls microinstruction flow", "Random", "None"], answer: 1, explanation: "Sequencer advances microprogram." },
  { q: "Branching in microcode:", options: ["Linear", "Conditional branches", "No branch", "None"], answer: 1, explanation: "Microcode can branch." },
  { q: "Exception handling:", options: ["Normal", "Alters control flow", "No alter", "None"], answer: 1, explanation: "Exceptions change sequence." },
  { q: "Interrupt handling:", options: ["Ignored", "Saves state, services", "No save", "None"], answer: 1, explanation: "Interrupts pause execution." },
  { q: "Trap:", options: ["Hardware", "Software-initiated exception", "External", "None"], answer: 1, explanation: "Trap is software exception." },
  { q: "Precise interrupt:", options: ["Approximate", "Commits only completed", "All", "None"], answer: 1, explanation: "Precise state for interrupts." },
  { q: "Control hazards:", options: ["Data", "Branch disrupts fetch", "Structural", "None"], answer: 1, explanation: "Control changes PC." },
  { q: "Branch prediction:", options: ["No predict", "Predicts branch outcome", "Always wrong", "None"], answer: 1, explanation: "Reduces control stalls." },
  { q: "Speculative execution:", options: ["Certain", "Executes predicted path", "No execute", "None"], answer: 1, explanation: "Executes ahead of certainty." },
  { q: "Out-of-order control:", options: ["In order", "Executes ready instructions", "Sequential", "None"], answer: 1, explanation: "Improves performance." },
  { q: "Scoreboarding:", options: ["No board", "Tracks hazards", "Random", "None"], answer: 1, explanation: "Scoreboarding controls issue." },
  { q: "Tomasulo's algorithm:", options: ["Static", "Dynamic scheduling", "No dynamic", "None"], answer: 1, explanation: "Tomasulo handles dependencies." },
  { q: "Reorder buffer:", options: ["No reorder", "Buffers completion", "In order", "None"], answer: 1, explanation: "Commits in order." },
  { q: "Control unit complexity:", options: ["Simple", "Increases with ISA", "Constant", "None"], answer: 1, explanation: "More instructions complicate control." }
];

const CA_CIRCUIT_QUESTIONS = [
  { q: "Combinational circuit:", options: ["Memory", "Output depends on input", "State", "None"], answer: 1, explanation: "No feedback, no state." },
  { q: "Sequential circuit:", options: ["No memory", "Has memory elements", "Combinational", "None"], answer: 1, explanation: "Has flip-flops." },
  { q: "Half adder:", options: ["Two bits", "Sums two bits", "Three bits", "None"], answer: 1, explanation: "Sum and carry for two bits." },
  { q: "Full adder:", options: ["Two bits", "Sums three bits", "Four bits", "None"], answer: 1, explanation: "Includes carry in." },
  { q: "Multiplexer:", options: ["One input", "Selects one of many", "All inputs", "None"], answer: 1, explanation: "Mux selects input." },
  { q: "Demultiplexer:", options: ["Many to one", "One to many", "One to one", "None"], answer: 1, explanation: "Demux routes to output." },
  { q: "Decoder:", options: ["Encodes", "Binary to one-hot", "No decode", "None"], answer: 1, explanation: "Activates one line." },
  { q: "Encoder:", options: ["Decodes", "One-hot to binary", "No encode", "None"], answer: 1, explanation: "Priority encoder." },
  { q: "Comparator:", options: ["Adds", "Compares magnitudes", "No compare", "None"], answer: 1, explanation: "Equality or magnitude." },
  { q: "ALU operations:", options: ["One", "Add, subtract, AND, OR", "None", "One"], answer: 1, explanation: "Arithmetic and logic." },
  { q: "Flip-flop types:", options: ["One", "SR, D, JK, T", "None", "One"], answer: 1, explanation: "Various flip-flops." },
  { q: "SR flip-flop:", options: ["No S R", "Set and reset", "Data", "None"], answer: 1, explanation: "Asynchronous set/reset." },
  { q: "D flip-flop:", options: ["Set reset", "Delays data", "Toggle", "None"], answer: 1, explanation: "Stores data input." },
  { q: "JK flip-flop:", options: ["No toggle", "Toggle mode", "Data only", "None"], answer: 1, explanation: "Can toggle." },
  { q: "T flip-flop:", options: ["Data", "Toggles", "Set", "None"], answer: 0, explanation: "Toggles on clock." },
  { q: "Master-slave FF:", options: ["One stage", "Two stages for race-free", "No stages", "None"], answer: 1, explanation: "Prevents races." },
  { q: "Register:", options: ["One bit", "Group of FFs", "Memory", "None"], answer: 1, explanation: "Stores word." },
  { q: "Shift register:", options: ["No shift", "Shifts bits", "Static", "None"], answer: 1, explanation: "Serial/parallel shift." },
  { q: "Counter types:", options: ["One", "Up, down, ring", "No count", "None"], answer: 1, explanation: "Various counters." },
  { q: "Synchronous counter:", options: ["Async", "Clocked together", "Ripple", "None"], answer: 1, explanation: "All FFs clocked." },
  { q: "Asynchronous counter:", options: ["Clocked", "Ripple carry", "Synchronous", "None"], answer: 1, explanation: "Carry propagates." },
  { q: "State machine:", options: ["No states", "States and transitions", "Inputs only", "None"], answer: 1, explanation: "FSM model." },
  { q: "Moore machine:", options: ["Input dependent", "Output on state", "Both", "None"], answer: 1, explanation: "Output depends on state." },
  { q: "Mealy machine:", options: ["State only", "Output on state and input", "Neither", "None"], answer: 1, explanation: "Output depends on both." },
  { q: "State diagram:", options: ["Table", "Graphical states", "Code", "None"], answer: 1, explanation: "Circles and arrows." },
  { q: "State table:", options: ["Diagram", "Tabular form", "No table", "None"], answer: 1, explanation: "Rows for states." },
  { q: "Karnaugh map for:", options: ["Sequential", "Combinational minimization", "Memory", "None"], answer: 1, explanation: "K-maps for logic." },
  { q: "Don't care in circuit:", options: ["Must care", "Optimize", "No care", "None"], answer: 1, explanation: "Don't cares simplify." },
  { q: "Race condition:", options: ["No race", "Unpredictable output", "Predictable", "None"], answer: 1, explanation: "Timing issues." },
  { q: "Hazard in circuit:", options: ["No hazard", "Glitch from delay", "No glitch", "None"], answer: 1, explanation: "Transient glitch." }
];

const CA_MULTI_QUESTIONS = [
  { q: "Multitasking:", options: ["One task", "Multiple tasks share CPU", "No share", "None"], answer: 1, explanation: "Time-sharing." },
  { q: "Multiprocessing:", options: ["One CPU", "Multiple CPUs", "No CPU", "None"], answer: 1, explanation: "Parallel CPUs." },
  { q: "Process:", options: ["Thread", "Program in execution", "No execution", "None"], answer: 1, explanation: "Running program." },
  { q: "Thread:", options: ["Process", "Lightweight process", "Heavy", "None"], answer: 1, explanation: "Shares memory." },
  { q: "Context switch:", options: ["No switch", "Saves/restores state", "No save", "None"], answer: 1, explanation: "Switches tasks." },
  { q: "Scheduler:", options: ["No schedule", "Decides task execution", "Random", "None"], answer: 1, explanation: "OS scheduler." },
  { q: "Preemptive scheduling:", options: ["Non-preemptive", "Interrupts running task", "No interrupt", "None"], answer: 1, explanation: "Forces switch." },
  { q: "Round-robin:", options: ["Priority", "Time slices", "No slices", "None"], answer: 1, explanation: "Fair time sharing." },
  { q: "Priority scheduling:", options: ["No priority", "Higher priority first", "Random", "None"], answer: 1, explanation: "Priority based." },
  { q: "Deadlock:", options: ["No block", "Circular wait", "No wait", "None"], answer: 0, explanation: "Resources blocked." },
  { q: "Deadlock conditions:", options: ["One", "Mutual exclusion, hold-wait, no preemption, circular wait", "None", "One"], answer: 1, explanation: "Coffman conditions." },
  { q: "Semaphore:", options: ["No sync", "Synchronization primitive", "Async", "None"], answer: 1, explanation: "Controls access." },
  { q: "Mutex:", options: ["Multiple", "Mutual exclusion", "No exclusion", "None"], answer: 1, explanation: "Binary semaphore." },
  { q: "Monitor:", options: ["Low-level", "High-level sync", "No level", "None"], answer: 1, explanation: "Object with sync." },
  { q: "Race condition:", options: ["No race", "Unpredictable due to timing", "Predictable", "None"], answer: 1, explanation: "Concurrent access issue." },
  { q: "Critical section:", options: ["Non-critical", "Code accessing shared", "No access", "None"], answer: 1, explanation: "Shared resource code." },
  { q: "Peterson's algorithm:", options: ["No algorithm", "Software mutual exclusion", "Hardware", "None"], answer: 1, explanation: "Two-process sync." },
  { q: "Spinlock:", options: ["Blocking", "Busy wait", "No wait", "None"], answer: 1, explanation: "Waits in loop." },
  { q: "SMP:", options: ["Asymmetric", "Symmetric multiprocessing", "No symmetry", "None"], answer: 1, explanation: "Equal processors." },
  { q: "NUMA:", options: ["Uniform", "Non-uniform access", "Uniform", "None"], answer: 1, explanation: "Varying access times." },
  { q: "Cache coherence:", options: ["Inconsistent", "Maintains consistency", "No maintain", "None"], answer: 1, explanation: "Shared data consistent." },
  { q: "MESI protocol:", options: ["No protocol", "Cache coherence states", "No states", "None"], answer: 1, explanation: "Modified, Exclusive, Shared, Invalid." },
  { q: "False sharing:", options: ["No false", "Contention on cache line", "True sharing", "None"], answer: 1, explanation: "Unrelated data in line." },
  { q: "Amdahl's law:", options: ["Infinite speedup", "Serial fraction limits", "No limit", "None"], answer: 1, explanation: "Parallel speedup limit." },
  { q: "Gustafson's law:", options: ["Same", "Speedup with size", "No size", "None"], answer: 1, explanation: "Scales with problem." },
  { q: "Flynn's taxonomy:", options: ["Memory", "SISD, SIMD, MISD, MIMD", "No taxonomy", "None"], answer: 1, explanation: "Classifies architectures." },
  { q: "SIMD:", options: ["Single data", "Single instruction, multiple data", "Multiple instruction", "None"], answer: 1, explanation: "Vector operations." },
  { q: "MIMD:", options: ["Single", "Multiple instruction, multiple data", "No multiple", "None"], answer: 1, explanation: "General parallel." },
  { q: "Hyperthreading:", options: ["Multiple cores", "Multiple threads per core", "One thread", "None"], answer: 1, explanation: "Shares core resources." },
  { q: "Multicore:", options: ["One core", "Multiple cores on chip", "External", "None"], answer: 1, explanation: "Integrated cores." }
];
const COMARCHI_QUESTION_BANKS = {
  21: CA_INTRO_QUESTIONS,
  22: CA_NUM_QUESTIONS,
  23: CA_BOOL_QUESTIONS,
  24: CA_KMAP_QUESTIONS,
  25: CA_ILP_QUESTIONS,
  26: CA_PIPE_QUESTIONS,
  27: CA_MIPS_QUESTIONS,
  28: CA_DIGITAL_QUESTIONS,
  29: CA_CONTROL_QUESTIONS,
  30: CA_CIRCUIT_QUESTIONS,
  31: CA_MULTI_QUESTIONS
};

const COMARCHI_MODULE = {
  id: 'ca',
  name: 'Computer Architecture',
  icon: '🖥️',
  color: '#f5c842',
  desc: 'CPU design, memory hierarchy, instruction sets & pipelines.',
  active: true,
  subjects: [21,22,23,24,25,26,27,28,29,30,31]
};
