// Computer Systems questions extracted from app (1)(1).js

const ICS1_QUESTIONS = [
  { q:"What is a computer system?", options:["Only hardware","Only software","Hardware and software working together","A single program"], answer:2, explanation:"A computer system consists of both hardware and software components that work together to process data." },
  { q:"Which is NOT a component of a computer system?", options:["Input devices","Processing unit","Storage devices","Cooking recipes"], answer:3, explanation:"Cooking recipes are not part of computer systems. The others are essential components." },
  { q:"What does CPU stand for?", options:["Computer Personal Unit","Central Processing Unit","Computer Power Unit","Central Program Unit"], answer:1, explanation:"CPU stands for Central Processing Unit, the brain of the computer." },
  { q:"Which device is used for input?", options:["Monitor","Printer","Keyboard","Speaker"], answer:2, explanation:"Keyboard is an input device that allows users to enter data into the computer." },
  { q:"Which device is used for output?", options:["Mouse","Scanner","Monitor","Microphone"], answer:2, explanation:"Monitor displays information and is considered an output device." },
  { q:"What is software?", options:["Physical parts of computer","Programs and instructions","Computer case","Power supply"], answer:1, explanation:"Software consists of programs, applications, and instructions that tell hardware what to do." },
  { q:"What is the main function of an operating system?", options:["Play games","Manage computer resources","Create documents","Browse internet"], answer:1, explanation:"Operating systems manage hardware resources, run programs, and provide user interfaces." },
  { q:"Which is an example of system software?", options:["Word processor","Video game","Operating system","Web browser"], answer:2, explanation:"Operating system is system software that manages the computer's basic functions." },
  { q:"What does RAM stand for?", options:["Random Access Memory","Read And Modify","Rapid Action Module","Remote Access Memory"], answer:0, explanation:"RAM stands for Random Access Memory, used for temporary data storage." },
  { q:"What is the purpose of storage devices?", options:["Process data","Display output","Store data permanently","Input commands"], answer:2, explanation:"Storage devices like hard drives store data and programs permanently." },
  { q:"Which component executes program instructions?", options:["Hard drive","Monitor","CPU","Keyboard"], answer:2, explanation:"The CPU executes instructions and performs calculations." },
  { q:"What is a program?", options:["Hardware device","Set of instructions","Computer case","Power cord"], answer:1, explanation:"A program is a set of instructions that tells the computer what to do." },
  { q:"Which is NOT an output device?", options:["Printer","Monitor","Speaker","Mouse"], answer:3, explanation:"Mouse is an input device, while the others are output devices." },
  { q:"What is the information processing cycle?", options:["Input → Process → Output → Storage","Storage → Input → Process → Output","Output → Storage → Input → Process","Process → Output → Input → Storage"], answer:0, explanation:"The standard information processing cycle is Input → Process → Output → Storage." },
  { q:"What is data?", options:["Computer programs","Raw facts and figures","Processed information","Hardware components"], answer:1, explanation:"Data consists of raw facts and figures that can be processed into information." },
  { q:"What is information?", options:["Raw facts","Processed data","Computer hardware","Software programs"], answer:1, explanation:"Information is data that has been processed and organized to be meaningful." },
  { q:"Which is an example of application software?", options:["Windows OS","Linux kernel","Microsoft Word","BIOS"], answer:2, explanation:"Microsoft Word is application software for creating documents." },
  { q:"What does GUI stand for?", options:["General User Interface","Graphical User Interface","Global User Input","Graphics Unit Interface"], answer:1, explanation:"GUI stands for Graphical User Interface, which uses graphics for user interaction." },
  { q:"What is a computer network?", options:["Single computer","Group of connected computers","Computer program","Storage device"], answer:1, explanation:"A computer network is a group of computers connected to share resources." },
  { q:"What is the internet?", options:["Single website","Network of networks","Computer program","Storage device"], answer:1, explanation:"The internet is a global network of interconnected computer networks." },
  { q:"What is a bit?", options:["Computer program","Smallest unit of data","Computer hardware","Software application"], answer:1, explanation:"A bit is the smallest unit of data in computing, representing 0 or 1." },
  { q:"What is a byte?", options:["8 bits","4 bits","16 bits","32 bits"], answer:0, explanation:"A byte consists of 8 bits." },
  { q:"What is binary system?", options:["Decimal numbers","Base-2 number system","Base-10 system","Hexadecimal"], answer:1, explanation:"Binary system uses only two digits: 0 and 1." },
  { q:"What is an algorithm?", options:["Computer hardware","Step-by-step procedure","Data storage","Output device"], answer:1, explanation:"An algorithm is a step-by-step procedure for solving a problem." },
  { q:"What is programming?", options:["Building hardware","Writing instructions for computers","Designing networks","Creating data"], answer:1, explanation:"Programming involves writing instructions that computers can execute." },
  { q:"What is a bug in programming?", options:["Hardware fault","Error in program","Network issue","Storage problem"], answer:1, explanation:"A bug is an error or flaw in a computer program." },
  { q:"What is debugging?", options:["Writing programs","Finding and fixing errors","Designing hardware","Creating networks"], answer:1, explanation:"Debugging is the process of finding and removing errors from programs." },
  { q:"What is a variable in programming?", options:["Fixed value","Changing value storage","Computer hardware","Program output"], answer:1, explanation:"A variable is a storage location that can hold changing values." },
  { q:"What is a loop in programming?", options:["Single instruction","Repeated execution","Program end","Data storage"], answer:1, explanation:"A loop allows repeated execution of a block of code." },
  { q:"What is computer security?", options:["Fast processing","Protection from threats","Large storage","Colorful display"], answer:1, explanation:"Computer security involves protecting systems from unauthorized access and threats." }
];

const ICS2_QUESTIONS = [
  { q:"Who invented the mechanical calculator?", options:["Charles Babbage","Ada Lovelace","Blaise Pascal","Alan Turing"], answer:2, explanation:"Blaise Pascal invented the mechanical calculator in 1642." },
  { q:"What did Charles Babbage design?", options:["First computer","Analytical Engine","ENIAC","Transistor"], answer:1, explanation:"Charles Babbage designed the Analytical Engine in 1837." },
  { q:"Who is considered the first programmer?", options:["Charles Babbage","Ada Lovelace","Alan Turing","John von Neumann"], answer:1, explanation:"Ada Lovelace wrote the first computer program for Babbage's Analytical Engine." },
  { q:"When was ENIAC completed?", options:["1930","1945","1950","1960"], answer:1, explanation:"ENIAC was completed in 1945." },
  { q:"What was ENIAC?", options:["Mechanical calculator","First electronic computer","Personal computer","Supercomputer"], answer:1, explanation:"ENIAC was the first electronic general-purpose computer." },
  { q:"Who invented the transistor?", options:["William Shockley","John Bardeen","Walter Brattain","All of them"], answer:3, explanation:"The transistor was invented by William Shockley, John Bardeen, and Walter Brattain in 1947." },
  { q:"When were integrated circuits invented?", options:["1947","1958","1965","1970"], answer:1, explanation:"Integrated circuits were invented by Jack Kilby and Robert Noyce in 1958." },
  { q:"What is the first programming language?", options:["FORTRAN","COBOL","Assembly","Machine code"], answer:0, explanation:"FORTRAN was the first high-level programming language, developed in 1957." },
  { q:"When was the first personal computer released?", options:["1970","1975","1980","1985"], answer:1, explanation:"The Altair 8800, considered the first personal computer, was released in 1975." },
  { q:"What does GUI stand for?", options:["General User Interface","Graphical User Interface","Global User Input","Graphics Unit Interface"], answer:1, explanation:"GUI stands for Graphical User Interface." },
  { q:"When was the World Wide Web invented?", options:["1980","1989","1990","1995"], answer:1, explanation:"Tim Berners-Lee invented the World Wide Web in 1989." },
  { q:"What is the abacus?", options:["First electronic computer","Ancient calculating tool","Modern calculator","Supercomputer"], answer:1, explanation:"The abacus is an ancient calculating tool used for arithmetic." },
  { q:"Who developed the difference engine?", options:["Ada Lovelace","Charles Babbage","Blaise Pascal","Gottfried Leibniz"], answer:1, explanation:"Charles Babbage developed the difference engine for calculating polynomial functions." },
  { q:"What was the purpose of ENIAC?", options:["Word processing","Military calculations","Gaming","Internet browsing"], answer:1, explanation:"ENIAC was built for military calculations, particularly artillery firing tables." },
  { q:"What replaced vacuum tubes?", options:["Transistors","Integrated circuits","Microprocessors","Hard drives"], answer:0, explanation:"Transistors replaced vacuum tubes, making computers smaller and more reliable." },
  { q:"When was the mouse invented?", options:["1960","1964","1970","1980"], answer:1, explanation:"Douglas Engelbart invented the computer mouse in 1964." },
  { q:"What is the significance of 1971?", options:["First computer","First microprocessor","First network","First software"], answer:1, explanation:"The first microprocessor (Intel 4004) was released in 1971." },
  { q:"Who coined the term 'computer'?", options:["Charles Babbage","Ada Lovelace","Herman Hollerith","Alan Turing"], answer:2, explanation:"Herman Hollerith coined the term 'computer' for his tabulating machine." },
  { q:"What was the Colossus computer used for?", options:["Business","Code breaking","Scientific research","Education"], answer:1, explanation:"Colossus was used by British intelligence for code breaking during WWII." },
  { q:"When was the first computer bug found?", options:["1940","1945","1947","1950"], answer:2, explanation:"The first computer bug was found in 1947 at Harvard University." },
  { q:"What is the Turing Machine?", options:["Real computer","Theoretical model","Calculator","Printer"], answer:1, explanation:"The Turing Machine is a theoretical model of computation proposed by Alan Turing." },
  { q:"When was the first computer game created?", options:["1950","1952","1960","1970"], answer:1, explanation:"The first computer game, OXO (tic-tac-toe), was created in 1952." },
  { q:"What is the von Neumann architecture?", options:["Computer design","Programming language","Network protocol","Storage system"], answer:0, explanation:"Von Neumann architecture describes the basic structure of modern computers." },
  { q:"When was the first computer network created?", options:["1950","1960","1969","1980"], answer:2, explanation:"ARPANET, the first computer network, was created in 1969." },
  { q:"What is the significance of 1981?", options:["First PC","First laptop","First smartphone","First internet"], answer:0, explanation:"IBM PC was released in 1981, popularizing personal computing." },
  { q:"When was the first laptop computer released?", options:["1975","1980","1985","1990"], answer:1, explanation:"The first laptop computer was released in 1981." },
  { q:"What is the internet?", options:["Single network","Network of networks","Computer program","Storage device"], answer:1, explanation:"The internet is a global network of interconnected networks." },
  { q:"When was email invented?", options:["1960","1971","1980","1990"], answer:1, explanation:"Email was invented by Ray Tomlinson in 1971." },
  { q:"What is cloud computing?", options:["Weather prediction","Remote computing","Local storage","Hardware design"], answer:1, explanation:"Cloud computing delivers computing services over the internet." },
  { q:"When was the first smartphone released?", options:["1990","1995","2000","2007"], answer:3, explanation:"The first iPhone was released in 2007, popularizing smartphones." }
];

const ICS3_QUESTIONS = [
  { q:"What is the CPU?", options:["Central Processing Unit","Computer Power Unit","Central Program Unit","Computer Personal Unit"], answer:0, explanation:"CPU stands for Central Processing Unit, the brain of the computer." },
  { q:"What does the CPU do?", options:["Store data","Execute instructions","Display output","Input data"], answer:1, explanation:"The CPU executes program instructions and performs calculations." },
  { q:"What are the main components of CPU?", options:["ALU and CU","RAM and ROM","Hard drive and SSD","Monitor and keyboard"], answer:0, explanation:"CPU consists of Arithmetic Logic Unit (ALU) and Control Unit (CU)." },
  { q:"What is RAM?", options:["Read Access Memory","Random Access Memory","Rapid Action Module","Remote Access Memory"], answer:1, explanation:"RAM stands for Random Access Memory, used for temporary data storage." },
  { q:"Is RAM volatile or non-volatile?", options:["Volatile","Non-volatile","Both","Neither"], answer:0, explanation:"RAM is volatile memory that loses data when power is turned off." },
  { q:"What is ROM?", options:["Read Only Memory","Random Only Memory","Rapid Output Module","Remote Only Memory"], answer:0, explanation:"ROM stands for Read Only Memory, containing permanent instructions." },
  { q:"What is the motherboard?", options:["Computer case","Main circuit board","Power supply","Monitor"], answer:1, explanation:"Motherboard is the main circuit board that connects all computer components." },
  { q:"What is a hard drive?", options:["Temporary storage","Permanent storage","Processing unit","Input device"], answer:1, explanation:"Hard drive provides permanent storage for data and programs." },
  { q:"What is an SSD?", options:["Solid State Drive","Super Speed Device","System Storage Disk","Secure Storage Device"], answer:0, explanation:"SSD stands for Solid State Drive, a type of permanent storage." },
  { q:"What is the difference between HDD and SSD?", options:["HDD uses disks, SSD uses chips","HDD is faster","SSD uses disks","No difference"], answer:0, explanation:"HDD uses spinning disks while SSD uses flash memory chips." },
  { q:"What is a graphics card?", options:["Sound device","Video display processor","Network card","Storage device"], answer:1, explanation:"Graphics card processes and renders images for display." },
  { q:"What is a sound card?", options:["Video device","Audio processor","Network device","Storage device"], answer:1, explanation:"Sound card processes audio signals for speakers or headphones." },
  { q:"What is a network card?", options:["Video device","Audio device","Network interface","Storage device"], answer:2, explanation:"Network card enables computer to connect to networks." },
  { q:"What is the power supply unit?", options:["PSU","Converts AC to DC","Provides power","All of the above"], answer:3, explanation:"PSU converts AC power to DC and supplies power to components." },
  { q:"What is a bus in computer architecture?", options:["Pathway for data","Storage device","Processing unit","Input device"], answer:0, explanation:"A bus is a communication pathway that transfers data between components." },
  { q:"What is the system clock?", options:["Time display","Timing signal generator","Storage device","Input device"], answer:1, explanation:"System clock generates timing signals that synchronize computer operations." },
  { q:"What is cache memory?", options:["Slow memory","Fast temporary storage","Permanent storage","Input device"], answer:1, explanation:"Cache memory is fast memory that stores frequently used data." },
  { q:"What are registers?", options:["Storage locations in CPU","External memory","Permanent storage","Input devices"], answer:0, explanation:"Registers are small storage locations inside the CPU for quick access." },
  { q:"What is the ALU?", options:["Arithmetic Logic Unit","Performs calculations","Part of CPU","All of the above"], answer:3, explanation:"ALU performs arithmetic and logical operations in the CPU." },
  { q:"What is the Control Unit?", options:["CU","Coordinates operations","Part of CPU","All of the above"], answer:3, explanation:"Control Unit coordinates and controls all computer operations." },
  { q:"What is a port?", options:["Door","Connection point","Storage area","Processing unit"], answer:1, explanation:"A port is a connection point for external devices." },
  { q:"What is USB?", options:["Universal Serial Bus","Connection standard","Fast data transfer","All of the above"], answer:3, explanation:"USB is a standard for connecting peripherals with fast data transfer." },
  { q:"What is HDMI?", options:["Audio standard","Video standard","Network standard","Storage standard"], answer:1, explanation:"HDMI is a standard for transmitting high-definition video and audio." },
  { q:"What is BIOS?", options:["Basic Input Output System","Boot firmware","Initializes hardware","All of the above"], answer:3, explanation:"BIOS is firmware that initializes hardware during computer startup." },
  { q:"What is firmware?", options:["Hardware","Software stored in hardware","Operating system","Application"], answer:1, explanation:"Firmware is software permanently stored in hardware devices." },
  { q:"What is a chipset?", options:["CPU","Set of integrated circuits","Motherboard","Power supply"], answer:1, explanation:"Chipset manages data flow between CPU, memory, and peripherals." },
  { q:"What is overclocking?", options:["Running CPU faster","Running CPU slower","Upgrading memory","Adding storage"], answer:0, explanation:"Overclocking means running the CPU at higher than rated frequency." },
  { q:"What is cooling system?", options:["Heats computer","Cools computer components","Powers computer","Stores data"], answer:1, explanation:"Cooling system prevents overheating of computer components." },
  { q:"What is a fan?", options:["Heating device","Cooling device","Storage device","Input device"], answer:1, explanation:"Fans circulate air to cool computer components." },
  { q:"What is thermal paste?", options:["Cooling liquid","Conductive material","Insulating material","Storage material"], answer:1, explanation:"Thermal paste improves heat transfer between CPU and heatsink." }
];

const ICS4_QUESTIONS = [
  { q:"What is computer memory?", options:["Processing unit","Storage for data","Input device","Output device"], answer:1, explanation:"Memory stores data and instructions for computer processing." },
  { q:"What is the memory hierarchy?", options:["Memory types by speed","Memory types by size","Memory types by cost","All of the above"], answer:3, explanation:"Memory hierarchy organizes memory by speed, size, and cost." },
  { q:"What is the fastest memory?", options:["RAM","Hard drive","Registers","Cache"], answer:2, explanation:"Registers are the fastest memory located in the CPU." },
  { q:"What is cache memory?", options:["Slow memory","Fast memory between CPU and RAM","Permanent storage","Input buffer"], answer:1, explanation:"Cache memory is fast memory that bridges CPU and main memory." },
  { q:"What are cache levels?", options:["L1, L2, L3","L1, L2","L1 only","L4, L5"], answer:0, explanation:"Cache memory has three levels: L1, L2, and L3." },
  { q:"What is RAM?", options:["Read Access Memory","Random Access Memory","Rapid Action Memory","Remote Access Memory"], answer:1, explanation:"RAM stands for Random Access Memory." },
  { q:"What is DRAM?", options:["Dynamic RAM","Fast memory","Static memory","Cache memory"], answer:0, explanation:"DRAM is Dynamic Random Access Memory that needs refreshing." },
  { q:"What is SRAM?", options:["Static RAM","Slow memory","Dynamic memory","Hard drive"], answer:0, explanation:"SRAM is Static Random Access Memory that doesn't need refreshing." },
  { q:"What is virtual memory?", options:["Physical RAM","Extension of RAM using disk","Cache memory","Registers"], answer:1, explanation:"Virtual memory uses disk space to extend physical RAM." },
  { q:"What is paging?", options:["Memory allocation","Dividing memory into pages","Cache management","Register allocation"], answer:1, explanation:"Paging divides memory into fixed-size pages for management." },
  { q:"What is segmentation?", options:["Memory protection","Dividing memory into segments","Cache organization","Register grouping"], answer:1, explanation:"Segmentation divides memory into variable-size segments." },
  { q:"What is memory fragmentation?", options:["Memory loss","Wasted memory space","Memory corruption","Memory speed"], answer:1, explanation:"Fragmentation is wasted memory space due to inefficient allocation." },
  { q:"What is internal fragmentation?", options:["Wasted space in allocated blocks","Wasted space between blocks","Memory leaks","Cache misses"], answer:0, explanation:"Internal fragmentation is wasted space within allocated memory blocks." },
  { q:"What is external fragmentation?", options:["Wasted space within blocks","Wasted space between blocks","Memory overflow","Cache hits"], answer:1, explanation:"External fragmentation is wasted space between allocated memory blocks." },
  { q:"What is memory management?", options:["CPU management","Allocating and deallocating memory","File management","Network management"], answer:1, explanation:"Memory management handles allocation and deallocation of memory." },
  { q:"What is a memory leak?", options:["Memory loss","Unreleased memory","Memory corruption","Memory speed"], answer:1, explanation:"Memory leak occurs when program fails to release allocated memory." },
  { q:"What is garbage collection?", options:["Memory cleaning","Automatic memory management","Manual memory allocation","Memory compression"], answer:1, explanation:"Garbage collection automatically reclaims unused memory." },
  { q:"What is swap space?", options:["RAM","Disk space for virtual memory","Cache memory","Registers"], answer:1, explanation:"Swap space is disk space used for virtual memory paging." },
  { q:"What is thrashing?", options:["Memory corruption","Excessive paging","Memory leak","Cache miss"], answer:1, explanation:"Thrashing occurs when system spends more time paging than executing." },
  { q:"What is memory protection?", options:["Physical protection","Preventing unauthorized access","Memory encryption","Memory compression"], answer:1, explanation:"Memory protection prevents processes from accessing each other's memory." },
  { q:"What is a memory address?", options:["Memory location identifier","Memory size","Memory speed","Memory type"], answer:0, explanation:"Memory address is a unique identifier for a memory location." },
  { q:"What is word size?", options:["Memory capacity","Number of bits processed","Memory speed","Memory type"], answer:1, explanation:"Word size is the number of bits a CPU can process at once." },
  { q:"What is byte addressable memory?", options:["Memory accessed by bytes","Memory accessed by words","Memory accessed by bits","Memory accessed by pages"], answer:0, explanation:"Byte addressable memory can access individual bytes." },
  { q:"What is memory latency?", options:["Memory size","Time to access memory","Memory speed","Memory type"], answer:1, explanation:"Memory latency is the time delay for memory access." },
  { q:"What is memory bandwidth?", options:["Memory size","Rate of data transfer","Memory speed","Memory type"], answer:1, explanation:"Memory bandwidth is the rate at which data can be transferred." },
  { q:"What is DDR RAM?", options:["Double Data Rate","Dynamic Data RAM","Direct Data RAM","Dual Data RAM"], answer:0, explanation:"DDR stands for Double Data Rate RAM." },
  { q:"What is ECC memory?", options:["Error Correcting Code","Extra Cache Memory","Extended Capacity Memory","Enhanced Clock Memory"], answer:0, explanation:"ECC memory can detect and correct memory errors." },
  { q:"What is flash memory?", options:["RAM","Non-volatile memory","Cache memory","Registers"], answer:1, explanation:"Flash memory is non-volatile memory that retains data without power." },
  { q:"What is ROM?", options:["Random Only Memory","Read Only Memory","Rapid Only Memory","Remote Only Memory"], answer:1, explanation:"ROM stands for Read Only Memory." },
  { q:"What is EEPROM?", options:["Electrically Erasable Programmable ROM","Extra EEPROM","Enhanced EEPROM","Extended EEPROM"], answer:0, explanation:"EEPROM can be erased and reprogrammed electrically." }
];

const ICS5_QUESTIONS = [
  { q:"What is computer software?", options:["Hardware components","Programs and instructions","Physical devices","Computer cases"], answer:1, explanation:"Software consists of programs and instructions that control hardware." },
  { q:"What is system software?", options:["Word processors","Operating systems","Video games","Web browsers"], answer:1, explanation:"System software manages computer hardware and provides platform for applications." },
  { q:"What is application software?", options:["Operating systems","Device drivers","Word processors","BIOS"], answer:2, explanation:"Application software performs specific tasks for users." },
  { q:"What is an operating system?", options:["Application program","System software managing resources","Hardware device","Network protocol"], answer:1, explanation:"Operating system manages hardware resources and runs programs." },
  { q:"What is a programming language?", options:["Computer hardware","Set of rules for writing programs","Operating system","Network device"], answer:1, explanation:"Programming language provides rules for writing computer instructions." },
  { q:"What is a compiler?", options:["Translates code to machine language","Interprets code line-by-line","Edits programs","Debugs programs"], answer:0, explanation:"Compiler translates entire program to machine language before execution." },
  { q:"What is an interpreter?", options:["Translates entire program","Executes code line-by-line","Compiles programs","Links programs"], answer:1, explanation:"Interpreter translates and executes code one line at a time." },
  { q:"What is source code?", options:["Machine language","Human-readable program","Compiled program","Executed program"], answer:1, explanation:"Source code is program written in programming language." },
  { q:"What is object code?", options:["Source code","Machine language from compiler","Human-readable code","Program design"], answer:1, explanation:"Object code is machine language produced by compiler." },
  { q:"What is an algorithm?", options:["Programming language","Step-by-step problem solution","Computer hardware","Operating system"], answer:1, explanation:"Algorithm is a step-by-step procedure for solving problems." },
  { q:"What is pseudocode?", options:["Fake code","Informal program description","Machine language","Compiled code"], answer:1, explanation:"Pseudocode is informal description of program logic." },
  { q:"What is a flowchart?", options:["Program code","Visual program representation","Programming language","Compiler output"], answer:1, explanation:"Flowchart is a diagram showing program flow." },
  { q:"What is debugging?", options:["Writing programs","Finding and fixing errors","Compiling programs","Running programs"], answer:1, explanation:"Debugging is the process of finding and removing program errors." },
  { q:"What is a bug?", options:["Program feature","Error in program","Programming language","Compiler"], answer:1, explanation:"Bug is an error or flaw in a computer program." },
  { q:"What is software development life cycle?", options:["Hardware design","Phased software creation","Program execution","Error correction"], answer:1, explanation:"SDLC is the process of developing software through phases." },
  { q:"What is requirements analysis?", options:["Writing code","Understanding user needs","Testing software","Deploying software"], answer:1, explanation:"Requirements analysis determines what software should do." },
  { q:"What is software design?", options:["Writing code","Planning software structure","Testing software","User training"], answer:1, explanation:"Software design creates the software architecture." },
  { q:"What is implementation?", options:["Planning software","Writing program code","Testing software","Deploying software"], answer:1, explanation:"Implementation is writing and coding the software." },
  { q:"What is software testing?", options:["Writing code","Finding and fixing errors","Planning software","User training"], answer:1, explanation:"Testing verifies software works correctly." },
  { q:"What is maintenance?", options:["Initial development","Fixing and updating software","Testing software","Planning software"], answer:1, explanation:"Maintenance involves fixing bugs and adding features." },
  { q:"What is version control?", options:["Code compilation","Tracking code changes","Program execution","Error detection"], answer:1, explanation:"Version control tracks changes to source code." },
  { q:"What is Git?", options:["Programming language","Version control system","Compiler","Interpreter"], answer:1, explanation:"Git is a distributed version control system." },
  { q:"What is open source software?", options:["Free software","Source code available","Commercial software","Proprietary software"], answer:1, explanation:"Open source software has publicly available source code." },
  { q:"What is proprietary software?", options:["Free software","Source code secret","Open source","Public domain"], answer:1, explanation:"Proprietary software has restricted source code access." },
  { q:"What is software licensing?", options:["Code compilation","Legal permission to use software","Program execution","Error correction"], answer:1, explanation:"Software licensing grants legal rights to use software." },
  { q:"What is a software library?", options:["Book collection","Reusable code collection","Program database","Code repository"], answer:1, explanation:"Software library contains reusable code and functions." },
  { q:"What is an API?", options:["Application Programming Interface","Advanced Program Interface","Automated Program Interface","Application Program Integration"], answer:0, explanation:"API defines how software components interact." },
  { q:"What is modular programming?", options:["Single large program","Breaking into smaller modules","Complex programming","Quick programming"], answer:1, explanation:"Modular programming divides programs into smaller, manageable parts." },
  { q:"What is object-oriented programming?", options:["Procedure-based","Object-based programming","Hardware programming","System programming"], answer:1, explanation:"OOP organizes code around objects with data and methods." }
];

const ICS6_QUESTIONS = [
  { q:"What is an operating system?", options:["Application software","System software managing resources","Hardware device","Programming language"], answer:1, explanation:"Operating system manages computer hardware and software resources." },
  { q:"What are the main functions of OS?", options:["Play games","Process management, memory management, file system","Word processing","Internet browsing"], answer:1, explanation:"OS manages processes, memory, files, I/O, and provides security." },
  { q:"What is a process?", options:["Program in memory","Hardware device","File on disk","Network connection"], answer:0, explanation:"A process is a program that is currently executing in memory." },
  { q:"What is a thread?", options:["Heavy process","Lightweight process","File thread","Network thread"], answer:1, explanation:"A thread is a lightweight process that shares memory with other threads." },
  { q:"What is multitasking?", options:["Single task","Multiple tasks simultaneously","Fast processing","Memory management"], answer:1, explanation:"Multitasking allows multiple programs to run concurrently." },
  { q:"What is multiprocessing?", options:["Single processor","Multiple processors","Fast CPU","Large memory"], answer:1, explanation:"Multiprocessing uses multiple CPUs for parallel processing." },
  { q:"What is process scheduling?", options:["Memory allocation","Deciding process execution order","File management","I/O management"], answer:1, explanation:"Process scheduling determines which process runs when." },
  { q:"What is FCFS scheduling?", options:["First Come First Served","Fastest CPU First Served","First Class First Served","First Code First Served"], answer:0, explanation:"FCFS executes processes in order of arrival." },
  { q:"What is Round Robin scheduling?", options:["Circular execution","Priority-based","Shortest first","First come first"], answer:0, explanation:"Round Robin allocates time slices to processes in circular order." },
  { q:"What is memory management?", options:["CPU management","Allocating memory to processes","File storage","Network management"], answer:1, explanation:"Memory management allocates and deallocates memory to processes." },
  { q:"What is virtual memory?", options:["Physical RAM","Disk extension of RAM","Cache memory","Registers"], answer:1, explanation:"Virtual memory uses disk space to extend physical memory." },
  { q:"What is paging?", options:["Memory protection","Fixed-size memory division","Variable-size division","Cache management"], answer:1, explanation:"Paging divides memory into fixed-size pages." },
  { q:"What is segmentation?", options:["Fixed division","Variable-size memory division","Page management","Cache division"], answer:1, explanation:"Segmentation divides memory into variable-size segments." },
  { q:"What is a file system?", options:["File organization method","Memory system","Process system","Network system"], answer:0, explanation:"File system organizes and stores files on storage devices." },
  { q:"What is FAT?", options:["File Allocation Table","Fast Access Table","File Access Type","Full Access Table"], answer:0, explanation:"FAT is a file system that uses a table to track file locations." },
  { q:"What is NTFS?", options:["New Technology File System","Network File System","New Table File System","Next Technology File System"], answer:0, explanation:"NTFS is a modern file system with advanced features." },
  { q:"What is a device driver?", options:["Hardware device","Software controlling hardware","Operating system","Application program"], answer:1, explanation:"Device driver is software that controls hardware devices." },
  { q:"What is I/O management?", options:["Input/Output handling","Memory management","Process scheduling","File management"], answer:0, explanation:"I/O management handles input and output operations." },
  { q:"What is buffering?", options:["Memory storage","Temporary data storage","Permanent storage","Cache storage"], answer:1, explanation:"Buffering temporarily stores data during I/O operations." },
  { q:"What is spooling?", options:["Memory pooling","Queueing output for devices","Memory allocation","Process pooling"], answer:1, explanation:"Spooling queues output requests for slow devices like printers." },
  { q:"What is deadlock?", options:["System crash","Processes waiting forever","Memory full","File corrupted"], answer:1, explanation:"Deadlock occurs when processes wait for resources held by each other." },
  { q:"What are deadlock conditions?", options:["Mutual exclusion, hold and wait, no preemption, circular wait","Memory full, CPU busy, disk full, network down","File locked, process crashed, system error, user error","All of the above","None of the above"], answer:0, explanation:"Four conditions must be present for deadlock: mutual exclusion, hold and wait, no preemption, circular wait." },
  { q:"What is security in OS?", options:["Physical security","Protection from unauthorized access","Hardware protection","Network security"], answer:1, explanation:"OS security protects system from unauthorized access and threats." },
  { q:"What is user authentication?", options:["User identification","Verifying user identity","User authorization","User management"], answer:1, explanation:"Authentication verifies the identity of users." },
  { q:"What is access control?", options:["User login","Controlling resource access","Password management","User creation"], answer:1, explanation:"Access control determines what users can access." },
  { q:"What is a kernel?", options:["User interface","Core OS part","Application program","Device driver"], answer:1, explanation:"Kernel is the core part of OS that manages hardware." },
  { q:"What is a shell?", options:["Hardware shell","User interface for commands","OS core","Device driver"], answer:1, explanation:"Shell is a user interface for interacting with the OS." },
  { q:"What is GUI?", options:["Graphical User Interface","Command line","Text interface","Hardware interface"], answer:0, explanation:"GUI provides graphical interface for user interaction." },
  { q:"What is CLI?", options:["Graphical interface","Command Line Interface","Hardware interface","Network interface"], answer:1, explanation:"CLI allows users to interact with OS using text commands." },
  { q:"What is booting?", options:["System startup","Loading OS into memory","User login","Application start"], answer:1, explanation:"Booting is the process of loading the OS into memory." }
];

const ICS7_QUESTIONS = [
  { q:"What is programming?", options:["Hardware design","Writing computer instructions","System administration","Network setup"], answer:1, explanation:"Programming is writing instructions that computers can execute." },
  { q:"What is a programming language?", options:["Computer hardware","Rules for writing programs","Operating system","Database system"], answer:1, explanation:"Programming language provides syntax and semantics for writing programs." },
  { q:"What is a variable?", options:["Fixed value","Storage location for data","Program instruction","Hardware component"], answer:1, explanation:"Variable is a named storage location that can hold changing values." },
  { q:"What is a data type?", options:["Variable name","Data classification","Program structure","Function name"], answer:1, explanation:"Data type specifies what kind of data a variable can hold." },
  { q:"What is an integer?", options:["Decimal number","Whole number","Text string","Boolean value"], answer:1, explanation:"Integer is a data type for whole numbers without decimal points." },
  { q:"What is a string?", options:["Number","Sequence of characters","Boolean","Array"], answer:1, explanation:"String is a sequence of characters enclosed in quotes." },
  { q:"What is a boolean?", options:["Number","Text","True/false value","Array"], answer:2, explanation:"Boolean represents true or false values." },
  { q:"What is an array?", options:["Single value","Collection of values","Function","Loop"], answer:1, explanation:"Array is a collection of elements of the same data type." },
  { q:"What is a function?", options:["Variable","Reusable code block","Data type","Loop"], answer:1, explanation:"Function is a reusable block of code that performs a specific task." },
  { q:"What is a parameter?", options:["Function result","Value passed to function","Function name","Variable type"], answer:1, explanation:"Parameter is a value passed to a function when called." },
  { q:"What is a return value?", options:["Input to function","Output from function","Function name","Parameter"], answer:1, explanation:"Return value is the result that a function sends back." },
  { q:"What is sequential execution?", options:["Parallel processing","Statements executed in order","Random execution","Conditional execution"], answer:1, explanation:"Sequential execution means statements run one after another." },
  { q:"What is selection?", options:["Looping","Conditional execution","Sequential execution","Function call"], answer:1, explanation:"Selection executes different code based on conditions." },
  { q:"What is iteration?", options:["Conditional execution","Repeated execution","Sequential execution","Function call"], answer:1, explanation:"Iteration repeats a block of code multiple times." },
  { q:"What is an if statement?", options:["Loop","Conditional statement","Function","Variable"], answer:1, explanation:"If statement executes code based on a condition." },
  { q:"What is a loop?", options:["Conditional","Repeated execution structure","Single execution","Function"], answer:1, explanation:"Loop repeats execution of code block." },
  { q:"What is a for loop?", options:["Conditional loop","Count-controlled loop","Infinite loop","While loop"], answer:1, explanation:"For loop repeats for a specific number of times." },
  { q:"What is a while loop?", options:["Count-controlled","Condition-controlled loop","For loop","Infinite loop"], answer:1, explanation:"While loop repeats while a condition is true." },
  { q:"What is a syntax error?", options:["Logic error","Grammar error in code","Runtime error","Logic mistake"], answer:1, explanation:"Syntax error is a violation of programming language rules." },
  { q:"What is a logic error?", options:["Syntax error","Program runs but gives wrong result","Runtime crash","Compilation error"], answer:1, explanation:"Logic error means program runs but produces incorrect results." },
  { q:"What is a runtime error?", options:["Syntax error","Logic error","Error during execution","Compilation error"], answer:2, explanation:"Runtime error occurs while program is running." },
  { q:"What is debugging?", options:["Writing code","Finding and fixing errors","Compiling code","Running code"], answer:1, explanation:"Debugging is finding and removing errors from programs." },
  { q:"What is an algorithm?", options:["Programming language","Step-by-step solution","Computer hardware","Data type"], answer:1, explanation:"Algorithm is a step-by-step procedure for solving problems." },
  { q:"What is pseudocode?", options:["Real code","Informal algorithm description","Machine code","Compiled code"], answer:1, explanation:"Pseudocode is informal description of algorithm logic." },
  { q:"What is a flowchart?", options:["Code text","Visual algorithm representation","Programming language","Data structure"], answer:1, explanation:"Flowchart is a diagram showing algorithm flow." },
  { q:"What is modular programming?", options:["Single module","Breaking into smaller modules","Complex code","Quick code"], answer:1, explanation:"Modular programming divides programs into manageable parts." },
  { q:"What is code reuse?", options:["Writing new code","Using existing code","Deleting code","Modifying code"], answer:1, explanation:"Code reuse means using existing code in new programs." },
  { q:"What is documentation?", options:["Code writing","Comments and explanations","Code execution","Code compilation"], answer:1, explanation:"Documentation explains how code works." },
  { q:"What is indentation?", options:["Code coloring","Consistent spacing","Code commenting","Code execution"], answer:1, explanation:"Indentation makes code structure clear through spacing." },
  { q:"What is a comment?", options:["Code instruction","Explanation for humans","Variable name","Function name"], answer:1, explanation:"Comment is text ignored by computer but explains code to humans." }
];

const ICS8_QUESTIONS = [
  { q:"What is data representation?", options:["Data storage","How data is stored in computer","Data processing","Data transmission"], answer:1, explanation:"Data representation is how information is encoded in computer systems." },
  { q:"What is binary system?", options:["Decimal system","Base-2 number system","Hexadecimal","Octal"], answer:1, explanation:"Binary uses only two digits: 0 and 1." },
  { q:"What is a bit?", options:["Binary digit","Byte","Kilobyte","Megabyte"], answer:0, explanation:"Bit is the smallest unit of data, representing 0 or 1." },
  { q:"What is a byte?", options:["8 bits","4 bits","16 bits","32 bits"], answer:0, explanation:"A byte consists of 8 bits." },
  { q:"What is a kilobyte?", options:["1000 bytes","1024 bytes","100 bytes","10 bytes"], answer:1, explanation:"A kilobyte is 1024 bytes." },
  { q:"What is ASCII?", options:["Image format","Text encoding standard","Audio format","Video format"], answer:1, explanation:"ASCII encodes text characters using 7-bit codes." },
  { q:"How many characters can ASCII represent?", options:["128","256","512","1024"], answer:0, explanation:"ASCII uses 7 bits, representing 128 characters." },
  { q:"What is Unicode?", options:["ASCII extension","International character encoding","Image encoding","Audio encoding"], answer:1, explanation:"Unicode supports characters from all writing systems." },
  { q:"How are images stored?", options:["Text","Pixels with color values","Sound waves","Numbers only"], answer:1, explanation:"Images are stored as pixels, each with color information." },
  { q:"What is RGB?", options:["Red Green Blue color model","Image format","Text encoding","Audio encoding"], answer:0, explanation:"RGB represents colors using red, green, and blue components." },
  { q:"What is resolution?", options:["Image size","Pixels per inch","Color depth","File size"], answer:1, explanation:"Resolution is the number of pixels per unit of length." },
  { q:"What is color depth?", options:["Image size","Bits per pixel","Resolution","File format"], answer:1, explanation:"Color depth is the number of bits used to represent each pixel's color." },
  { q:"How is sound stored?", options:["Images","Analog-to-digital conversion","Text","Colors"], answer:1, explanation:"Sound is converted from analog waves to digital samples." },
  { q:"What is sampling rate?", options:["Sound volume","Samples per second","Sound quality","File size"], answer:1, explanation:"Sampling rate is the number of samples taken per second." },
  { q:"What is bit depth in audio?", options:["Sample rate","Bits per sample","File size","Duration"], answer:1, explanation:"Bit depth determines the dynamic range of audio." },
  { q:"What is data compression?", options:["Data expansion","Reducing data size","Data encryption","Data transmission"], answer:1, explanation:"Compression reduces the amount of data needed to represent information." },
  { q:"What is lossless compression?", options:["Lossy compression","No data loss","Data reduction with loss","Image compression"], answer:1, explanation:"Lossless compression allows perfect reconstruction of original data." },
  { q:"What is lossy compression?", options:["No data loss","Data reduction with loss","Text compression","Database compression"], answer:1, explanation:"Lossy compression reduces size but loses some data permanently." },
  { q:"What is JPEG?", options:["Text format","Lossy image compression","Lossless compression","Audio format"], answer:1, explanation:"JPEG is a lossy compression format for images." },
  { q:"What is MP3?", options:["Video format","Lossy audio compression","Text format","Image format"], answer:1, explanation:"MP3 is a lossy compression format for audio." },
  { q:"What is ZIP?", options:["Image format","Lossless compression","Video format","Audio format"], answer:1, explanation:"ZIP is a lossless compression format for files." },
  { q:"What is hexadecimal?", options:["Binary","Base-16 number system","Base-8","Base-10"], answer:1, explanation:"Hexadecimal uses 16 digits: 0-9 and A-F." },
  { q:"What is octal?", options:["Base-8","Base-16","Base-2","Base-10"], answer:0, explanation:"Octal uses 8 digits: 0-7." },
  { q:"What is binary addition?", options:["1+1=2","1+1=10","1+1=1 carry 1","1+1=0 carry 1"], answer:1, explanation:"In binary, 1 + 1 = 10 (2 in decimal)." },
  { q:"What is two's complement?", options:["Binary addition","Negative number representation","Multiplication","Division"], answer:1, explanation:"Two's complement represents negative numbers in binary." },
  { q:"What is floating point?", options:["Integer representation","Decimal number representation","Text representation","Image representation"], answer:1, explanation:"Floating point represents real numbers with decimal points." },
  { q:"What is parity bit?", options:["Error detection","Data compression","Encryption","Encoding"], answer:0, explanation:"Parity bit detects single-bit errors in data." },
  { q:"What is checksum?", options:["Error correction","Error detection value","Data compression","Encryption"], answer:1, explanation:"Checksum is a value used to detect data corruption." },
  { q:"What is CRC?", options:["Cyclic Redundancy Check","Error detection","Data compression","Encryption"], answer:0, explanation:"CRC detects accidental changes to data." },
  { q:"What is metadata?", options:["Main data","Data about data","Compressed data","Encrypted data"], answer:1, explanation:"Metadata is information that describes other data." }
];

const ICS9_QUESTIONS = [
  { q:"What is a computer network?", options:["Single computer","Connected computers sharing resources","Computer program","Storage device"], answer:1, explanation:"Network connects computers to share resources and communicate." },
  { q:"What is LAN?", options:["Large Area Network","Local Area Network","Long Area Network","Linked Area Network"], answer:1, explanation:"LAN connects computers in a limited area like home or office." },
  { q:"What is WAN?", options:["Wide Area Network","World Area Network","Web Area Network","Wireless Area Network"], answer:0, explanation:"WAN connects computers over large geographical areas." },
  { q:"What is MAN?", options:["Main Area Network","Metropolitan Area Network","Multiple Area Network","Mobile Area Network"], answer:1, explanation:"MAN covers a city or large campus area." },
  { q:"What is a network topology?", options:["Network speed","Physical layout","Network size","Network type"], answer:1, explanation:"Topology is the physical or logical layout of network devices." },
  { q:"What is star topology?", options:["Circular","Central hub with spokes","Bus line","Mesh connections"], answer:1, explanation:"Star topology has a central hub with connections to all devices." },
  { q:"What is bus topology?", options:["Star","Single cable connecting all","Ring","Mesh"], answer:1, explanation:"Bus topology uses a single cable that all devices connect to." },
  { q:"What is ring topology?", options:["Star","Bus","Circular connection","Mesh"], answer:2, explanation:"Ring topology connects devices in a circular fashion." },
  { q:"What is mesh topology?", options:["Star","Bus","Ring","Interconnected devices"], answer:3, explanation:"Mesh topology has multiple interconnections between devices." },
  { q:"What is a network protocol?", options:["Network device","Rules for communication","Network cable","Network speed"], answer:1, explanation:"Protocol defines rules for data transmission and reception." },
  { q:"What is TCP/IP?", options:["Network cable","Protocol suite","Network device","Network topology"], answer:1, explanation:"TCP/IP is a suite of protocols for internet communication." },
  { q:"What is IP address?", options:["Computer name","Numerical network identifier","Network speed","Protocol type"], answer:1, explanation:"IP address uniquely identifies a device on a network." },
  { q:"What is IPv4?", options:["32-bit addresses","128-bit addresses","64-bit addresses","16-bit addresses"], answer:0, explanation:"IPv4 uses 32-bit addresses." },
  { q:"What is IPv6?", options:["32-bit","64-bit","128-bit","256-bit"], answer:2, explanation:"IPv6 uses 128-bit addresses." },
  { q:"What is DNS?", options:["Domain Name System","Dynamic Network System","Data Network Service","Device Name System"], answer:0, explanation:"DNS translates domain names to IP addresses." },
  { q:"What is HTTP?", options:["HyperText Transfer Protocol","High Transfer Protocol","Hyper Transfer Protocol","Host Transfer Protocol"], answer:0, explanation:"HTTP is the protocol for transferring web pages." },
  { q:"What is HTTPS?", options:["Secure HTTP","High Security HTTP","Hyper Secure Transfer","Host Secure Transfer"], answer:0, explanation:"HTTPS is the secure version of HTTP using SSL/TLS." },
  { q:"What is a router?", options:["Network cable","Device forwarding data","Network protocol","Network topology"], answer:1, explanation:"Router forwards data packets between networks." },
  { q:"What is a switch?", options:["Network router","Device connecting devices in LAN","Network protocol","Network cable"], answer:1, explanation:"Switch connects devices within a local network." },
  { q:"What is a hub?", options:["Intelligent switch","Broadcasts data to all ports","Network router","Network protocol"], answer:1, explanation:"Hub broadcasts incoming data to all connected ports." },
  { q:"What is a modem?", options:["Network switch","Modulates digital to analog","Network router","Network cable"], answer:1, explanation:"Modem converts digital signals to analog for transmission." },
  { q:"What is Ethernet?", options:["Wireless standard","Wired network technology","Network protocol","Network device"], answer:1, explanation:"Ethernet is a wired networking technology for LANs." },
  { q:"What is Wi-Fi?", options:["Wired network","Wireless network standard","Network protocol","Network device"], answer:1, explanation:"Wi-Fi enables wireless network connections." },
  { q:"What is Bluetooth?", options:["Long-range wireless","Short-range wireless","Network protocol","Network cable"], answer:1, explanation:"Bluetooth is for short-range wireless communication." },
  { q:"What is bandwidth?", options:["Network size","Data transfer rate","Network devices","Network protocols"], answer:1, explanation:"Bandwidth is the maximum data transfer rate of a network." },
  { q:"What is latency?", options:["Data amount","Delay in data transmission","Network speed","Network size"], answer:1, explanation:"Latency is the delay before data transfer begins." },
  { q:"What is a firewall?", options:["Network cable","Security barrier","Network router","Network switch"], answer:1, explanation:"Firewall blocks unauthorized network access." },
  { q:"What is encryption?", options:["Data compression","Converting data to secret code","Data transmission","Data storage"], answer:1, explanation:"Encryption converts data to prevent unauthorized reading." },
  { q:"What is VPN?", options:["Virtual Private Network","Very Private Network","Virtual Public Network","Very Public Network"], answer:0, explanation:"VPN creates secure connections over public networks." },
  { q:"What is the internet?", options:["Single network","Global network of networks","Local network","Private network"], answer:1, explanation:"Internet is a worldwide network of interconnected networks." }
];

const ICS10_QUESTIONS = [
  { q:"What is computer security?", options:["Fast computers","Protection from threats","Large storage","Colorful displays"], answer:1, explanation:"Computer security protects systems from unauthorized access and damage." },
  { q:"What is a virus?", options:["Hardware fault","Malicious software","Network cable","Computer program"], answer:1, explanation:"Virus is malicious software that replicates and spreads." },
  { q:"What is malware?", options:["Good software","Malicious software","Operating system","Application"], answer:1, explanation:"Malware is software designed to harm or exploit systems." },
  { q:"What is phishing?", options:["Fishing","Tricking users for information","Network protocol","Security software"], answer:1, explanation:"Phishing deceives users into revealing sensitive information." },
  { q:"What is a firewall?", options:["Physical wall","Software blocking unauthorized access","Network cable","Computer case"], answer:1, explanation:"Firewall monitors and blocks unauthorized network traffic." },
  { q:"What is antivirus software?", options:["Word processor","Detects and removes malware","Operating system","Web browser"], answer:1, explanation:"Antivirus scans for and removes malicious software." },
  { q:"What is encryption?", options:["Data compression","Converting data to unreadable form","Data deletion","Data copying"], answer:1, explanation:"Encryption makes data unreadable without proper key." },
  { q:"What is a password?", options:["Computer name","Secret code for access","Network address","File name"], answer:1, explanation:"Password is a secret string used for authentication." },
  { q:"What is two-factor authentication?", options:["Two passwords","Password plus second verification","Two computers","Two networks"], answer:1, explanation:"2FA requires password plus another verification method." },
  { q:"What is social engineering?", options:["Engineering degree","Manipulating people for information","Computer programming","Network design"], answer:1, explanation:"Social engineering tricks people into divulging confidential information." },
  { q:"What is software piracy?", options:["Stealing hardware","Illegal software copying","Network hacking","Data encryption"], answer:1, explanation:"Software piracy is unauthorized copying of software." },
  { q:"What is plagiarism?", options:["Writing code","Presenting others' work as own","Creating software","Testing programs"], answer:1, explanation:"Plagiarism is using someone else's work without credit." },
  { q:"What is intellectual property?", options:["Physical property","Creations of mind","Computer hardware","Network equipment"], answer:1, explanation:"Intellectual property includes inventions, designs, and creative works." },
  { q:"What is copyright?", options:["Physical ownership","Legal protection for original works","Computer security","Network access"], answer:1, explanation:"Copyright protects original literary, artistic, and musical works." },
  { q:"What is a computer ethics?", options:["Computer skills","Moral principles in computing","Programming rules","Hardware design"], answer:1, explanation:"Computer ethics deals with moral issues in computing." },
  { q:"What is digital citizenship?", options:["Computer ownership","Responsible technology use","Network access","Software license"], answer:1, explanation:"Digital citizenship is responsible and appropriate technology use." },
  { q:"What is privacy?", options:["Public information","Right to control personal information","Computer speed","Network security"], answer:1, explanation:"Privacy is the right to control personal information collection and use." },
  { q:"What is data mining?", options:["Data deletion","Extracting patterns from data","Data compression","Data encryption"], answer:1, explanation:"Data mining discovers patterns and knowledge from large datasets." },
  { q:"What is surveillance?", options:["Data storage","Monitoring individuals or groups","Data transmission","Data compression"], answer:1, explanation:"Surveillance is the monitoring of behavior, activities, or information." },
  { q:"What is cyberbullying?", options:["Physical bullying","Harassment using digital platforms","Network problem","Computer error"], answer:1, explanation:"Cyberbullying is harassment using digital communication." },
  { q:"What is identity theft?", options:["Stealing identity","Using someone else's identity","Computer theft","Network theft"], answer:1, explanation:"Identity theft is stealing personal information to impersonate someone." },
  { q:"What is hacking?", options:["Legal access","Unauthorized system access","Network setup","Software installation"], answer:1, explanation:"Hacking is gaining unauthorized access to computer systems." },
  { q:"What is ethical hacking?", options:["Illegal hacking","Authorized security testing","Malware creation","Data theft"], answer:1, explanation:"Ethical hacking tests systems for vulnerabilities with permission." },
  { q:"What is a digital footprint?", options:["Computer size","Trace of online activity","Network speed","Storage capacity"], answer:1, explanation:"Digital footprint is the trail of data left by online activities." },
  { q:"What is netiquette?", options:["Network speed","Internet etiquette","Network protocol","Network device"], answer:1, explanation:"Netiquette is proper behavior and communication on the internet." },
  { q:"What is cybercrime?", options:["Computer crime","Illegal activities using computers","Network problem","Software error"], answer:1, explanation:"Cybercrime is criminal activities conducted using computers." },
  { q:"What is ransomware?", options:["Free software","Malware encrypting files for ransom","Antivirus","Firewall"], answer:1, explanation:"Ransomware encrypts files and demands payment for decryption." },
  { q:"What is a DDoS attack?", options:["Data attack","Overwhelming server with traffic","Data theft","Data corruption"], answer:1, explanation:"DDoS attack floods a server with traffic to make it unavailable." },
  { q:"What is data breach?", options:["Data backup","Unauthorized data access","Data compression","Data encryption"], answer:1, explanation:"Data breach is unauthorized access to confidential data." },
  { q:"What is cybersecurity?", options:["Computer security","Protecting systems from threats","Network speed","Software development"], answer:1, explanation:"Cybersecurity protects computer systems from digital attacks." }
];

const COMSYS_QUESTION_MAP = {
  38: ICS1_QUESTIONS,
  39: ICS2_QUESTIONS,
  40: ICS3_QUESTIONS,
  41: ICS4_QUESTIONS,
  42: ICS5_QUESTIONS,
  43: ICS6_QUESTIONS,
  44: ICS7_QUESTIONS,
  45: ICS8_QUESTIONS,
  46: ICS9_QUESTIONS,
  47: ICS10_QUESTIONS,
};

// Optional export for module-based usage
if (typeof module !== 'undefined') { module.exports = { ICS1_QUESTIONS, ICS2_QUESTIONS, ICS3_QUESTIONS, ICS4_QUESTIONS, ICS5_QUESTIONS, ICS6_QUESTIONS, ICS7_QUESTIONS, ICS8_QUESTIONS, ICS9_QUESTIONS, ICS10_QUESTIONS, COMSYS_QUESTION_MAP }; }
