// Data Communication questions extracted from app (1)(1).js

const DC_INTRO_QUESTIONS = [
  { q:"What is data communication?", options:["Transfer of data","Storage of data","Data encryption","Data sorting"], answer:0, explanation:"Data communication is the transfer of data between sender and receiver." },
  { q:"Which element is NOT part of a communication system?", options:["Sender","Receiver","Channel","Battery"], answer:3, explanation:"Battery is not part of the standard communication system model." },
  { q:"What is the communication channel?", options:["Sender device","Medium for signal travel","Receiving software","Encryption method"], answer:1, explanation:"The channel is the physical medium used to carry signals." },
  { q:"What is noise in data communication?", options:["Useful signal","Unwanted interference","Encryption key","Network protocol"], answer:1, explanation:"Noise is unwanted interference that corrupts transmitted data." },
  { q:"What does bandwidth measure?", options:["Voltage level","Signal strength","Data rate capacity","Number of devices"], answer:2, explanation:"Bandwidth measures the capacity of a channel to carry data." },
  { q:"Which is a digital signal?", options:["Continuous waveform","Discrete binary levels","Varying amplitude analog","None"], answer:1, explanation:"Digital signals use discrete binary levels such as 0 and 1." },
  { q:"Which mode allows two-way communication simultaneously?", options:["Simplex","Half-duplex","Full-duplex","Multiplex"], answer:2, explanation:"Full-duplex allows simultaneous two-way communication." },
  { q:"What is a protocol?", options:["Data storage standard","Rules for communication","A cable type","A network device"], answer:1, explanation:"A protocol defines rules and conventions for communication." },
  { q:"What is attenuation?", options:["Signal amplification","Signal weakening","Message encoding","Error correction"], answer:1, explanation:"Attenuation is the reduction in signal strength over distance." },
  { q:"Which is an example of a digital data type?", options:["Voice signal","Analog temperature","Binary file","Continuous waveform"], answer:2, explanation:"A binary file is digital data consisting of discrete values." },
  { q:"What is a transmitter?", options:["Receives data","Converts data to signal","Stores data","Encrypts data"], answer:1, explanation:"A transmitter converts data into signals for transmission." },
  { q:"What is a receiver?", options:["Creates data","Sends signals","Converts signals back to data","Measures bandwidth"], answer:2, explanation:"A receiver converts incoming signals back into usable data." },
  { q:"What does full-duplex mean?", options:["One-way only","Two-way one at a time","Two-way simultaneous","No transmission"], answer:2, explanation:"Full-duplex allows data flow in both directions at the same time." },
  { q:"What is the main purpose of analog-to-digital conversion?", options:["Store analog data","Send data as sound","Represent analog data digitally","Reduce noise"], answer:2, explanation:"Analog-to-digital conversion represents analog information in digital form." },
  { q:"How is a message defined in data communication?", options:["The transmitted information","The protocol used","The physical medium","The receiver hardware"], answer:0, explanation:"A message is the information transferred from sender to receiver." },
  { q:"What is the relationship between baud rate and bit rate?", options:["They are always equal","Baud rate counts symbols, bit rate counts bits","Bit rate is always higher","Baud rate is irrelevant"], answer:1, explanation:"Baud rate measures signal changes per second, while bit rate measures bits per second." },
  { q:"Which factor can reduce transmission quality?", options:["Bandwidth","Noise","Protocols","Encoding"], answer:1, explanation:"Noise interferes with the signal and reduces quality." },
  { q:"Which is a basic mode of communication?", options:["Multiplexing","Encryption","Simplex","Virtual circuit"], answer:2, explanation:"Simplex is a basic mode where data flows in only one direction." },
  { q:"What is data rate?", options:["Amount of data per second","Number of connected users","Encryption speed","Channel length"], answer:0, explanation:"Data rate is the amount of data transmitted per second." },
  { q:"Which term describes the process of arranging data for transmission?", options:["Encoding","Storage","Routing","Switching"], answer:0, explanation:"Encoding arranges data into a signal form suitable for transmission." },
  { q:"What does a protocol stack provide?", options:["One device only","Layered communication functions","Wireless connection","Encryption only"], answer:1, explanation:"A protocol stack provides layered communication functions for interoperability." },
  { q:"What is a simplex system best used for?", options:["Phone calls","Television broadcast","Internet chat","File transfer"], answer:1, explanation:"Simplex is suitable for one-way transmission such as television broadcast." },
  { q:"What is the main benefit of full-duplex?", options:["Lower bandwidth","Simultaneous communication","No noise","Simpler hardware"], answer:1, explanation:"Full-duplex provides simultaneous two-way communication." },
  { q:"What is a baseband channel?", options:["Channel using multiple frequencies","Channel using original signal frequency","Wireless channel","Encrypted channel"], answer:1, explanation:"Baseband uses the original frequency range of the signal." },
  { q:"What does the term 'medium' refer to in communication?", options:["Sender software","Physical path for signals","Encryption method","Protocol sequence"], answer:1, explanation:"The medium is the physical path used to carry signals." },
  { q:"What is the term for unwanted changes in signal amplitude?", options:["Encryption","Interference","Attenuation","Noise"], answer:3, explanation:"Noise causes unwanted changes in the signal." },
  { q:"Which communication mode is used by walkie-talkies?", options:["Simplex","Full-duplex","Half-duplex","Broadcast"], answer:2, explanation:"Walkie-talkies typically use half-duplex communication." },
  { q:"What does the term 'channel capacity' refer to?", options:["Number of users","Maximum data rate","Physical cable length","Protocol type"], answer:1, explanation:"Channel capacity is the maximum achievable data rate of a channel." },
  { q:"What is the effect of increasing bandwidth?", options:["Lower data rate","Higher data rate","More noise","Simpler encoding"], answer:1, explanation:"Increasing bandwidth enables a higher data rate." },
  { q:"Why are protocols important?", options:["They store data","They define communication rules","They generate signals","They measure bandwidth"], answer:1, explanation:"Protocols ensure consistent rules for communication between devices." }
];

const DC_NET_TYPES_QUESTIONS = [
  { q:"What does LAN stand for?", options:["Large Area Network","Local Area Network","Long Access Network","Link Access Network"], answer:1, explanation:"LAN stands for Local Area Network." },
  { q:"Which network type typically covers a city?", options:["PAN","LAN","MAN","WAN"], answer:2, explanation:"MAN stands for Metropolitan Area Network, covering a city." },
  { q:"What is a WAN?", options:["Wide Area Network","Wireless Access Network","Web Area Network","Workgroup Area Network"], answer:0, explanation:"A WAN covers a broad geographic area, often connecting multiple LANs." },
  { q:"What is a PAN used for?", options:["Cloud servers","Personal device connectivity","City-wide links","International links"], answer:1, explanation:"PAN stands for Personal Area Network, used for nearby device connectivity." },
  { q:"Which topology uses a single central cable?", options:["Star","Ring","Bus","Mesh"], answer:2, explanation:"Bus topology uses a single backbone cable shared by all devices." },
  { q:"Which topology connects all nodes to one central hub?", options:["Ring","Star","Mesh","Bus"], answer:1, explanation:"Star topology connects all nodes to a central hub or switch." },
  { q:"Which topology passes data around a closed loop?", options:["Star","Ring","Bus","Tree"], answer:1, explanation:"Ring topology passes data around a closed loop of nodes." },
  { q:"Which topology has direct links between every pair of nodes?", options:["Mesh","Bus","Ring","Star"], answer:0, explanation:"Mesh topology connects every node directly to every other node." },
  { q:"What is a hybrid topology?", options:["Single topology only","Combination of topologies","Wireless only","Incompatible networks"], answer:1, explanation:"Hybrid topology combines two or more different topologies." },
  { q:"Which topology is most fault tolerant?", options:["Bus","Ring","Star","Mesh"], answer:3, explanation:"Mesh topology is highly fault tolerant because multiple paths exist." },
  { q:"Which topology can suffer from collisions on a shared medium?", options:["Mesh","Star","Bus","Tree"], answer:2, explanation:"Bus topology can suffer from collisions because all nodes share the same medium." },
  { q:"Which network type is the smallest in geographic scope?", options:["WAN","MAN","LAN","PAN"], answer:3, explanation:"PAN is the smallest network type, typically within a person’s range." },
  { q:"Which topology is simple to install but hard to expand?", options:["Bus","Mesh","Star","Ring"], answer:0, explanation:"Bus topology is simple to install but difficult to expand and troubleshoot." },
  { q:"Which topology isolates each device on its own cable?", options:["Star","Bus","Ring","Mesh"], answer:0, explanation:"Star topology isolates devices by connecting each to a central switch or hub." },
  { q:"Which type of network is best for connecting offices in different countries?", options:["PAN","LAN","MAN","WAN"], answer:3, explanation:"WAN is suitable for connecting offices over large distances." },
  { q:"What is a key advantage of star topology?", options:["No central point","Easy fault identification","Low cable usage","No switch required"], answer:1, explanation:"Star topology makes it easier to identify faults because each device has an independent connection." },
  { q:"Which topology often uses a token passing access method?", options:["Bus","Ring","Star","Mesh"], answer:1, explanation:"Ring topology often uses token passing to regulate access to the medium." },
  { q:"What is a CAN?", options:["Campus Area Network","Channel Area Network","Computer Access Network","Center Area Network"], answer:0, explanation:"CAN stands for Campus Area Network." },
  { q:"Which topology is easiest to reconfigure?", options:["Bus","Ring","Star","Mesh"], answer:2, explanation:"Star topology is easier to reconfigure because devices connect individually to a central node." },
  { q:"Which network type is typically used inside a building?", options:["WAN","MAN","LAN","PAN"], answer:2, explanation:"LAN is typically used to connect computers within a building." },
  { q:"What is a major disadvantage of mesh topology?", options:["Low reliability","Complex cabling","Poor performance","Lack of redundancy"], answer:1, explanation:"Mesh topology requires complex and expensive cabling." },
  { q:"Which topology can continue working if one link fails in a full mesh?", options:["Bus","Ring","Star","Mesh"], answer:3, explanation:"A full mesh can continue operating even if one link fails." },
  { q:"What is a star-bus hybrid?", options:["Star and mesh combined","Bus and star combined","Ring and star combined","Mesh and ring combined"], answer:1, explanation:"A star-bus hybrid combines the star and bus topologies." },
  { q:"Which topology uses a central device to manage traffic?", options:["Bus","Star","Ring","Mesh"], answer:1, explanation:"Star topology uses a central hub or switch to manage traffic." },
  { q:"Which network type supports high-speed local access?", options:["WAN","MAN","LAN","PAN"], answer:2, explanation:"LAN supports high-speed local access within a limited area." },
  { q:"What is the common disadvantage of bus topology?", options:["High cost","One cable failure can stop the network","Complex setup","Requires many routers"], answer:1, explanation:"In bus topology, one cable failure can bring down the entire network." },
  { q:"Which topology is used by Ethernet networks with a switch?", options:["Bus","Ring","Star","Mesh"], answer:2, explanation:"Ethernet networks commonly use a star topology with a switch." },
  { q:"What is a main benefit of mesh topology?", options:["Cheap cabling","High redundancy","No central device","Fewer connections"], answer:1, explanation:"Mesh topology offers high redundancy and fault tolerance." },
  { q:"Which topology is best when expansion is likely?", options:["Bus","Star","Ring","Mesh"], answer:1, explanation:"Star topology supports easier expansion as devices are added." },
  { q:"What is the main feature of a hybrid topology?", options:["Single topology only","Combined topologies","Wireless only","Protocol-based"], answer:1, explanation:"A hybrid topology combines multiple topology types to suit specific needs." }
];

const DC_TRANSMISSION_QUESTIONS = [
  { q:"Which is a guided transmission medium?", options:["Radio waves","Optical fiber","Satellite link","Infrared"], answer:1, explanation:"Optical fiber is a guided transmission medium enclosed in a cable." },
  { q:"Which is an unguided medium?", options:["Twisted pair","Coaxial cable","Optical fiber","Radio waves"], answer:3, explanation:"Radio waves are an unguided medium transmitted through the air." },
  { q:"What is twisted pair cable commonly used for?", options:["Telephone lines","Satellite links","Fiber optics","Wi-Fi"], answer:0, explanation:"Twisted pair cable is commonly used for telephone and Ethernet connections." },
  { q:"What distinguishes optical fiber?", options:["Copper conductor","Glass core","No attenuation","Wireless"], answer:1, explanation:"Optical fiber uses a glass or plastic core to carry light signals." },
  { q:"What is a property of coaxial cable?", options:["Very low bandwidth","Shielded conductor","No insulation","Wireless"], answer:1, explanation:"Coaxial cable has a shielded conductor to reduce interference." },
  { q:"Which medium is used for long-distance, high-speed communication?", options:["Twisted pair","Optical fiber","Infrared","Ethernet"], answer:1, explanation:"Optical fiber is ideal for long-distance, high-speed communication." },
  { q:"What causes signal loss in guided media?", options:["Noise only","Attenuation","Protocol mismatch","Server load"], answer:1, explanation:"Attenuation causes signal loss over distance in guided media." },
  { q:"Which is a wireless transmission medium?", options:["Twisted pair","Optical fiber","Radio waves","Coaxial"], answer:2, explanation:"Radio waves are a wireless transmission medium." },
  { q:"What is the advantage of optical fiber over copper?", options:["Lower bandwidth","Higher attenuation","Higher bandwidth","Less secure"], answer:2, explanation:"Optical fiber offers higher bandwidth than copper media." },
  { q:"What is a characteristic of microwaves?", options:["Require line of sight","Use fiber optics","Low frequency","Use twisted pair"], answer:0, explanation:"Microwaves usually require line-of-sight transmission." },
  { q:"Which medium is least affected by electromagnetic interference?", options:["Twisted pair","Coaxial cable","Optical fiber","Radio waves"], answer:2, explanation:"Optical fiber is immune to electromagnetic interference." },
  { q:"What is a disadvantage of wireless media?", options:["High cable cost","Mobility only","Interference","No security"], answer:2, explanation:"Wireless media are prone to interference from other signals." },
  { q:"Which medium uses a copper conductor with insulation?", options:["Optical fiber","Twisted pair","Air","Infrared"], answer:1, explanation:"Twisted pair uses copper conductors wrapped in insulation." },
  { q:"Which medium provides the highest bandwidth?", options:["Twisted pair","Coaxial","Optical fiber","Infrared"], answer:2, explanation:"Optical fiber provides the highest bandwidth among common media." },
  { q:"What is the role of a repeater?", options:["Change protocols","Regenerate signals","Encrypt messages","Route packets"], answer:1, explanation:"A repeater regenerates weakened signals in a transmission medium." },
  { q:"Which unguided medium is commonly used for home Wi-Fi?", options:["Coaxial","Infrared","Radio waves","Twisted pair"], answer:2, explanation:"Home Wi-Fi uses radio waves as the transmission medium." },
  { q:"What is the main use of coaxial cable?", options:["Fiber backbone","TV and broadband","Cellular backhaul","Bluetooth"], answer:1, explanation:"Coaxial cable is widely used for television and broadband internet." },
  { q:"Which medium is best for secure, high-speed backbone links?", options:["Twisted pair","Coaxial","Optical fiber","Radio"], answer:2, explanation:"Optical fiber is best for secure, high-speed backbone links." },
  { q:"What is a disadvantage of copper cables?", options:["High bandwidth","Impervious to noise","Bulk and interference","Lightweight"], answer:2, explanation:"Copper cables are bulky and susceptible to interference." },
  { q:"Which medium uses light pulses to carry data?", options:["Coaxial","Twisted pair","Optical fiber","Satellite"], answer:2, explanation:"Optical fiber transmits data using light pulses." },
  { q:"Which medium is associated with satellite communication?", options:["Optical fiber","Radio waves","Twisted pair","Coaxial"], answer:1, explanation:"Satellite communication uses radio waves through space." },
  { q:"What is a key property of guided media?", options:["No physical path","Uses a physical conductor","Uses free space","Requires wireless devices"], answer:1, explanation:"Guided media use a physical conductor or waveguide to carry signals." },
  { q:"Which medium is typically least expensive for small networks?", options:["Optical fiber","Coaxial","Twisted pair","Wireless"], answer:2, explanation:"Twisted pair cable is typically the least expensive medium for small networks." },
  { q:"What is a major factor limiting copper cable distance?", options:["Bandwidth only","Attenuation and noise","Line coding","IP address"], answer:1, explanation:"Attenuation and noise limit the distance of copper cable transmissions." },
  { q:"What is the main purpose of shielding in coaxial cable?", options:["Reduce cost","Reduce interference","Increase speed","Create wireless signals"], answer:1, explanation:"Shielding in coaxial cable reduces electromagnetic interference." },
  { q:"Which medium is used in fiber-to-the-home connections?", options:["Twisted pair","Coaxial","Optical fiber","Radio waves"], answer:2, explanation:"Fiber-to-the-home uses optical fiber to bring high-speed service to residences." },
  { q:"Which unguided medium is used by infrared remote controls?", options:["Radio","Microwave","Infrared","Laser"], answer:2, explanation:"Infrared remote controls use infrared light as the transmission medium." },
  { q:"What defines the choice between guided and unguided media?", options:["Protocol only","Distance and environment","Encryption method","OS support"], answer:1, explanation:"Distance and environment help decide whether guided or unguided media are appropriate." },
  { q:"Which medium is best for underground communication?", options:["Optical fiber","Radio waves","Twisted pair","Coaxial"], answer:0, explanation:"Optical fiber is commonly used for underground communication due to durability and capacity." },
  { q:"What is an example of an unguided medium used for mobile phones?", options:["Twisted pair","Optical fiber","Radio waves","Coaxial"], answer:2, explanation:"Mobile phones use radio waves for wireless transmission." }
];

const DC_SIGNALS_QUESTIONS = [
  { q:"What is the difference between analog and digital signals?", options:["Analog is discrete, digital is continuous","Analog is continuous, digital is discrete","Both are continuous","Both are discrete"], answer:1, explanation:"Analog signals vary continuously, while digital signals use discrete levels." },
  { q:"What is amplitude modulation used for?", options:["Encode digital data","Vary signal amplitude","Change signal phase","Add error correction"], answer:1, explanation:"Amplitude modulation changes the amplitude of a carrier signal." },
  { q:"What is frequency modulation?", options:["Change signal amplitude","Change signal frequency","Change signal phase","Maintain constant frequency"], answer:1, explanation:"Frequency modulation alters the carrier frequency to encode information." },
  { q:"What is phase modulation?", options:["Change amplitude","Change frequency","Change phase","Change waveform"], answer:2, explanation:"Phase modulation encodes data by altering the phase of the carrier." },
  { q:"What does PCM stand for?", options:["Pulse Code Modulation","Phase Code Multiplexing","Packet Count Metric","Protocol Control Mode"], answer:0, explanation:"PCM stands for Pulse Code Modulation." },
  { q:"What is Manchester encoding?", options:["Uses no transitions","Represents bits by voltage levels only","Uses transitions for clocking","Encodes audio signals"], answer:2, explanation:"Manchester encoding uses transitions to represent bits and aid synchronization." },
  { q:"Which line code has a transition at the middle of each bit?", options:["NRZ-L","Manchester","RZ","4B/5B"], answer:1, explanation:"Manchester encoding has a transition at the middle of each bit period." },
  { q:"What does NRZ-L encoding use to represent bits?", options:["Voltage transitions","High and low voltage levels","Frequency shifts","Pulse shapes"], answer:1, explanation:"NRZ-L uses high and low voltage levels to represent binary bits." },
  { q:"What is a symbol rate?", options:["Bits per second","Signals per second","Packets per second","Frames per second"], answer:1, explanation:"Symbol rate measures signal changes or symbols transmitted per second." },
  { q:"What does Nyquist theorem define?", options:["Minimum bandwidth for zero error","Maximum data rate for noiseless channel","Number of layers in OSI","Packet size limit"], answer:1, explanation:"Nyquist theorem defines maximum data rate for a noiseless channel." },
  { q:"What is Shannon capacity?", options:["Data rate for noisy channel","Size of packet","Minimum signal amplitude","Network delay"], answer:0, explanation:"Shannon capacity calculates the theoretical maximum data rate over a noisy channel." },
  { q:"What is line coding used for?", options:["Routing packets","Modem connection","Mapping bits to signal waveforms","Encrypting data"], answer:2, explanation:"Line coding maps bits into electrical or optical signal waveforms." },
  { q:"What is baseband transmission?", options:["Using multiple channels","Sending original signal frequency","Wireless only","Encrypted only"], answer:1, explanation:"Baseband transmission sends a signal in its original frequency range." },
  { q:"Which encoding method uses both amplitude and phase changes?", options:["ASK","FSK","PSK","QAM"], answer:3, explanation:"QAM uses both amplitude and phase changes to encode data." },
  { q:"What is quantization in digital signal processing?", options:["Sampling rate selection","Mapping continuous values to discrete levels","Changing carrier frequency","Adding redundancy"], answer:1, explanation:"Quantization maps continuous amplitude values to discrete digital levels." },
  { q:"Which signal type is used in voice communication over telephone lines?", options:["Digital only","Analog only","Either analog or digital","Neither"], answer:2, explanation:"Voice communication can use analog or digital signals depending on the system." },
  { q:"What is the purpose of encoding data into signals?", options:["Reduce bandwidth","Make data human-readable","Prepare data for transmission","Store more data"], answer:2, explanation:"Encoding prepares data for transmission over a communication medium." },
  { q:"Which modulation type uses changes in amplitude?", options:["PSK","FSK","ASK","PCM"], answer:2, explanation:"ASK stands for Amplitude Shift Keying, which changes amplitude to encode data." },
  { q:"Which modulation uses changes in frequency?", options:["ASK","PSK","FSK","PCM"], answer:2, explanation:"FSK uses different frequencies to represent data values." },
  { q:"What does PSK stand for?", options:["Phase Shift Keying","Pulse Shift Keying","Parity Shift Keying","Packet Shift Keying"], answer:0, explanation:"PSK stands for Phase Shift Keying." },
  { q:"Which process converts analog signals to digital pulses?", options:["Modulation","Multiplexing","Sampling and quantization","Routing"], answer:2, explanation:"Sampling and quantization convert analog signals into digital pulses." },
  { q:"What is the goal of encoding in communication?", options:["Encrypt data","Represent information with signals","Reduce device cost","Increase packet size"], answer:1, explanation:"The goal of encoding is to represent information with suitable signals." },
  { q:"Why is synchronization important in encoding?", options:["To reduce noise","To align sender and receiver timing","To encrypt bits","To change protocols"], answer:1, explanation:"Synchronization ensures sender and receiver share timing for accurate decoding." },
  { q:"What is a benefit of digital encoding?", options:["No error detection","Better noise immunity","Reduced bandwidth always","No processing required"], answer:1, explanation:"Digital encoding generally offers better noise immunity and error detection." },
  { q:"Which technique is used for digital-to-analog conversion?", options:["ASK","MASM","ASCII","UUID"], answer:0, explanation:"ASK is an example of a digital-to-analog conversion technique." },
  { q:"What is the effect of sampling at less than twice the signal frequency?", options:["Perfect reconstruction","Aliasing","Lower noise","Higher bandwidth"], answer:1, explanation:"Sampling below the Nyquist rate can cause aliasing." },
  { q:"What is a pulse code?", options:["Analog waveform","Digital representation of samples","Error correction code","Routing protocol"], answer:1, explanation:"A pulse code is a digital representation of sampled analog values." },
  { q:"What does line coding affect?", options:["User interface","Signal waveform and bandwidth","Operating system","Cable length"], answer:1, explanation:"Line coding affects the signal waveform and its bandwidth requirements." },
  { q:"Which encoding method provides clock recovery and data representation?", options:["NRZ-L","Manchester","Pulse gating","Line switching"], answer:1, explanation:"Manchester encoding provides both clock recovery and data representation." }
];

const DC_OSI_QUESTIONS = [
  { q:"How many layers are in the OSI model?", options:["4","5","6","7"], answer:3, explanation:"The OSI model has seven layers." },
  { q:"Which OSI layer is responsible for physical signal transmission?", options:["Physical","Data Link","Network","Transport"], answer:0, explanation:"The Physical layer handles raw signal transmission." },
  { q:"Which layer handles frame formatting and MAC addressing?", options:["Physical","Data Link","Network","Session"], answer:1, explanation:"The Data Link layer handles framing and MAC addresses." },
  { q:"Which layer is responsible for routing packets?", options:["Transport","Network","Session","Application"], answer:1, explanation:"The Network layer is responsible for routing packets." },
  { q:"Which layer provides end-to-end delivery and flow control?", options:["Physical","Data Link","Transport","Presentation"], answer:2, explanation:"The Transport layer manages end-to-end delivery and flow control." },
  { q:"Which layer manages sessions and dialogues between applications?", options:["Session","Presentation","Application","Network"], answer:0, explanation:"The Session layer manages sessions and dialogues." },
  { q:"Which layer handles data encryption and formatting?", options:["Physical","Data Link","Presentation","Application"], answer:2, explanation:"The Presentation layer handles encryption and data formatting." },
  { q:"Which layer is closest to the end user?", options:["Physical","Data Link","Transport","Application"], answer:3, explanation:"The Application layer is closest to the end user." },
  { q:"What is encapsulation?", options:["Breaking packets into bits","Wrapping data with headers","Encrypting data","Switching topologies"], answer:1, explanation:"Encapsulation wraps higher-layer data with lower-layer headers." },
  { q:"What is the PDU name at the Transport layer?", options:["Bits","Frames","Packets","Segments"], answer:3, explanation:"The Transport layer works with segments." },
  { q:"What is the PDU name at the Network layer?", options:["Bits","Frames","Packets","Segments"], answer:2, explanation:"Network layer units are called packets." },
  { q:"Which layer provides logical addressing?", options:["Physical","Data Link","Network","Transport"], answer:2, explanation:"The Network layer provides logical addresses such as IP addresses." },
  { q:"Which layer can provide error detection on frames?", options:["Physical","Data Link","Network","Application"], answer:1, explanation:"The Data Link layer can detect and sometimes correct errors in frames." },
  { q:"Which layer uses port numbers?", options:["Transport","Network","Data Link","Presentation"], answer:0, explanation:"The Transport layer uses port numbers for process-to-process communication." },
  { q:"Which OSI layer is responsible for data compression?", options:["Physical","Data Link","Presentation","Application"], answer:2, explanation:"The Presentation layer is responsible for data compression." },
  { q:"Which layer is responsible for session checkpointing and recovery?", options:["Session","Presentation","Network","Application"], answer:0, explanation:"The Session layer can manage checkpoints and recovery for sessions." },
  { q:"What layer provides application services directly to end users?", options:["Physical","Presentation","Application","Transport"], answer:2, explanation:"The Application layer provides services directly to end-user applications." },
  { q:"Which layer formats data into frames?", options:["Physical","Data Link","Network","Transport"], answer:1, explanation:"The Data Link layer formats data into frames." },
  { q:"Which layer establishes, manages, and terminates connections?", options:["Session","Transport","Network","Application"], answer:0, explanation:"The Session layer manages connections and dialogues." },
  { q:"Which layer converts data into a network-compatible form?", options:["Physical","Presentation","Transport","Data Link"], answer:1, explanation:"The Presentation layer converts data into a common format for the network." },
  { q:"Which layer ensures reliable delivery of data segments?", options:["Physical","Data Link","Network","Transport"], answer:3, explanation:"The Transport layer ensures reliable delivery of segments." },
  { q:"What is the OSI layer that uses MAC addresses?", options:["Physical","Data Link","Network","Session"], answer:1, explanation:"MAC addresses are used at the Data Link layer." },
  { q:"What is the OSI layer between the Transport and Presentation layers?", options:["Network","Session","Data Link","Physical"], answer:1, explanation:"The Session layer sits between Transport and Presentation." },
  { q:"Which layer is responsible for path determination and logical addressing?", options:["Physical","Data Link","Network","Transport"], answer:2, explanation:"The Network layer determines paths and logical addresses." },
  { q:"What does the Application layer do?", options:["Transmits bits","Routes packets","Provides network services to applications","Encodes signals"], answer:2, explanation:"The Application layer provides services to user applications." },
  { q:"Which OSI layer is responsible for converting bits into electrical signals?", options:["Physical","Data Link","Network","Transport"], answer:0, explanation:"The Physical layer converts bits into electrical or optical signals." },
  { q:"Which layer is responsible for connectionless communication?", options:["Physical","Session","Network","Application"], answer:2, explanation:"The Network layer can support connectionless communication via datagrams." },
  { q:"What is the correct order of OSI layers from lowest to highest?", options:["Physical, Data Link, Network, Transport, Session, Presentation, Application","Application, Presentation, Session, Transport, Network, Data Link, Physical","Data Link, Physical, Network, Transport, Session, Presentation, Application","Physical, Network, Data Link, Transport, Session, Presentation, Application"], answer:0, explanation:"The correct OSI order from lowest to highest begins with Physical and ends with Application." },
  { q:"Which layer is responsible for encryption and decryption?", options:["Session","Presentation","Transport","Network"], answer:1, explanation:"The Presentation layer handles encryption and decryption." }
];

const DC_TCPIP_QUESTIONS = [
  { q:"How many layers are in the TCP/IP model?", options:["3","4","5","7"], answer:1, explanation:"The TCP/IP model commonly has four layers." },
  { q:"Which TCP/IP layer contains TCP and UDP?", options:["Application","Transport","Internet","Network Interface"], answer:1, explanation:"The Transport layer contains TCP and UDP." },
  { q:"Which layer includes IP addressing?", options:["Application","Transport","Internet","Physical"], answer:2, explanation:"The Internet layer includes IP addressing and routing." },
  { q:"What does the Network Interface layer do?", options:["Manages applications","Handles packet routing","Interacts with hardware","Encrypts data"], answer:2, explanation:"The Network Interface layer interacts with the physical hardware." },
  { q:"Which protocol resolves IP addresses to MAC addresses?", options:["ICMP","ARP","DNS","HTTP"], answer:1, explanation:"ARP resolves IP addresses to MAC addresses." },
  { q:"Which protocol provides echo request and reply?", options:["ARP","ICMP","TCP","UDP"], answer:1, explanation:"ICMP provides echo request and reply messages." },
  { q:"Which protocol is connectionless and low overhead?", options:["TCP","UDP","ARP","HTTP"], answer:1, explanation:"UDP is connectionless and has lower overhead than TCP." },
  { q:"Which protocol is used for web browsing?", options:["SMTP","FTP","HTTP","ARP"], answer:2, explanation:"HTTP is used for web browsing." },
  { q:"Which protocol translates domain names to IP addresses?", options:["DNS","DHCP","SMTP","FTP"], answer:0, explanation:"DNS translates domain names to IP addresses." },
  { q:"What is the purpose of DHCP?", options:["Encrypt data","Assign IP addresses automatically","Route packets","Control access"], answer:1, explanation:"DHCP assigns IP addresses automatically to hosts." },
  { q:"What does the TCP three-way handshake begin with?", options:["SYN, SYN-ACK, ACK","ACK, SYN, FIN","FIN, ACK, SYN","SYN-ACK, ACK, SYN"], answer:0, explanation:"The three-way handshake starts with SYN, then SYN-ACK, then ACK." },
  { q:"Which field identifies application processes?", options:["MAC address","IP address","Port number","Subnet mask"], answer:2, explanation:"Port numbers identify application processes on hosts." },
  { q:"What is a datagram?", options:["A fixed-size cell","A packet without a dedicated path","A physical signal","A network cable"], answer:1, explanation:"A datagram is a packet sent without a dedicated path." },
  { q:"Which protocol provides reliable ordered delivery?", options:["UDP","TCP","IP","ARP"], answer:1, explanation:"TCP provides reliable and ordered delivery." },
  { q:"What does 'best effort' delivery mean?", options:["Guaranteed delivery","No delivery attempt","Delivery without guarantees","Encrypted transmission"], answer:2, explanation:"Best effort means delivery is attempted without guarantees of reliability." },
  { q:"Which layer is responsible for application protocols like SMTP?", options:["Application","Transport","Internet","Network Interface"], answer:0, explanation:"The Application layer handles protocols like SMTP." },
  { q:"What is the role of ARP?", options:["Map domain names","Map IP addresses to MAC addresses","Encrypt traffic","Route packets"], answer:1, explanation:"ARP maps IP addresses to MAC addresses." },
  { q:"Which protocol is delay-sensitive and connectionless?", options:["TCP","UDP","ICMP","FTP"], answer:1, explanation:"UDP is connectionless and suitable for delay-sensitive traffic." },
  { q:"What does IP stand for?", options:["Internet Protocol","Internal Process","Interface Packet","Intranet Port"], answer:0, explanation:"IP stands for Internet Protocol." },
  { q:"Which protocol sends error and control messages?", options:["TCP","UDP","ICMP","DNS"], answer:2, explanation:"ICMP is used for network error reporting and control messages." },
  { q:"What is the maximum IP version widely used today?", options:["IPv2","IPv4","IPv5","IPv8"], answer:1, explanation:"IPv4 is the widely used version today, with IPv6 emerging." },
  { q:"What feature allows multiple devices to share one IP address?", options:["MAC filtering","ARP","NAT","VPN"], answer:2, explanation:"NAT allows multiple devices to share a single public IP address." },
  { q:"Which transport protocol uses a checksum for error detection?", options:["TCP","UDP","ARP","HTTP"], answer:1, explanation:"UDP uses a checksum for error detection." },
  { q:"What is the main advantage of TCP over UDP?", options:["Less overhead","Connectionless delivery","Reliability","No headers"], answer:2, explanation:"TCP provides reliable delivery while UDP does not." },
  { q:"Which protocol provides dynamic host configuration?", options:["DNS","DHCP","FTP","HTTP"], answer:1, explanation:"DHCP dynamically assigns network configuration to hosts." },
  { q:"What does the Internet layer handle?", options:["Application services","Data encryption","Routing and addressing","Physical wiring"], answer:2, explanation:"The Internet layer handles routing and addressing." },
  { q:"What is a common transport protocol used by streaming services?", options:["TCP","UDP","ARP","ICMP"], answer:1, explanation:"Streaming services often use UDP for low-latency delivery." },
  { q:"Which layer includes the reply from a ping command?", options:["Transport","Application","Internet","Network Interface"], answer:2, explanation:"Ping uses ICMP at the Internet layer." },
  { q:"What is the purpose of a header in a TCP/IP packet?", options:["Encrypt payload","Carry control information","Add noise","Measure bandwidth"], answer:1, explanation:"Headers carry control and routing information." },
  { q:"What is a socket in TCP/IP?", options:["A physical port","A combination of IP address and port","A cable connector","A router setting"], answer:1, explanation:"A socket combines an IP address and port number for process communication." }
];

const DC_SWITCHING_QUESTIONS = [
  { q:"What is circuit switching?", options:["Packets routed independently","Dedicated path setup","Wireless transmission","No connection needed"], answer:1, explanation:"Circuit switching establishes a dedicated path for the duration of a connection." },
  { q:"What is packet switching?", options:["Dedicated circuit path","Data broken into packets","No addressing","Only analog"], answer:1, explanation:"Packet switching divides data into packets that travel independently." },
  { q:"What is message switching?", options:["Send packets without storage","Store and forward whole messages","Use a dedicated circuit","Encapsulate at layer 2"], answer:1, explanation:"Message switching stores and forwards entire messages from node to node." },
  { q:"Which switching technique is used by the Internet?", options:["Circuit switching","Packet switching","Message switching","None"], answer:1, explanation:"The Internet uses packet switching." },
  { q:"What is a virtual circuit?", options:["Physical circuit only","Logical path with packet switching","Wireless channel","Time-division multiplexer"], answer:1, explanation:"A virtual circuit is a logical connection established over packet switching." },
  { q:"What is a datagram network?", options:["Uses dedicated channels","Sends packets independently","Requires call setup","Symmetric bandwidth"], answer:1, explanation:"In a datagram network, packets are sent independently without pre-established path." },
  { q:"What is store-and-forward?", options:["Broadcast immediately","Store data then forward it","Encrypt data","Use analog only"], answer:1, explanation:"Store-and-forward involves storing incoming data before forwarding it." },
  { q:"Which switching is best for low-delay voice calls?", options:["Packet switching","Circuit switching","Message switching","No switching"], answer:1, explanation:"Circuit switching is preferred for low-delay continuous voice calls." },
  { q:"What is statistical multiplexing?", options:["Dedicated channel per user","Dynamic sharing of bandwidth","Physical layer coding","Error detection"], answer:1, explanation:"Statistical multiplexing dynamically shares bandwidth among users based on demand." },
  { q:"Which technique requires a setup phase before data transfer?", options:["Packet switching","Circuit switching","Broadcasting","Routing"], answer:1, explanation:"Circuit switching requires a setup phase before data transfer." },
  { q:"What is an advantage of packet switching?", options:["Guaranteed bandwidth","Efficient use of network resources","No addressing required","No delay"], answer:1, explanation:"Packet switching uses network resources more efficiently for bursty traffic." },
  { q:"What is a switching node?", options:["End user device","Network device that forwards data","Media converter","Encryption device"], answer:1, explanation:"A switching node forwards data packets between network segments." },
  { q:"What does a switch do in a packet-switched network?", options:["Encapsulate frames","Forward packets based on addresses","Generate electricity","Create protocols"], answer:1, explanation:"A switch forwards packets based on addressing and switching decisions." },
  { q:"Which switching method stores a complete message before forwarding?", options:["Circuit switching","Packet switching","Message switching","Virtual switching"], answer:2, explanation:"Message switching stores the complete message before forwarding." },
  { q:"What is a key characteristic of packet switching?", options:["Fixed path for all packets","Packets may take different routes","No addressing","One packet per connection"], answer:1, explanation:"In packet switching, packets may take different routes to the destination." },
  { q:"Which technique is less efficient for bursty data?", options:["Packet switching","Circuit switching","Message switching","Datagram switching"], answer:1, explanation:"Circuit switching is less efficient for bursty data because it reserves a dedicated path." },
  { q:"What is the main advantage of virtual circuits?", options:["No packet headers","Fixed route with packet switching","No addressing","No delay"], answer:1, explanation:"Virtual circuits provide a fixed logical route within a packet-switched network." },
  { q:"Which switching method is best for email and batch data?", options:["Circuit switching","Packet switching","Message switching","Broadcast"], answer:2, explanation:"Message switching suits email and batch data because it stores messages before forwarding." },
  { q:"What is the primary goal of switching technology?", options:["Encrypt data","Connect end devices through paths","Create user accounts","Measure bandwidth"], answer:1, explanation:"Switching connects end devices by selecting paths for data transfer." },
  { q:"What is the meaning of 'switching delay'?", options:["Encryption time","Processing time inside switch","Cable length delay","Protocol overhead"], answer:1, explanation:"Switching delay is the processing time inside a switch or node." },
  { q:"Which technique is used in cell relay networks like ATM?", options:["Circuit switching","Packet switching","Cell switching","Message switching"], answer:2, explanation:"ATM uses cell switching with fixed-size cells." },
  { q:"What is a benefit of packet switching for internet traffic?", options:["Less overhead than circuit switching","Guaranteed bandwidth","Improved efficiency for bursts","No need for protocols"], answer:2, explanation:"Packet switching is efficient for bursty internet traffic." },
  { q:"What determines the path of packets in a network?", options:["Physical cables only","Switching algorithm and routing table","User choice","Application settings"], answer:1, explanation:"Packet paths are determined by switching algorithms and routing tables." },
  { q:"What is the purpose of a call setup phase in circuit switching?", options:["Encrypt data","Reserve resources and establish a path","Transmit data continuously","Broadcast a message"], answer:1, explanation:"The setup phase reserves resources and establishes a dedicated path." },
  { q:"What is the distinction between connection oriented and connectionless switching?", options:["Connection oriented uses no path","Connectionless uses a dedicated path","Connection oriented establishes a path before data transfer","Both are identical"], answer:2, explanation:"Connection oriented switching establishes a path before data transfer." },
  { q:"What is an example of packet switching in practice?", options:["Traditional telephone call","Email delivery","Circuit-switched video call","Dedicated leased line"], answer:1, explanation:"Email delivery commonly uses packet switching." },
  { q:"Which switching type can be used for real-time voice traffic with low latency?", options:["Message switching","Packet switching","Circuit switching","All of the above"], answer:2, explanation:"Circuit switching can provide low latency for real-time voice traffic." },
  { q:"What is a hybrid switching network?", options:["Combines circuit and packet switching","Uses wireless and wired media","Is always connectionless","Encrypts data"], answer:0, explanation:"A hybrid switching network may combine circuit and packet switching techniques." }
];

const DC_ERROR_QUESTIONS = [
  { q:"What is a parity bit used for?", options:["Encrypt data","Detect single-bit errors","Route packets","Measure bandwidth"], answer:1, explanation:"Parity bits detect single-bit errors in a data block." },
  { q:"Which parity scheme makes the total number of 1s even?", options:["Odd parity","Even parity","CRC parity","Checksum parity"], answer:1, explanation:"Even parity ensures the total number of 1s is even." },
  { q:"Which parity scheme makes the total number of 1s odd?", options:["Even parity","Odd parity","CRC parity","Checksum parity"], answer:1, explanation:"Odd parity ensures an odd number of 1 bits." },
  { q:"What does CRC stand for?", options:["Cyclic Redundancy Check","Connection Retry Count","Control Relay Code","Critical Rate Count"], answer:0, explanation:"CRC stands for Cyclic Redundancy Check." },
  { q:"What is the purpose of ARQ?", options:["Encrypt packets","Request retransmission on error","Address messages","Schedule routing"], answer:1, explanation:"ARQ requests retransmission when errors are detected." },
  { q:"What is Stop-and-Wait ARQ?", options:["Send all packets at once","Send one packet then wait for acknowledgement","Send packets without acknowledgement","A type of encryption"], answer:1, explanation:"Stop-and-Wait ARQ sends one packet and waits for acknowledgement before sending the next." },
  { q:"What is Go-Back-N ARQ?", options:["Send one packet at a time","Retransmit missing packet only","Retransmit a sequence starting from the missing packet","No acknowledgements"], answer:2, explanation:"Go-Back-N retransmits all packets starting from a missing or erroneous packet." },
  { q:"What is Selective Repeat ARQ?", options:["Retransmit only erroneous packets","Ignore errors","Send all packets twice","Use no acknowledgements"], answer:0, explanation:"Selective Repeat ARQ retransmits only packets that contain errors." },
  { q:"What is the main difference between detection and correction?", options:["Detection fixes errors","Correction ignores errors","Detection finds errors, correction fixes them","Both are identical"], answer:2, explanation:"Detection identifies errors, while correction repairs them." },
  { q:"What does a checksum detect?", options:["All errors always","Some transmission errors","Signal strength","Packet loss"], answer:1, explanation:"A checksum detects many transmission errors but not all." },
  { q:"What is Hamming distance used for?", options:["Encrypt data","Measure difference between codewords","Route packets","Calculate bandwidth"], answer:1, explanation:"Hamming distance measures the number of bit differences between codewords." },
  { q:"What does forward error correction do?", options:["Request retransmission","Add redundancy to correct errors","Change the signal medium","Reduce packet size"], answer:1, explanation:"Forward error correction adds redundancy so the receiver can correct errors without retransmission." },
  { q:"Which method uses a polynomial to compute a remainder?", options:["Parity","Checksum","CRC","ARQ"], answer:2, explanation:"CRC uses polynomial division to compute a remainder for error detection." },
  { q:"What is a burst error?", options:["Single-bit error","Multiple adjacent bit errors","Error only in headers","No error"], answer:1, explanation:"A burst error affects multiple adjacent bits." },
  { q:"Which control message indicates successful receipt?", options:["NACK","ACK","SYN","FIN"], answer:1, explanation:"ACK indicates successful receipt of data." },
  { q:"Which message indicates a packet was not received correctly?", options:["ACK","NACK","SYN","RST"], answer:1, explanation:"NACK indicates negative acknowledgement when a packet is corrupt or missing." },
  { q:"Which code can correct single-bit errors and detect double-bit errors?", options:["Parity","CRC","Hamming","Checksum"], answer:2, explanation:"Hamming codes can correct single-bit errors and detect double-bit errors." },
  { q:"What is retransmission used for?", options:["Encrypt packets","Recover from errors","Route data","Compress payload"], answer:1, explanation:"Retransmission recovers lost or corrupted packets." },
  { q:"In error control, what is redundancy used for?", options:["Speeding transmission","Detecting or correcting errors","Routing decisions","User authentication"], answer:1, explanation:"Redundancy provides extra bits to detect or correct errors." },
  { q:"Which technique detects errors using a fixed-size parity block?", options:["CRC","Hamming","Checksum","Parity"], answer:3, explanation:"Parity detection uses a fixed-size block parity bit." },
  { q:"What does ARQ rely on to maintain reliability?", options:["Encryption","Acknowledgements and retransmissions","Switching techniques","Compression"], answer:1, explanation:"ARQ relies on Acknowledgements and retransmissions for reliability." },
  { q:"Which method is faster but less reliable than ARQ?", options:["FEC","CRC","Parity","TCP"], answer:0, explanation:"FEC can be faster because it corrects errors without retransmission, but it adds overhead." },
  { q:"What is a frame check sequence?", options:["Network address","Error-detection field","Transport header","Signal strength"], answer:1, explanation:"A frame check sequence is an error-detection field added to a frame." },
  { q:"What is the purpose of interleaving?", options:["Encrypt data","Spread errors across blocks to aid correction","Increase bandwidth","Route packets"], answer:1, explanation:"Interleaving spreads error bursts across blocks to improve correction." },
  { q:"What does bit error rate measure?", options:["Bits per second","Errors per bit transmitted","Packet size","Signal power"], answer:1, explanation:"Bit error rate measures the frequency of erroneous bits in transmission." },
  { q:"Which error control method is commonly used in TCP?", options:["FEC","Parity","CRC","ARQ"], answer:3, explanation:"TCP uses ARQ mechanisms for reliable delivery." },
  { q:"What is the main advantage of CRC over simple parity?", options:["Less overhead","Better error detection","No error detection","Faster transmission"], answer:1, explanation:"CRC offers much stronger error detection than simple parity." },
  { q:"What is the role of a negative acknowledgement?", options:["Confirm receipt","Request retransmission","Terminate connection","Start encryption"], answer:1, explanation:"A NACK requests retransmission when an error is detected." },
  { q:"Which technique can correct errors without retransmission?", options:["ARQ","FEC","Parity","Packet switching"], answer:1, explanation:"FEC corrects errors at the receiver without needing retransmission." },
  { q:"What causes the need for error control?", options:["Perfect channels","Noise and interference","Programming bugs","User errors"], answer:1, explanation:"Noise and interference in channels cause transmission errors that require error control." }
];

const DC_NETWORK_DEVICES_QUESTIONS = [
  { q:"Which device forwards packets between networks?", options:["Hub","Switch","Router","Repeater"], answer:2, explanation:"A router forwards packets between different networks." },
  { q:"Which device forwards frames within a LAN using MAC addresses?", options:["Router","Switch","Bridge","Modem"], answer:1, explanation:"A switch forwards frames within a LAN using MAC addresses." },
  { q:"What does a hub do?", options:["Routes packets","Broadcasts incoming signals to all ports","Encrypts data","Connects fiber links"], answer:1, explanation:"A hub broadcasts signals to all connected ports." },
  { q:"What is the function of a bridge?", options:["Regenerate signals","Filter traffic between LAN segments","Convert analog to digital","Assign IP addresses"], answer:1, explanation:"A bridge filters traffic between LAN segments based on MAC addresses." },
  { q:"What does a repeater do?", options:["Connects networks","Amplifies and forwards signals","Encrypts data","Routes packets"], answer:1, explanation:"A repeater regenerates and forwards signals to extend distance." },
  { q:"What does a modem do?", options:["Route packets","Modulate and demodulate signals","Switch frames","Store data"], answer:1, explanation:"A modem modulates digital signals for transmission over analog media and demodulates incoming signals." },
  { q:"Which device acts as a gateway?", options:["Routes between different protocols","Broadcasts frames","Applies parity","Changes topology"], answer:0, explanation:"A gateway translates and routes between different network protocols." },
  { q:"What is an access point?", options:["A wired switch","A wireless network device","An internet protocol","A firewall"], answer:1, explanation:"An access point provides wireless connectivity for devices." },
  { q:"What is the purpose of a firewall?", options:["Amplify signals","Control and filter network traffic","Store packets","Translate addresses"], answer:1, explanation:"A firewall controls and filters network traffic for security." },
  { q:"What does a NIC do?", options:["Route packets","Provide a physical network interface to a host","Display data","Store addresses"], answer:1, explanation:"A NIC provides a physical interface for a host to connect to the network." },
  { q:"How does a switch differ from a hub?", options:["Switch broadcasts all frames","Switch filters frames to correct ports","Switch uses wireless only","Switch is slower"], answer:1, explanation:"A switch forwards frames only to the correct port instead of broadcasting to all ports." },
  { q:"Which device can separate collision domains?", options:["Hub","Switch","Repeater","None"], answer:1, explanation:"A switch separates collision domains for each port." },
  { q:"Which device functions at the network layer and makes routing decisions?", options:["Switch","Router","Bridge","Hub"], answer:1, explanation:"A router operates at the network layer and makes routing decisions." },
  { q:"Which device is used to extend the reach of a network segment?", options:["Repeater","Router","Firewall","Switch"], answer:0, explanation:"A repeater extends the reach of a network segment by regenerating signals." },
  { q:"What type of device is a wireless access point?", options:["Router","Hub","Gateway","Network device for wireless clients"], answer:3, explanation:"A wireless access point connects wireless clients to a wired network." },
  { q:"Which device can translate between Ethernet and serial links?", options:["Bridge","Router","Media converter","Switch"], answer:2, explanation:"A media converter translates between different physical media types." },
  { q:"What does a load balancer do?", options:["Forward all traffic to one server","Distribute network traffic across servers","Encrypt data","Switch frames"], answer:1, explanation:"A load balancer distributes traffic across multiple servers." },
  { q:"Which device helps segment a network into separate broadcast domains?", options:["Hub","Switch","Router","Repeater"], answer:2, explanation:"A router segments networks into separate broadcast domains." },
  { q:"What is a smart switch?", options:["An unmanaged hub","A switch with limited management features","A wireless router","A repeater"], answer:1, explanation:"A smart switch offers some management capabilities beyond an unmanaged switch." },
  { q:"Which device operates at the data link layer?", options:["Hub","Switch","Router","Application"], answer:1, explanation:"A switch operates at the data link layer." },
  { q:"What does a gateway often provide?", options:["Simple switching","Protocol translation between networks","Power regulation","Reliable transport"], answer:1, explanation:"Gateways often translate between different network protocols." },
  { q:"Which device would connect a home network to an ISP?", options:["Switch","Hub","Modem","Brid ge"], answer:2, explanation:"A modem connects a home network to an ISP by converting signals." },
  { q:"What is a common function of a router in a network?", options:["Broadcast frames","Filter packets based on IP addresses","Encrypt data","Store files"], answer:1, explanation:"A router filters packets and forwards them based on IP addresses." },
  { q:"Which device is used to join two LAN segments and reduce traffic?", options:["Hub","Bridge","Modem","Repeater"], answer:1, explanation:"A bridge joins LAN segments and helps reduce unnecessary traffic." },
  { q:"Which network device increases signal strength over distance?", options:["Switch","Repeater","Router","Firewall"], answer:1, explanation:"A repeater increases signal strength to extend network distance." },
  { q:"Which device is primarily responsible for packet switching?", options:["Hub","Router","Bridge","Access point"], answer:1, explanation:"A router is primarily responsible for packet switching between networks." },
  { q:"What is the role of a network hub?", options:["Filter traffic","Broadcast incoming packets to all ports","Translate protocols","Encrypt traffic"], answer:1, explanation:"A hub broadcasts incoming packets to all connected ports." },
  { q:"Which device helps implement network security by filtering traffic?", options:["Switch","Firewall","Repeater","Hub"], answer:1, explanation:"A firewall filters network traffic to enforce security." },
  { q:"Which device can connect multiple wired devices in a LAN?", options:["Router","Switch","Gateway","Bridge"], answer:1, explanation:"A switch connects multiple wired devices in a LAN." },
  { q:"Which device is best for connecting different network segments with unique IP ranges?", options:["Hub","Switch","Router","Repeater"], answer:2, explanation:"A router connects different network segments with unique IP ranges." }
];

const DC_SECURITY_QUESTIONS = [
  { q:"What does confidentiality protect?", options:["Network speed","Data from unauthorized access","Quality of service","Cable length"], answer:1, explanation:"Confidentiality protects data from unauthorized access." },
  { q:"What does integrity ensure?", options:["Data is encrypted","Data is not altered","Data is delivered fast","Data is broadcast"], answer:1, explanation:"Integrity ensures that data is not altered during transmission." },
  { q:"What does availability mean in security?", options:["Data is hidden","Data is accessible when needed","Data is copied","Data is slow"], answer:1, explanation:"Availability means authorized users can access data when needed." },
  { q:"Which device filters traffic based on security rules?", options:["Repeater","Firewall","Switch","Hub"], answer:1, explanation:"A firewall filters traffic to enforce security rules." },
  { q:"What is encryption used for?", options:["Reduce noise","Protect data confidentiality","Increase bandwidth","Route packets"], answer:1, explanation:"Encryption protects data confidentiality during transmission." },
  { q:"What is authentication?", options:["Verifying user identity","Sending data","Routing packets","Storing logs"], answer:0, explanation:"Authentication verifies the identity of a user or device." },
  { q:"What is authorization?", options:["Granting access rights","Encrypting data","Routing traffic","Measuring speed"], answer:0, explanation:"Authorization grants permissions to access resources." },
  { q:"What does a VPN provide?", options:["Open network access","Secure remote access","Faster routing","Wireless communication"], answer:1, explanation:"A VPN provides secure remote access over a public network." },
  { q:"What is an IDS used for?", options:["Intrusion detection","Internet distribution","IP addressing","Encryption"], answer:0, explanation:"An IDS detects suspicious or malicious activity on a network." },
  { q:"What is an IPS used for?", options:["Intrusion prevention","Internet service","IP routing","Packet switching"], answer:0, explanation:"An IPS can prevent intrusions by blocking malicious traffic." },
  { q:"Which protocol secures web traffic?", options:["HTTP","FTP","HTTPS","SMTP"], answer:2, explanation:"HTTPS secures web traffic using TLS/SSL." },
  { q:"What is MAC filtering?", options:["Filtering by IP address","Filtering by physical address","Encrypting data","Routing packets"], answer:1, explanation:"MAC filtering allows or blocks devices based on their physical MAC address." },
  { q:"Which policy restricts password use?", options:["Encryption policy","Password policy","Routing policy","Media access policy"], answer:1, explanation:"Password policy restricts password complexity and change frequency." },
  { q:"What type of malware can replicate itself?", options:["Firewall","Virus","Router","Router"], answer:1, explanation:"A virus is malware that can replicate itself." },
  { q:"What is phishing?", options:["Configuring routers","A social engineering attack","Encrypting files","Broadcasting packets"], answer:1, explanation:"Phishing is a social engineering attack that attempts to steal information." },
  { q:"What is a DoS attack?", options:["Allowing service","Disrupting service","Encrypting service","Routing service"], answer:1, explanation:"A Denial of Service attack disrupts normal service availability." },
  { q:"What is a common wireless security protocol?", options:["WEP","WPA2","TCP","IPv4"], answer:1, explanation:"WPA2 is a common wireless security protocol." },
  { q:"What is multi-factor authentication?", options:["Single password only","Multiple authentication factors","Protocol layering","Bandwidth control"], answer:1, explanation:"Multi-factor authentication uses more than one method to verify identity." },
  { q:"What is a digital certificate used for?", options:["Routing packets","Verifying identity and keys","Measuring speed","Switching frames"], answer:1, explanation:"A digital certificate verifies identity and encryption keys." },
  { q:"What does SSL/TLS protect?", options:["Physical wires","Application data in transit","MAC addresses","IP routing"], answer:1, explanation:"SSL/TLS protects application data in transit." },
  { q:"What is a zero-trust model?", options:["Trust all devices","Trust nothing by default","Use one firewall","Ignore authentication"], answer:1, explanation:"Zero trust means nothing is trusted by default and access is verified continuously." },
  { q:"What is network segmentation used for?", options:["Combine networks","Divide networks for security","Increase broadcast domains","Reduce IP addresses"], answer:1, explanation:"Network segmentation divides networks to improve security and performance." },
  { q:"What is the purpose of an access control list?", options:["Encrypt data","Define which traffic is allowed or denied","Route packets","Store logs"], answer:1, explanation:"ACLs define which traffic is allowed or denied on network devices." },
  { q:"Which protocol provides secure email transfer?", options:["SMTP","IMAP","SMTPS","FTP"], answer:2, explanation:"SMTPS provides secure email transfer using encryption." },
  { q:"What is two-factor authentication?", options:["Two passwords","Password and another factor","Two routers","Two network cables"], answer:1, explanation:"Two-factor authentication uses a password plus another verification factor." },
  { q:"What is a man-in-the-middle attack?", options:["Direct delivery","Intercepting and altering communication","Secure transmission","Fast routing"], answer:1, explanation:"A man-in-the-middle attack intercepts and possibly alters communication between parties." },
  { q:"Which type of encryption uses the same key for encryption and decryption?", options:["Asymmetric","Symmetric","Hashing","Public key"], answer:1, explanation:"Symmetric encryption uses the same key for both encryption and decryption." },
  { q:"What is the purpose of VPN tunneling?", options:["Broadcast data","Create a secure logical connection","Increase packet size","Switch topologies"], answer:1, explanation:"VPN tunneling creates a secure logical connection over an insecure network." },
  { q:"Which wireless security protocol is stronger than WEP?", options:["WAP","WPA2","FTP","SMTP"], answer:1, explanation:"WPA2 is stronger than the older WEP protocol." },
  { q:"What does the term 'security policy' refer to?", options:["Cable layout","Rules and procedures for protecting networks","Protocol stack","Network topology"], answer:1, explanation:"A security policy defines rules and procedures for protecting network assets." },
  { q:"Which device inspects and filters packets at the network edge?", options:["Switch","Firewall","Repeater","Modem"], answer:1, explanation:"A firewall inspects and filters packets at the network edge." }
];

const DC_WIRELESS_QUESTIONS = [
  { q:"What does WLAN stand for?", options:["Wide Local Area Network","Wireless Local Area Network","Wireless Long Area Network","Wide LAN Access Network"], answer:1, explanation:"WLAN stands for Wireless Local Area Network." },
  { q:"What is a cellular network?", options:["Fixed wired network","Network divided into cells","Single wireless link","Optical fiber network"], answer:1, explanation:"A cellular network is divided into cells served by base stations." },
  { q:"What is Bluetooth mainly used for?", options:["Long-range communication","Short-range device connectivity","Internet backbone","Satellite links"], answer:1, explanation:"Bluetooth is used for short-range wireless device connectivity." },
  { q:"What does NFC stand for?", options:["Network Frequency Control","Near Field Communication","New Fiber Connection","Network File Carrier"], answer:1, explanation:"NFC stands for Near Field Communication." },
  { q:"Which standard is commonly used for Wi-Fi?", options:["802.3","802.11","802.15","802.16"], answer:1, explanation:"802.11 is the IEEE standard for Wi-Fi." },
  { q:"Which generation introduced 5G?", options:["2G","3G","4G","5G"], answer:3, explanation:"5G is the fifth generation of cellular mobile communication." },
  { q:"What is handoff in mobile communication?", options:["Changing frequency bands","Switching a call from one cell to another","Encrypting data","Routing packets"], answer:1, explanation:"Handoff switches an active call or data session to a new cell." },
  { q:"What is roaming?", options:["Using a phone outside its home network","Changing Wi-Fi settings","Encrypting mobile data","Switching protocols"], answer:0, explanation:"Roaming allows a mobile device to use another network when outside its home coverage." },
  { q:"What is frequency reuse?", options:["Using same frequency in different cells","Using one frequency for all cells","Avoiding radio frequencies","Encrypting wireless signals"], answer:0, explanation:"Frequency reuse allows the same frequency to be used in nonadjacent cells." },
  { q:"What is GSM?", options:["Global System for Mobile communications","General Service Model","Graphical Service Module","Gigabit Switching Method"], answer:0, explanation:"GSM stands for Global System for Mobile communications." },
  { q:"What is CDMA?", options:["Code Division Multiple Access","Carrier Data Multiplexing Access","Cellular Data Management Architecture","Control Domain Method"], answer:0, explanation:"CDMA is Code Division Multiple Access." },
  { q:"What is LTE?", options:["Long-Term Evolution","Low Transmission Equipment","Local Telephony Extension","Link Time Encryption"], answer:0, explanation:"LTE stands for Long-Term Evolution." },
  { q:"What is a hotspot?", options:["A thermal node","A wireless access point for public use","A router feature","A secure tunnel"], answer:1, explanation:"A hotspot is a public wireless access point." },
  { q:"What is a common challenge in wireless channels?", options:["No interference","Fading and multipath","Unlimited bandwidth","No encryption needed"], answer:1, explanation:"Wireless channels often experience fading and multipath interference." },
  { q:"What is mobile IP used for?", options:["Encrypt packets","Support device mobility across networks","Route only local traffic","Manage Wi-Fi passwords"], answer:1, explanation:"Mobile IP supports device mobility across different networks." },
  { q:"Which wireless standard is used for personal area networks?", options:["802.11","802.15","802.3","802.16"], answer:1, explanation:"IEEE 802.15 is used for personal area network standards like Bluetooth." },
  { q:"What is a common security protocol for Wi-Fi?", options:["HTTP","WPA2","FTP","SMTP"], answer:1, explanation:"WPA2 is a common wireless security protocol." },
  { q:"What does '5G' promise over 4G?", options:["Lower speed","Higher latency","Higher speed and lower latency","Less coverage"], answer:2, explanation:"5G promises higher speed and lower latency than 4G." },
  { q:"What is the role of an access point in wireless networking?", options:["Route IP packets","Provide wireless clients access to a wired network","Store data","Encrypt traffic"], answer:1, explanation:"An access point connects wireless clients to the wired portion of the network." },
  { q:"What is a mobile station?", options:["A network switch","A mobile device used by a subscriber","A wireless access point","A base station"], answer:1, explanation:"A mobile station is the subscriber’s mobile device." },
  { q:"Which technology is used for very short range contactless communication?", options:["Wi-Fi","Bluetooth","NFC","Satellite"], answer:2, explanation:"NFC is used for very short-range contactless communication." },
  { q:"What is a base station in cellular systems?", options:["Mobile phone","Cell tower equipment","Router software","Encryption device"], answer:1, explanation:"A base station provides wireless coverage for a cellular cell." },
  { q:"Which generation introduced high-speed mobile internet suitable for video streaming?", options:["2G","3G","4G","5G"], answer:2, explanation:"4G introduced high-speed mobile internet suitable for video streaming." },
  { q:"What is a key benefit of mesh Wi-Fi networks?", options:["Single point of failure","Simpler cabling","Improved coverage and redundancy","Lower bandwidth"], answer:2, explanation:"Mesh Wi-Fi improves coverage and redundancy." },
  { q:"Which wireless technology is often used for smart home devices?", options:["LTE","Bluetooth","Zigbee and Wi-Fi","DSL"], answer:2, explanation:"Smart home devices often use Zigbee and Wi-Fi." },
  { q:"What does handoff prevent?", options:["Package loss","Network growth","Signal interference","Static routing"], answer:0, explanation:"Handoff prevents call or session loss as a mobile device moves between cells." },
  { q:"What is a characteristic of 5G networks?", options:["Lower capacity","Higher latency","Support for IoT and high speeds","No use for mobile devices"], answer:2, explanation:"5G supports IoT and high-speed mobile communication." },
  { q:"Which wireless standard supports high data rate multimedia?", options:["802.3","802.11ac or ax","802.15.4","802.16"], answer:1, explanation:"802.11ac and 802.11ax support high-data-rate multimedia applications." },
  { q:"What is a mobility management function?", options:["Password encryption","Tracking device location for roaming","Building physical media","Creating a protocol"], answer:1, explanation:"Mobility management tracks device location and supports roaming." },
  { q:"What is a likely source of wireless interference?", options:["Coaxial cable","Other radio signals","Optical fiber","Network switch"], answer:1, explanation:"Other radio signals are a common source of wireless interference." },
  { q:"Which wireless technology uses frequency hopping?", options:["Wi-Fi","Bluetooth","Ethernet","Optical fiber"], answer:1, explanation:"Bluetooth uses frequency hopping to reduce interference." }
];

const DC_MODERN_TECH_QUESTIONS = [
  { q:"What does IoT stand for?", options:["Internet of Things","Internet of Technology","Integration of Telecom","Information of Transport"], answer:0, explanation:"IoT stands for Internet of Things." },
  { q:"What is 5G primarily designed to improve?", options:["Power consumption","Data rate and latency","Cable length","Number of devices"], answer:1, explanation:"5G is designed to improve data rates and reduce latency." },
  { q:"What is SDN?", options:["Secure Data Network","Software-Defined Networking","Static Device Network","Sensor Data Node"], answer:1, explanation:"SDN stands for Software-Defined Networking." },
  { q:"What does NFV do?", options:["Changes cables","Virtualizes network functions","Encrypts traffic","Creates protocols"], answer:1, explanation:"NFV virtualizes network functions in software." },
  { q:"What is cloud networking?", options:["Local only networking","Using cloud services for network resources","A physical cable system","A security protocol"], answer:1, explanation:"Cloud networking uses cloud services to provide network resources and services." },
  { q:"What is MPLS?", options:["Multiprotocol Label Switching","Multiple Protocol Layer Security","Mobile Public Link Service","Metric Path Link System"], answer:0, explanation:"MPLS stands for Multiprotocol Label Switching." },
  { q:"What does VoIP allow?", options:["Video over Internet","Voice over Internet Protocol","Virtual optical link","Value of IP"], answer:1, explanation:"VoIP allows voice communication over IP networks." },
  { q:"What is a benefit of video conferencing technology?", options:["Only audio","In-person travel","Remote collaboration","Lower bandwidth"], answer:2, explanation:"Video conferencing supports remote collaboration." },
  { q:"What is satellite internet used for?", options:["Local area networking","Remote area connectivity","Ethernet cables","Bluetooth connections"], answer:1, explanation:"Satellite internet provides connectivity in remote locations." },
  { q:"What does FTTH stand for?", options:["Fiber to the Home","Fast Telecom Transmission Hub","Fiber to the Host","First Time Hardware"], answer:0, explanation:"FTTH stands for Fiber to the Home." },
  { q:"What is edge computing?", options:["Centralized cloud only","Processing data near the source","More network cables","A switching technique"], answer:1, explanation:"Edge computing processes data closer to where it is generated." },
  { q:"What is a mesh network advantage?", options:["Single path only","Improved coverage and redundancy","Higher interference","More wired cable"], answer:1, explanation:"Mesh networks improve coverage and redundancy." },
  { q:"What is backhaul in communication networks?", options:["Local device connection","Link between access points and the core network","User authentication","Protocol encryption"], answer:1, explanation:"Backhaul connects access points or base stations to the core network." },
  { q:"What is a smart city application of networks?", options:["Network cabling only","Using sensors and communication for urban services","Only social media","Only voice calls"], answer:1, explanation:"Smart cities use sensors and communication for urban services." },
  { q:"What is network virtualization?", options:["Physical cabling","Creating virtual networks in software","Encrypting packets","Measuring bandwidth"], answer:1, explanation:"Network virtualization creates virtual networks in software." },
  { q:"What is a feature of AI-driven networks?", options:["Static configuration","Self-optimization","Pure hardware only","No routing"], answer:1, explanation:"AI-driven networks can self-optimize and adapt automatically." },
  { q:"What is Li-Fi?", options:["Light Fidelity wireless communication","A data encryption method","A routing protocol","A fiber optic cable"], answer:0, explanation:"Li-Fi is a wireless communication method using light." },
  { q:"What is a VANET?", options:["Virtual Access Network","Vehicular Ad Hoc Network","Voice and Network Equipment","Visual Area Node"], answer:1, explanation:"VANET stands for Vehicular Ad Hoc Network." },
  { q:"What does M2M communication mean?", options:["Man to Machine","Machine to Machine","Media to Media","Multiple to Multiple"], answer:1, explanation:"M2M means Machine to Machine communication." },
  { q:"Which technology supports smart grid communication?", options:["Paper mail","IoT and networking","Manual switches","Broadcast TV"], answer:1, explanation:"Smart grid communication uses IoT and networking technologies." },
  { q:"What is URLLC in 5G?", options:["Ultra-Reliable Low-Latency Communication","User Rate Limit Control","Unified Routing Link Control","Universal Resource Logistics"], answer:0, explanation:"URLLC is Ultra-Reliable Low-Latency Communication in 5G." },
  { q:"What is network automation?", options:["Manual configuration","Automating network tasks","Using only cables","Static IP assignment"], answer:1, explanation:"Network automation automates repetitive network tasks." },
  { q:"What is a cyber-physical system?", options:["A physical network cable","A system integrating computation and physical processes","A type of firewall","A routing protocol"], answer:1, explanation:"A cyber-physical system integrates computation with physical processes." },
  { q:"What is a wireless sensor network?", options:["Wired sensors","Distributed wireless sensors communicating data","A single router","A phone network"], answer:1, explanation:"A wireless sensor network consists of distributed wireless sensors that communicate data." },
  { q:"What is an emerging area for high-speed communication beyond 5G?", options:["Dial-up","Li-Fi and quantum communication","Coaxial cable only","Token ring"], answer:1, explanation:"Emerging areas beyond 5G include Li-Fi and quantum communication." },
  { q:"What does virtualization reduce in the network?", options:["Performance","Hardware dependency","Security","Protocols"], answer:1, explanation:"Virtualization reduces dependency on specific hardware." },
  { q:"What is AR/VR streaming a demand for?", options:["Low bandwidth","High-speed low-latency networks","Circuit switching only","No security"], answer:1, explanation:"AR/VR streaming demands high-speed, low-latency networks." },
  { q:"What is the main benefit of fiber optic broadband?", options:["Low speed","High speed and reliability","Large interference","No security"], answer:1, explanation:"Fiber optic broadband offers high speed and reliability." },
  { q:"What is network slicing in modern networks?", options:["Splitting a single cable","Creating virtual networks for different services","Broadcasting data","Encrypting bits"], answer:1, explanation:"Network slicing creates virtual network segments tailored for different services." },
  { q:"What is the goal of next-gen communication technologies?", options:["Lower speeds","Higher latency","Better connectivity and intelligence","Fewer devices"], answer:2, explanation:"Next-gen communication technologies aim for better connectivity and intelligent network behavior." }
];

const DC_QUESTION_MAP = {
  48: DC_INTRO_QUESTIONS,
  49: DC_NET_TYPES_QUESTIONS,
  50: DC_TRANSMISSION_QUESTIONS,
  51: DC_SIGNALS_QUESTIONS,
  52: DC_OSI_QUESTIONS,
  53: DC_TCPIP_QUESTIONS,
  54: DC_SWITCHING_QUESTIONS,
  55: DC_ERROR_QUESTIONS,
  56: DC_NETWORK_DEVICES_QUESTIONS,
  57: DC_SECURITY_QUESTIONS,
  58: DC_WIRELESS_QUESTIONS,
  59: DC_MODERN_TECH_QUESTIONS
};

// Optional export for module-based usage
if (typeof module !== 'undefined') { module.exports = { DC_INTRO_QUESTIONS, DC_NET_TYPES_QUESTIONS, DC_TRANSMISSION_QUESTIONS, DC_SIGNALS_QUESTIONS, DC_OSI_QUESTIONS, DC_TCPIP_QUESTIONS, DC_SWITCHING_QUESTIONS, DC_ERROR_QUESTIONS, DC_NETWORK_DEVICES_QUESTIONS, DC_SECURITY_QUESTIONS, DC_WIRELESS_QUESTIONS, DC_MODERN_TECH_QUESTIONS, DC_QUESTION_MAP }; }
