// Python Programming questions extracted from app (2) (1).js

// ═══════════════════════════════════════════════════════════════════════
// PYTHON QUESTION BANKS
// ═══════════════════════════════════════════════════════════════════════

const PY_BASICS = [
  {q:"What keyword is used to print output in Python?",options:["echo","console.log","print","output"],answer:2,explanation:"print() is the built-in function to display output on the screen."},
  {q:"How do you create a variable x with value 10 in Python?",options:["var x = 10","int x = 10","x = 10","let x = 10"],answer:2,explanation:"Python uses dynamic typing. Simply write x = 10 — no type keyword needed."},
  {q:"What is the data type of 3.14 in Python?",options:["int","str","bool","float"],answer:3,explanation:"3.14 is a floating-point number, so its type is float."},
  {q:"What does type(42) return?",options:["<class 'float'>","<class 'str'>","<class 'int'>","<class 'bool'>"],answer:2,explanation:"42 is an integer, so type(42) returns <class 'int'>."},
  {q:"Which of these is a valid Python comment?",options:["// This is a comment","/* comment */","# This is a comment","-- comment"],answer:2,explanation:"Python uses the # symbol to start a single-line comment."},
  {q:"How do you convert the string '5' to an integer?",options:["str('5')","float('5')","int('5')","parse('5')"],answer:2,explanation:"int('5') converts the string '5' to the integer 5."},
  {q:"What is the output of: print(type(True))?",options:["<class 'int'>","<class 'str'>","<class 'bool'>","<class 'float'>"],answer:2,explanation:"True is a boolean value, so type(True) returns <class 'bool'>."},
  {q:"Which function reads user input from the keyboard?",options:["read()","scan()","get()","input()"],answer:3,explanation:"input() reads a line of text entered by the user and returns it as a string."},
  {q:"What is the result of str(100)?",options:["100","'100'","int","error"],answer:1,explanation:"str(100) converts the integer 100 to the string '100'."},
  {q:"What symbol is used for string concatenation in Python?",options:["&","+","*","."],answer:1,explanation:"The + operator joins (concatenates) two strings together."},
  {q:"Which of these is a boolean value in Python?",options:["'True'","1.0","True","yes"],answer:2,explanation:"Python's boolean values are exactly True and False (capital T and F)."},
  {q:"What does len('hello') return?",options:["4","5","6","error"],answer:1,explanation:"len() returns the number of characters. 'hello' has 5 characters."},
  {q:"What is the result of 10 // 3 in Python?",options:["3.33","3","4","1"],answer:1,explanation:"// is floor division. 10 // 3 = 3 (integer part only)."},
  {q:"What does 10 % 3 return?",options:["3","0","1","2"],answer:3,explanation:"% is the modulo operator. 10 % 3 = 1 (remainder when 10 is divided by 3)."},
  {q:"What is the result of 2 ** 3?",options:["6","8","5","9"],answer:1,explanation:"** is the exponentiation operator. 2 ** 3 = 8."},
  {q:"Which creates a multi-line string in Python?",options:["'text'","\"text\"","'''text'''","#text"],answer:2,explanation:"Triple quotes (''' or \"\"\") are used for multi-line strings."},
  {q:"What does float('3.14') return?",options:["'3.14'","3","3.14","error"],answer:2,explanation:"float('3.14') converts the string '3.14' to 3.14."},
  {q:"What is the output of print(5 > 3)?",options:["5","3","True","False"],answer:2,explanation:"5 > 3 evaluates to True."},
  {q:"Which operator checks equality in Python?",options:["=","==","===","!="],answer:1,explanation:"== checks if two values are equal. A single = is assignment."},
  {q:"What is the data type of 'Python'?",options:["int","float","bool","str"],answer:3,explanation:"Any text enclosed in quotes is a string (str) in Python."},
  {q:"What does print('Hi' * 3) output?",options:["Hi3","HiHiHi","Hi Hi Hi","error"],answer:1,explanation:"String * integer repeats the string. 'Hi' * 3 = 'HiHiHi'."},
  {q:"Which is NOT a valid variable name in Python?",options:["my_var","_var","2var","var2"],answer:2,explanation:"Variable names cannot start with a digit. 2var is invalid."},
  {q:"What does bool(0) return?",options:["True","False","0","error"],answer:1,explanation:"bool(0) returns False. Zero is falsy in Python."},
  {q:"What is the result of 'hello'.upper()?",options:["hello","HELLO","Hello","hELLO"],answer:1,explanation:".upper() converts all characters to uppercase."},
  {q:"What does 'Python'.lower() return?",options:["PYTHON","Python","python","error"],answer:2,explanation:".lower() converts all characters to lowercase."},
  {q:"What is the output of print(10 / 4)?",options:["2","2.5","3","2.0"],answer:1,explanation:"/ performs true division. 10 / 4 = 2.5 (a float)."},
  {q:"What does 'hello'.replace('l','r') return?",options:["herro","hello","helo","error"],answer:0,explanation:".replace('l','r') replaces every 'l' with 'r', giving 'herro'."},
  {q:"What is None in Python?",options:["Zero","False","Empty string","Absence of a value"],answer:3,explanation:"None represents the absence of a value or a null value in Python."},
  {q:"What does 'hello world'.split() return?",options:["['hello world']","['hello','world']","'hello','world'","error"],answer:1,explanation:".split() splits a string on whitespace and returns a list of words."},
  {q:"Which method removes whitespace from both ends of a string?",options:["strip()","trim()","clean()","remove()"],answer:0,explanation:".strip() removes leading and trailing whitespace from a string."}
];

const PY_CONTROL = [
  {q:"What is the correct syntax for an if statement in Python?",options:["if (x > 0) {}","if x > 0:","if x > 0 then","if x > 0 do"],answer:1,explanation:"Python uses a colon after the condition. Indentation defines the block."},
  {q:"What keyword is used for 'else if' in Python?",options:["elseif","else if","elif","elsif"],answer:2,explanation:"Python uses elif as a shorthand for 'else if'."},
  {q:"How many times does 'for i in range(5):' loop?",options:["4","5","6","3"],answer:1,explanation:"range(5) generates 0,1,2,3,4 — the loop runs 5 times."},
  {q:"What does 'break' do inside a loop?",options:["Skips one iteration","Exits the loop immediately","Restarts the loop","Exits the program"],answer:1,explanation:"break immediately terminates the nearest enclosing loop."},
  {q:"What does 'continue' do inside a loop?",options:["Stops the loop","Exits the program","Skips the rest of the current iteration","Restarts the loop"],answer:2,explanation:"continue skips remaining code in the current iteration and jumps to the next."},
  {q:"What is the output of: for i in range(3): print(i)?",options:["1 2 3","0 1 2","0 1 2 3","1 2"],answer:1,explanation:"range(3) gives 0, 1, 2. print(i) outputs each on a new line."},
  {q:"Which loop is best when the number of iterations is unknown?",options:["for loop","while loop","do-while loop","range loop"],answer:1,explanation:"A while loop continues as long as a condition is true."},
  {q:"What does 'pass' do in Python?",options:["Exits the loop","Skips a value","Does nothing (placeholder)","Prints a blank line"],answer:2,explanation:"pass is a no-operation statement used as a placeholder."},
  {q:"What does range(2, 8, 2) generate?",options:["2 4 6 8","2 4 6","1 3 5 7","2 3 4 5 6 7"],answer:1,explanation:"range(start,stop,step) → range(2,8,2) gives 2, 4, 6 (stops before 8)."},
  {q:"In Python, what value makes a while loop stop?",options:["None","True","False","0"],answer:2,explanation:"A while loop stops when its condition becomes False."},
  {q:"What is the output of: i=0; while i<3: print(i); i+=1?",options:["0 1 2 3","1 2 3","0 1 2","infinite loop"],answer:2,explanation:"i prints 0, 1, 2, then i becomes 3 which is not < 3, loop ends."},
  {q:"Which statement creates an infinite loop?",options:["while True:","for i in range():","while False:","for i in []:"],answer:0,explanation:"while True: never has a false condition, so it loops forever unless break is used."},
  {q:"What keyword is the final fallback when all conditions fail?",options:["elif","then","else","default"],answer:2,explanation:"else is the final fallback block that runs when no if or elif is True."},
  {q:"What is the output of: for i in range(5): if i==3: break; print(i)?",options:["0 1 2 3","0 1 2","3 4","1 2 3"],answer:1,explanation:"Prints 0, 1, 2. When i==3, break exits before printing 3."},
  {q:"What does 'for char in \"abc\":' iterate over?",options:["Indices only","Characters a, b, c","The whole string once","Numbers 0 1 2"],answer:1,explanation:"Iterating over a string goes through each character one by one."},
  {q:"How do you loop through a list [10,20,30] and print each item?",options:["for i in range(list):","for item in [10,20,30]: print(item)","while [10,20,30]:","loop [10,20,30]:"],answer:1,explanation:"for item in list: iterates directly over each element."},
  {q:"What does 'else' after a for loop mean in Python?",options:["Always runs","Runs if loop was broken","Runs if loop completed without break","Never runs"],answer:2,explanation:"The else block after a for loop executes only if the loop finished without break."},
  {q:"What is the output of: x=10; print('big') if x>5 else print('small')?",options:["small","big","error","10"],answer:1,explanation:"x=10 > 5 is True, so 'big' is printed."},
  {q:"range(10, 0, -2) produces:",options:["0 2 4 6 8","10 8 6 4 2","10 8 6 4 2 0","1 3 5 7 9"],answer:1,explanation:"Starts at 10, steps by -2, stops before 0: gives 10, 8, 6, 4, 2."},
  {q:"What is a nested loop?",options:["A loop inside another loop","A loop with a condition","A loop that breaks","A loop using range only"],answer:0,explanation:"A nested loop is a loop placed inside another loop's body."},
  {q:"Which is NOT a valid loop in Python?",options:["for loop","while loop","do-while loop","nested loop"],answer:2,explanation:"Python does not have a do-while loop."},
  {q:"What does 'for i in range(0)' do?",options:["Runs once","Runs infinitely","Never runs","Error"],answer:2,explanation:"range(0) is empty, so the for loop body never executes."},
  {q:"What does 'for i in [1,2,3]: continue' do to print('done')?",options:["done","1 2 3","Nothing","error"],answer:2,explanation:"continue skips every iteration. print('done') is never reached."},
  {q:"In a while loop, what is i+=1 used for?",options:["Break the loop","Print i","Update the counter to avoid infinite loop","Reset i"],answer:2,explanation:"Without incrementing i, the loop condition never changes and loops forever."},
  {q:"What does 'if not x:' mean?",options:["if x is True","if x is not empty","if x is False or falsy","if x is a number"],answer:2,explanation:"'not x' is True when x is falsy (False, 0, None, empty string, empty list)."},
  {q:"What is the output of: x=3; print('yes') if x%2==0 else print('no')?",options:["yes","no","3","error"],answer:1,explanation:"3 % 2 = 1, not 0, so the condition is False and 'no' is printed."},
  {q:"What does 'for i in enumerate([\"a\",\"b\"])' give?",options:["Only values","Only indices","Index and value pairs","Error"],answer:2,explanation:"enumerate() returns pairs of (index, value)."},
  {q:"How do you use a for loop to print numbers 1 to 5?",options:["for i in range(5):","for i in range(1,6): print(i)","for i in range(6):","for i in range(1,5):"],answer:1,explanation:"range(1,6) generates 1,2,3,4,5. The stop value 6 is excluded."},
  {q:"What is the purpose of the 'else' clause in a while loop?",options:["Runs if condition was True at start","Runs if loop ended because condition became False","Runs if break was used","Never runs"],answer:1,explanation:"else after while runs when the while condition becomes False normally."},
  {q:"What is the output of: for i in range(1,4): print(i*2)?",options:["1 2 3","2 4 6","2 4 6 8","1 4 9"],answer:1,explanation:"range(1,4) gives 1,2,3. Multiplied by 2: 2, 4, 6."}
];

const PY_FUNCTIONS = [
  {q:"What keyword defines a function in Python?",options:["func","function","def","define"],answer:2,explanation:"def is the keyword used to declare a new function in Python."},
  {q:"What does a function return if it has no return statement?",options:["0","False","None","Error"],answer:2,explanation:"Python functions implicitly return None when there is no explicit return statement."},
  {q:"What is a default parameter value?",options:["A required parameter","A value used when no argument is given","The first parameter","A global variable"],answer:1,explanation:"def greet(name='World'): uses 'World' if no name argument is passed."},
  {q:"What does *args allow in a function?",options:["Only keyword arguments","A fixed number of arguments","Any number of positional arguments","No arguments"],answer:2,explanation:"*args collects any extra positional arguments into a tuple."},
  {q:"What is a lambda function?",options:["A function with def","A class method","An anonymous one-line function","A recursive function"],answer:2,explanation:"lambda x: x*2 is an anonymous function defined in a single expression."},
  {q:"What does **kwargs allow in a function?",options:["Any number of keyword arguments","Only positional arguments","A fixed argument count","No arguments"],answer:0,explanation:"**kwargs collects any extra keyword arguments into a dictionary."},
  {q:"What is the output of: def add(a,b): return a+b; print(add(3,4))?",options:["34","7","ab","error"],answer:1,explanation:"add(3,4) returns 3+4=7."},
  {q:"What does the 'global' keyword do inside a function?",options:["Creates a new variable","Allows access to a global variable","Deletes a variable","Returns a value"],answer:1,explanation:"global x inside a function lets you read and modify the global variable x."},
  {q:"What is a recursive function?",options:["A function that returns None","A function that calls itself","A function with no parameters","A lambda function"],answer:1,explanation:"A recursive function calls itself to solve smaller instances of the same problem."},
  {q:"Which is a valid lambda to double a number?",options:["lambda: x*2","lambda x: x*2","def x: x*2","function(x) x*2"],answer:1,explanation:"lambda x: x*2 takes one argument x and returns x*2."},
  {q:"What is the output of: f = lambda x,y: x+y; print(f(2,3))?",options:["23","5","xy","error"],answer:1,explanation:"The lambda adds its two arguments. f(2,3) = 5."},
  {q:"What does 'return' do in a function?",options:["Exits the program","Prints a value","Sends a value back to the caller","Skips a line"],answer:2,explanation:"return ends the function and sends a result back to the caller."},
  {q:"Can a function return multiple values in Python?",options:["No","Yes, as a tuple","Yes, but only two","No, only None"],answer:1,explanation:"def f(): return 1,2 returns a tuple (1,2)."},
  {q:"What is the scope of a variable defined inside a function?",options:["Global","Local","Module","Universal"],answer:1,explanation:"Variables defined inside a function are local — they only exist within that function."},
  {q:"What is the output of: def greet(name='Ali'): print('Hi',name); greet()?",options:["Hi","Hi Ali","Hi name","error"],answer:1,explanation:"No argument passed, so default 'Ali' is used. Output: Hi Ali."},
  {q:"Which is the correct way to call a function named calc?",options:["call calc()","calc[]","calc()","run calc"],answer:2,explanation:"Functions are called by writing their name followed by parentheses."},
  {q:"What does a function docstring do?",options:["Runs the function","Documents what the function does","Deletes the function","Returns None"],answer:1,explanation:"A docstring documents the function's purpose and is placed right after def."},
  {q:"What is the output of: def f(x, y=5): return x+y; print(f(3))?",options:["3","5","8","error"],answer:2,explanation:"y defaults to 5. f(3) = 3 + 5 = 8."},
  {q:"What does 'pass' do inside a function body?",options:["Returns None","Raises an error","Acts as a placeholder — does nothing","Exits the function"],answer:2,explanation:"pass allows an empty function body without causing a syntax error."},
  {q:"What is the output of: def sq(n): return n**2; print(sq(4))?",options:["8","16","4","error"],answer:1,explanation:"sq(4) returns 4**2 = 16."},
  {q:"In Python, functions are treated as:",options:["Keywords","First-class objects","Operators","Constants"],answer:1,explanation:"Functions are first-class objects — they can be stored in variables and passed to other functions."},
  {q:"What is a higher-order function?",options:["A function with many lines","A function that takes or returns another function","A function with default args","A recursive function"],answer:1,explanation:"Higher-order functions accept functions as arguments or return functions as results."},
  {q:"What does map(func, list) do?",options:["Filters a list","Applies func to each element of list","Sorts a list","Counts elements"],answer:1,explanation:"map() applies the given function to every element of an iterable."},
  {q:"What does filter(func, list) do?",options:["Maps values","Applies func and keeps elements where func returns True","Sorts the list","Returns func"],answer:1,explanation:"filter() keeps only those elements for which the function returns True."},
  {q:"What does sorted([3,1,2]) return?",options:["[3,1,2]","[1,2,3]","[3,2,1]","error"],answer:1,explanation:"sorted() returns a new sorted list in ascending order."},
  {q:"What is the output of: print(list(map(lambda x: x*2, [1,2,3])))?",options:["[1,2,3]","[2,4,6]","[1,4,9]","error"],answer:1,explanation:"lambda x: x*2 doubles each element. Result: [2,4,6]."},
  {q:"What is the output of: def f(*args): return sum(args); print(f(1,2,3))?",options:["123","3","6","error"],answer:2,explanation:"*args collects (1,2,3). sum((1,2,3)) = 6."},
  {q:"What does 'nonlocal' keyword do?",options:["Creates a global variable","Allows modifying a variable in the enclosing scope","Deletes a variable","Creates a local variable"],answer:1,explanation:"nonlocal allows a nested function to modify a variable from its enclosing function's scope."},
  {q:"What is a closure in Python?",options:["A locked class","A function that remembers variables from its enclosing scope","A function that returns None","A recursive function"],answer:1,explanation:"A closure is a function that captures variables from its outer function."},
  {q:"What is the output of: f = lambda x: x if x>0 else -x; print(f(-5))?",options:["-5","5","0","error"],answer:1,explanation:"x=-5 is not > 0, so -x = -(-5) = 5 is returned."}
];

const PY_LISTS = [
  {q:"How do you access the first element of a list named 'items'?",options:["items[1]","items(0)","items[0]","items.first()"],answer:2,explanation:"Python lists are zero-indexed. The first element is at index 0."},
  {q:"Which list method adds an element to the end?",options:["add()","insert()","push()","append()"],answer:3,explanation:"list.append(value) adds value to the end of the list."},
  {q:"What is the key difference between a list and a tuple?",options:["Lists use () and tuples use []","Tuples are mutable, lists are not","Lists are mutable, tuples are immutable","No difference"],answer:2,explanation:"Lists can be changed after creation; tuples cannot."},
  {q:"What does list.pop() do by default?",options:["Removes first element","Removes last element","Removes all elements","Returns last element without removing"],answer:1,explanation:"pop() with no argument removes and returns the last element."},
  {q:"What does 'in' do with a list?",options:["Adds an element","Checks membership","Removes an element","Sorts the list"],answer:1,explanation:"'in' checks if a value exists in the list, returning True or False."},
  {q:"What is the output of: [1,2,3][1]?",options:["1","2","3","error"],answer:1,explanation:"Index 1 refers to the second element. [1,2,3][1] = 2."},
  {q:"What does [1,2,3,4,5][1:3] return?",options:["[1,2]","[2,3]","[3,4]","[2,3,4]"],answer:1,explanation:"Slicing [1:3] returns elements at index 1 and 2. Result: [2,3]."},
  {q:"What does list.sort() do?",options:["Returns a new sorted list","Sorts the list in place","Creates a copy","Reverses the list"],answer:1,explanation:"list.sort() modifies the list in place."},
  {q:"How do you create an empty list?",options:["list()","[]","list{}","Both list() and []"],answer:3,explanation:"Both [] and list() create an empty list."},
  {q:"What does len([10,20,30]) return?",options:["10","2","3","30"],answer:2,explanation:"len() returns the number of elements. [10,20,30] has 3 elements."},
  {q:"What is the output of: t = (1,2,3); print(t[2])?",options:["1","2","3","error"],answer:2,explanation:"Tuple indexing works like lists. t[2] is the third element: 3."},
  {q:"What happens if you try to change a tuple element?",options:["It changes","Returns None","Raises a TypeError","Creates a new tuple"],answer:2,explanation:"Tuples are immutable. Attempting t[0]=5 raises TypeError."},
  {q:"What does [0]*5 produce?",options:["[0,1,2,3,4]","[0,0,0,0,0]","[5]","error"],answer:1,explanation:"list * integer repeats the list. [0]*5 = [0,0,0,0,0]."},
  {q:"What does list.remove(x) do?",options:["Removes element at index x","Removes first occurrence of value x","Removes all x","Returns x"],answer:1,explanation:"list.remove(x) removes the first item whose value equals x."},
  {q:"Which is a valid list comprehension?",options:["[x*2 for x in range(5)]","(x*2 for x in range(5))","list x*2 for x in 5","x*2 [x in range(5)]"],answer:0,explanation:"List comprehensions use square brackets: [expression for item in iterable]."},
  {q:"What does [x for x in range(6) if x%2==0] produce?",options:["[1,3,5]","[0,2,4]","[0,2,4,6]","[2,4,6]"],answer:1,explanation:"Keeps even numbers from range(6)=0-5. Result: [0,2,4]."},
  {q:"What does list.index(x) return?",options:["Count of x","First index where x appears","Last index of x","True or False"],answer:1,explanation:"list.index(x) returns the index of the first occurrence of x."},
  {q:"How do you reverse a list in place?",options:["list.sort(reverse=True)","list.reverse()","list[::-1]","reversed(list)"],answer:1,explanation:"list.reverse() reverses the list in place, modifying the original."},
  {q:"What does tuple() do?",options:["Creates an empty list","Converts an iterable to a tuple","Converts a tuple to a list","Deletes a tuple"],answer:1,explanation:"tuple(iterable) converts any iterable into a tuple."},
  {q:"What is the output of: a=[1,2]; b=a; b.append(3); print(a)?",options:["[1,2]","[1,2,3]","[3]","error"],answer:1,explanation:"b=a makes b point to the same list. Appending to b also changes a."},
  {q:"How do you make a shallow copy of a list?",options:["b=a","b=a.copy()","b=copy(a)","b=tuple(a)"],answer:1,explanation:"a.copy() creates a new list, so changes to b won't affect a."},
  {q:"What does list.count(x) do?",options:["Returns total elements","Counts occurrences of x","Returns x's index","Sorts by count"],answer:1,explanation:"list.count(x) returns how many times x appears in the list."},
  {q:"Which method joins a list of strings?",options:["list.join()","','.join(list)","join(list)","str.join()"],answer:1,explanation:"'sep'.join(list) combines list elements into a string using sep as separator."},
  {q:"What does list.insert(1, 'x') do?",options:["Replaces index 1 with 'x'","Inserts 'x' at index 1","Appends 'x'","Removes index 1"],answer:1,explanation:"insert(i, val) inserts val before the element at position i."},
  {q:"What does list.extend([4,5]) do?",options:["Appends [4,5] as one element","Adds 4 and 5 individually to the list","Creates a new list","Sorts and adds"],answer:1,explanation:"extend() adds each element of the iterable to the list individually."},
  {q:"What is list slicing?",options:["Sorting a list","Extracting a portion of a list","Deleting a list","Copying a tuple"],answer:1,explanation:"Slicing extracts a sub-list using list[start:stop:step] syntax."},
  {q:"What is the output of: [1,2,3] + [4,5]?",options:["[1,2,3,4,5]","[5,7]","error","[1,2,3],[4,5]"],answer:0,explanation:"+ concatenates two lists into one new list."},
  {q:"How do you check if a list is empty?",options:["list.empty()","if not list:","if list==None:","if len==0:"],answer:1,explanation:"An empty list is falsy. 'if not list:' returns True when the list has no elements."},
  {q:"What does list.clear() do?",options:["Deletes the variable","Removes all elements","Sorts the list","Returns an empty tuple"],answer:1,explanation:"list.clear() removes all elements, leaving an empty list []."},
  {q:"What is the output of: t=(1,2,3); print(len(t))?",options:["1","2","3","error"],answer:2,explanation:"len() works on tuples. The tuple has 3 elements."}
];

const PY_DICTS = [
  {q:"How do you get the value for key 'name' from dict d?",options:["d.name","d[name]","d('name')","d['name']"],answer:3,explanation:"Dictionary values are accessed using d['key'] with the key in quotes."},
  {q:"Which method returns all keys of a dictionary?",options:["dict.values()","dict.items()","dict.keys()","dict.list()"],answer:2,explanation:"dict.keys() returns a view of all the keys."},
  {q:"How do you create an empty dictionary?",options:["{}","dict()","[]","Both {} and dict()"],answer:3,explanation:"Both {} and dict() create an empty dictionary."},
  {q:"What does dict.get('key') return if the key doesn't exist?",options:["Error","0","None","False"],answer:2,explanation:"dict.get(key) returns None (not an error) if the key is not found."},
  {q:"How do you add a new key 'age' with value 25 to dict d?",options:["d.add('age',25)","d['age']=25","d.insert('age',25)","d.set('age',25)"],answer:1,explanation:"Simply assign d['age'] = 25 to add or update a key-value pair."},
  {q:"What does dict.values() return?",options:["All keys","All values","All key-value pairs","The length"],answer:1,explanation:"dict.values() returns a view of all values in the dictionary."},
  {q:"What does dict.items() return?",options:["All keys","All values","All key-value pairs as tuples","The length"],answer:2,explanation:"dict.items() returns pairs of (key, value) as a view of tuples."},
  {q:"How do you remove a key from a dictionary?",options:["dict.remove(key)","del dict[key]","dict.delete(key)","dict.pop(key) only"],answer:1,explanation:"del dict[key] removes the key-value pair."},
  {q:"What does dict.update({'b':2}) do?",options:["Replaces dict with {'b':2}","Adds or updates keys from the given dict","Removes 'b'","Sorts the dict"],answer:1,explanation:"update() merges the given dictionary, adding or overwriting keys."},
  {q:"What is the output of: d={'a':1,'b':2}; print(len(d))?",options:["1","2","3","error"],answer:1,explanation:"len(d) returns the number of key-value pairs: 2."},
  {q:"How do you check if 'name' is a key in dict d?",options:["'name' in d.values()","'name' in d","'name' in d.items()","d.has('name')"],answer:1,explanation:"'in' on a dictionary checks for key existence by default."},
  {q:"What is a set in Python?",options:["An ordered list","A mutable sequence","An unordered collection of unique elements","A key-value store"],answer:2,explanation:"A set is an unordered collection where all elements are unique."},
  {q:"How do you create a set in Python?",options:["set = []","set = {}","s = {1,2,3} or set([1,2,3])","set = ()"],answer:2,explanation:"Use curly braces {1,2,3} or set() constructor."},
  {q:"What does set.add(x) do?",options:["Adds x if not already in set","Replaces set with x","Sorts set and adds x","Raises error if x exists"],answer:0,explanation:"set.add(x) inserts x. If x already exists, nothing happens."},
  {q:"What is the output of: s={1,2,2,3,3}; print(len(s))?",options:["5","4","3","error"],answer:2,explanation:"Sets remove duplicates. {1,2,2,3,3} becomes {1,2,3} with 3 elements."},
  {q:"What does set.union(other) return?",options:["Common elements","All elements from both sets","Elements in set but not other","Elements in other but not set"],answer:1,explanation:"union() returns all elements from both sets (duplicates removed)."},
  {q:"What does set.intersection(other) return?",options:["All elements from both","Only elements in both sets","Elements not in both","Empty set"],answer:1,explanation:"intersection() returns elements that appear in both sets."},
  {q:"What does set.difference(other) return?",options:["Elements in both","Elements in set but NOT in other","Elements in other only","Union of sets"],answer:1,explanation:"difference() returns elements in the first set but not in the second."},
  {q:"Can a set contain duplicate values?",options:["Yes","No","Only numbers can repeat","Only strings can repeat"],answer:1,explanation:"Sets automatically remove duplicates — every element must be unique."},
  {q:"What is a frozenset?",options:["A mutable set","An immutable set","A dictionary","A tuple of sets"],answer:1,explanation:"frozenset is an immutable version of a set."},
  {q:"What does set.remove(x) do if x is not in the set?",options:["Does nothing","Returns False","Raises a KeyError","Adds x instead"],answer:2,explanation:"set.remove(x) raises KeyError if x is not found. Use discard() to avoid the error."},
  {q:"What is the output of: {1,2,3} | {3,4,5}?",options:["{3}","{1,2,4,5}","{1,2,3,4,5}","error"],answer:2,explanation:"| is the union operator. All unique elements: {1,2,3,4,5}."},
  {q:"What does {1,2,3} & {2,3,4} return?",options:["{1,4}","{2,3}","{1,2,3,4}","error"],answer:1,explanation:"& is the intersection operator. Common elements: {2,3}."},
  {q:"What does {1,2,3} - {2,3} return?",options:["{1}","{2,3}","{1,2,3}","error"],answer:0,explanation:"- is the difference operator. Elements in first but not second: {1}."},
  {q:"What does dict.pop('key') do?",options:["Returns key only","Removes and returns the value for 'key'","Adds 'key'","Returns all keys"],answer:1,explanation:"dict.pop(key) removes the key and returns its value."},
  {q:"How do you loop through key-value pairs of a dictionary?",options:["for k in d:","for k,v in d.items():","for v in d.values():","for k in d.keys():"],answer:1,explanation:"d.items() returns (key,value) tuples, unpack with for k,v in d.items()."},
  {q:"What does dict.setdefault('key', 0) do?",options:["Always sets 'key' to 0","Sets 'key' to 0 only if it doesn't exist","Removes 'key'","Returns all keys"],answer:1,explanation:"setdefault returns the value if the key exists; otherwise inserts it with the default."},
  {q:"Can dictionary keys be mutable objects like lists?",options:["Yes","No","Only if values are also mutable","Only in Python 3"],answer:1,explanation:"Dictionary keys must be hashable (immutable). Lists cannot be keys."},
  {q:"What is the output of: d={1:'a',2:'b'}; print('not found') if 3 not in d else print(d[3])?",options:["a","b","not found","error"],answer:2,explanation:"3 is not in d, so 'not found' is printed."},
  {q:"What does set.issubset(other) return?",options:["True if other is inside set","True if set is inside other","True if they are equal","Always True"],answer:1,explanation:"set.issubset(other) returns True if every element of set is also in other."}
];

const PY_OOP = [
  {q:"What keyword defines a class in Python?",options:["object","struct","class","type"],answer:2,explanation:"The 'class' keyword is used to define a new class in Python."},
  {q:"What is __init__ in a Python class?",options:["A destructor","A static method","The constructor called when an object is created","A private variable"],answer:2,explanation:"__init__ initialises a new instance and is automatically called on creation."},
  {q:"What does 'self' refer to inside a class method?",options:["The class itself","The current instance of the class","The parent class","A global variable"],answer:1,explanation:"'self' is a reference to the specific object that called the method."},
  {q:"How do you create an instance of class Dog?",options:["Dog.create()","new Dog()","Dog()","instance Dog"],answer:2,explanation:"In Python, create an instance by calling the class name like a function: Dog()."},
  {q:"What is inheritance in Python OOP?",options:["Copying code from another file","A child class acquiring attributes and methods of a parent class","Deleting a class","Running two classes at once"],answer:1,explanation:"class Dog(Animal): means Dog inherits all attributes and methods from Animal."},
  {q:"What does super() do in a child class?",options:["Deletes the parent class","Calls a method from the parent class","Creates a new object","Returns self"],answer:1,explanation:"super() gives access to methods of the parent class from the child class."},
  {q:"What is encapsulation?",options:["Inheriting methods","Hiding internal details and protecting data","Creating multiple classes","Overriding methods"],answer:1,explanation:"Encapsulation bundles data and methods together and restricts direct access."},
  {q:"What does a single underscore prefix (e.g., _name) indicate?",options:["Private, inaccessible","Protected by convention","Public","Static"],answer:1,explanation:"A single underscore signals the attribute is for internal use by convention."},
  {q:"What does double underscore prefix (e.g., __name) do?",options:["Makes it public","Makes it static","Triggers name mangling (strong privacy)","Deletes the attribute"],answer:2,explanation:"Double underscores cause name mangling, making the attribute harder to access from outside."},
  {q:"What is polymorphism in OOP?",options:["Same class, different objects","One method name behaving differently in different classes","Creating subclasses","Hiding data"],answer:1,explanation:"Polymorphism allows different classes to have methods with the same name but different behaviour."},
  {q:"What is method overriding?",options:["Adding a new method to a parent class","A child class providing its own version of an inherited method","Calling super()","Deleting a method"],answer:1,explanation:"Method overriding means redefining an inherited method in the subclass."},
  {q:"What does @staticmethod allow?",options:["Access to self","Access to class","Calling the method without an instance","Inheritance only"],answer:2,explanation:"A static method doesn't receive self or cls — it works like a regular function."},
  {q:"What does @classmethod receive as its first parameter?",options:["self","instance","cls (the class itself)","None"],answer:2,explanation:"Class methods receive cls (the class) as the first argument."},
  {q:"What is the output of: class A: def hi(self): print('Hello'); a=A(); a.hi()?",options:["A","hi","Hello","error"],answer:2,explanation:"a.hi() calls the method, which executes print('Hello')."},
  {q:"What does __str__ define in a class?",options:["Constructor","Destructor","String representation of the object","Static method"],answer:2,explanation:"__str__ is called by print() and str() to get a readable string representation."},
  {q:"What does __len__ define?",options:["How to add objects","Behaviour of len() on the object","Comparison behaviour","String format"],answer:1,explanation:"Defining __len__ allows len(obj) to return a custom length for your object."},
  {q:"Which is the correct way to inherit from class Animal?",options:["class Dog extends Animal:","class Dog(Animal):","class Dog inherits Animal:","class Dog::Animal:"],answer:1,explanation:"Python uses class ChildClass(ParentClass): syntax for inheritance."},
  {q:"What is multiple inheritance?",options:["Inheriting from more than one parent class","Creating multiple instances","Overriding many methods","Having many attributes"],answer:0,explanation:"Multiple inheritance: class C(A, B): inherits from both A and B."},
  {q:"What does __del__ define?",options:["Constructor","Destructor — called when object is destroyed","String representation","Comparison"],answer:1,explanation:"__del__ is the destructor, called when the object is garbage collected."},
  {q:"What is an abstract class?",options:["A class with no methods","A class that cannot be instantiated and must be subclassed","A class with only static methods","A class with __init__ only"],answer:1,explanation:"Abstract classes define methods that subclasses must implement."},
  {q:"What module provides abstract class support in Python?",options:["sys","os","abc","re"],answer:2,explanation:"The abc module provides ABC and @abstractmethod decorator."},
  {q:"What is __repr__ used for?",options:["Deleting objects","Official string representation for debugging","Len of object","Comparison"],answer:1,explanation:"__repr__ provides an unambiguous representation for debugging."},
  {q:"What is the MRO (Method Resolution Order)?",options:["The order methods are deleted","The order Python searches for methods in inheritance","The order attributes are created","The order objects are garbage collected"],answer:1,explanation:"MRO determines the order Python looks for methods in a class hierarchy."},
  {q:"What does isinstance(obj, ClassName) return?",options:["The class name","True if obj is an instance of ClassName (or subclass)","The object type","The object id"],answer:1,explanation:"isinstance checks whether obj is an instance of the given class or its subclasses."},
  {q:"What does issubclass(Child, Parent) check?",options:["If Child has more methods","If Child inherits from Parent","If Parent inherits from Child","If they are equal"],answer:1,explanation:"issubclass returns True if Child is a subclass of Parent."},
  {q:"What are class attributes vs instance attributes?",options:["Same thing","Class attributes are shared by all instances; instance attributes are unique to each object","Instance attributes are shared; class attributes are unique","No difference"],answer:1,explanation:"Class attributes are defined at class level and shared; instance attributes are set on self."},
  {q:"What does the __eq__ method define?",options:["String representation","Behaviour of == operator","Behaviour of + operator","Deletion"],answer:1,explanation:"__eq__ defines how two objects are compared using the == operator."},
  {q:"What is composition in OOP?",options:["Inheriting from multiple parents","A class containing an object of another class as an attribute","Overriding a method","Using class methods"],answer:1,explanation:"Composition is the 'has-a' relationship — one class uses another class's objects."},
  {q:"Can Python classes have multiple __init__ methods?",options:["Yes, as overloads","No, only one __init__ is allowed","Yes, with different names","Yes, but only in subclasses"],answer:1,explanation:"Python doesn't support method overloading. Only the last defined __init__ would be used."},
  {q:"What is duck typing in Python?",options:["A type checking system","An object is used based on its behaviour (methods) rather than its class","A type conversion","A way to create objects"],answer:1,explanation:"'If it walks like a duck and quacks like a duck, it's a duck.' Python checks for methods, not types."}
];

const PY_FILES = [
  {q:"Which function is used to open a file in Python?",options:["file()","read()","open()","load()"],answer:2,explanation:"open(filename, mode) opens a file and returns a file object."},
  {q:"What mode opens a file for reading?",options:["'w'","'a'","'r'","'x'"],answer:2,explanation:"'r' is the read mode. It is also the default mode."},
  {q:"What mode opens a file for writing (creates or overwrites)?",options:["'r'","'a'","'w'","'x'"],answer:2,explanation:"'w' opens for writing. If the file exists it is overwritten; if not, it is created."},
  {q:"What mode appends to an existing file?",options:["'r'","'a'","'w'","'x'"],answer:1,explanation:"'a' opens the file for appending. New data is added at the end."},
  {q:"What does 'with open(file) as f:' do?",options:["Opens and never closes","Opens and automatically closes when block exits","Creates the file","Reads the file in binary"],answer:1,explanation:"The 'with' statement ensures the file is closed automatically, even if an error occurs."},
  {q:"What does file.read() do?",options:["Reads one line","Reads all lines as a list","Reads the entire file as a string","Reads first character"],answer:2,explanation:"file.read() returns the entire file content as a single string."},
  {q:"What does file.readline() do?",options:["Reads all lines","Reads one line at a time","Reads last line","Reads file size"],answer:1,explanation:"file.readline() reads and returns one line including the newline character."},
  {q:"What does file.readlines() return?",options:["A single string","A list of all lines","Only first line","File size"],answer:1,explanation:"readlines() returns a list where each element is a line from the file."},
  {q:"What does file.write('text') do?",options:["Reads text","Appends text and saves","Writes text to the file","Closes the file"],answer:2,explanation:"file.write(string) writes the string to the file (must be in write or append mode)."},
  {q:"What is the purpose of try/except in Python?",options:["To define functions","To catch and handle exceptions","To create loops","To import modules"],answer:1,explanation:"try/except allows you to handle errors gracefully instead of crashing."},
  {q:"What does 'except Exception as e' capture?",options:["The exception type","The exception object (with message)","Only the message","Only the line number"],answer:1,explanation:"'as e' stores the exception object. Access its message with str(e)."},
  {q:"What does the 'finally' block do?",options:["Runs only if an error occurs","Runs only if no error occurs","Always runs, with or without an error","Defines the exception"],answer:2,explanation:"finally always executes regardless of whether an exception was raised."},
  {q:"What does 'raise' do in Python?",options:["Catches an exception","Manually triggers an exception","Ignores an exception","Logs an exception"],answer:1,explanation:"raise explicitly triggers an exception: raise ValueError('bad input')."},
  {q:"Which exception is raised for wrong data type?",options:["ValueError","IndexError","TypeError","KeyError"],answer:2,explanation:"TypeError is raised when an operation is applied to an object of the wrong type."},
  {q:"Which exception is raised when a key is missing from a dictionary?",options:["IndexError","KeyError","ValueError","AttributeError"],answer:1,explanation:"KeyError is raised when you try to access a dictionary key that doesn't exist."},
  {q:"Which exception is raised for list index out of range?",options:["KeyError","ValueError","IndexError","TypeError"],answer:2,explanation:"IndexError is raised when you try to access an index beyond the list's length."},
  {q:"Which exception is raised for dividing by zero?",options:["ValueError","ZeroDivisionError","ArithmeticError","TypeError"],answer:1,explanation:"ZeroDivisionError is raised when you divide by zero."},
  {q:"Which exception is raised when a file is not found?",options:["OSError","FileNotFoundError","IOError","ValueError"],answer:1,explanation:"FileNotFoundError is raised when the specified file doesn't exist."},
  {q:"How do you create a custom exception?",options:["class MyError: pass","class MyError(Exception): pass","raise Exception('custom')","except MyError:"],answer:1,explanation:"Custom exceptions extend the Exception class: class MyError(Exception): pass."},
  {q:"What is the output of: try: print(1/0) except ZeroDivisionError: print('error')?",options:["0","1","error","None"],answer:2,explanation:"1/0 raises ZeroDivisionError, which is caught, so 'error' is printed."},
  {q:"What does 'except (TypeError, ValueError):' mean?",options:["Catches only TypeError","Catches only ValueError","Catches either TypeError or ValueError","Catches all exceptions"],answer:2,explanation:"You can catch multiple exception types in one except clause."},
  {q:"What is the purpose of 'else' in a try/except block?",options:["Runs if exception occurred","Always runs","Runs only if no exception was raised","Defines a new exception"],answer:2,explanation:"The else block runs only when the try block completes without exception."},
  {q:"What does file.close() do?",options:["Deletes the file","Flushes and closes the file","Reads the file","Renames the file"],answer:1,explanation:"file.close() flushes any buffered data to disk and releases the file resource."},
  {q:"What mode opens a file in binary read mode?",options:["'r'","'rb'","'br'","'b'"],answer:1,explanation:"'rb' opens the file for reading in binary mode, returning bytes."},
  {q:"What does os.path.exists('file.txt') do?",options:["Creates a file","Deletes a file","Returns True if file exists, False otherwise","Opens a file"],answer:2,explanation:"os.path.exists() checks whether a file or directory exists."},
  {q:"What does file.seek(0) do?",options:["Closes the file","Moves read position to start of file","Reads first line","Deletes content"],answer:1,explanation:"seek(0) moves the file pointer back to position 0 (start)."},
  {q:"What does file.tell() return?",options:["File size","Current position of the file pointer","Last line","File name"],answer:1,explanation:"tell() returns the current byte position of the file pointer."},
  {q:"What does 'assert x > 0' do?",options:["Raises ValueError if x <= 0","Raises AssertionError if x <= 0","Prints x","Does nothing"],answer:1,explanation:"assert raises AssertionError if the condition is False."},
  {q:"What does 'raise X from Y' do?",options:["Raises two exceptions","Links a new exception to the original cause","Suppresses the original","Creates a custom exception"],answer:1,explanation:"raise NewError() from original_error links the new exception to its root cause."},
  {q:"What does 'except Exception:' catch?",options:["Only ValueError","Only built-in exceptions","Almost all exceptions (except SystemExit, KeyboardInterrupt)","All exceptions including system ones"],answer:2,explanation:"Exception is the base class for most built-in exceptions, but not SystemExit or KeyboardInterrupt."}
];

const PY_MIXED = [
  {q:"What keyword is used to define a function?",options:["function","func","def","define"],answer:2,explanation:"def is the Python keyword for defining a function."},
  {q:"What does list.append(x) do?",options:["Inserts x at index 0","Removes x","Adds x to the end","Sorts then adds x"],answer:2,explanation:"append() adds the element to the end of the list."},
  {q:"What is the output of: type([]) in Python?",options:["<class 'tuple'>","<class 'dict'>","<class 'list'>","<class 'set'>"],answer:2,explanation:"[] is an empty list, so type([]) returns <class 'list'>."},
  {q:"How do you open a file safely and close it automatically?",options:["open(f); close(f)","with open(f) as file:","file = open(f); finally: file.close()","open.safe(f)"],answer:1,explanation:"The 'with' statement automatically closes the file."},
  {q:"What does x = {'a':1} create?",options:["A set","A list","A tuple","A dictionary"],answer:3,explanation:"Curly braces with key:value pairs create a dictionary."},
  {q:"What is self in a class method?",options:["The class","The current instance","A global variable","A static method"],answer:1,explanation:"self refers to the specific object (instance) calling the method."},
  {q:"What exception is raised by int('abc')?",options:["TypeError","ValueError","NameError","KeyError"],answer:1,explanation:"'abc' cannot be converted to an integer, so int() raises ValueError."},
  {q:"Which loop runs an unknown number of times?",options:["for loop","while loop","range loop","list loop"],answer:1,explanation:"A while loop continues until its condition becomes False."},
  {q:"What does 'break' do in a loop?",options:["Continues to next iteration","Exits the loop immediately","Restarts the loop","Skips even iterations"],answer:1,explanation:"break immediately exits the nearest enclosing loop."},
  {q:"What does range(1,10,2) produce?",options:["1 3 5 7 9","2 4 6 8","1 2 3 4 5","1 10 2"],answer:0,explanation:"Starts at 1, steps by 2, stops before 10: 1, 3, 5, 7, 9."},
  {q:"What is a tuple in Python?",options:["A mutable ordered sequence","An immutable ordered sequence","A key-value store","An unordered collection"],answer:1,explanation:"Tuples are immutable — you cannot change their elements after creation."},
  {q:"What does __init__ do in a class?",options:["Deletes an instance","Initialises a new instance when created","Returns the class name","Creates a static method"],answer:1,explanation:"__init__ is the constructor. It runs automatically when you create a new object."},
  {q:"What does file.read() return?",options:["A list of lines","The file size","The entire file as a string","The first line"],answer:2,explanation:"read() returns all content as one string."},
  {q:"What is a lambda function?",options:["A class method","An anonymous single-expression function","A recursive function","A generator"],answer:1,explanation:"lambda is used to write small anonymous functions without the def keyword."},
  {q:"What does set() do with duplicates?",options:["Keeps all duplicates","Removes duplicates","Raises an error","Sorts them"],answer:1,explanation:"Sets only store unique values — duplicates are automatically removed."},
  {q:"Which method retrieves a dictionary value safely without error?",options:["dict['key']","dict.fetch('key')","dict.get('key')","dict.retrieve('key')"],answer:2,explanation:"dict.get(key) returns None instead of raising a KeyError."},
  {q:"What does 'finally' in try/except ensure?",options:["Runs only on error","Runs only on success","Always runs regardless of errors","Raises an exception"],answer:2,explanation:"finally always executes — used for cleanup like closing files."},
  {q:"What does len({'a':1,'b':2,'c':3}) return?",options:["1","2","3","6"],answer:2,explanation:"len() on a dictionary returns the number of key-value pairs: 3."},
  {q:"What is a list comprehension?",options:["A method to sort a list","A concise way to create lists","A loop with break","A tuple constructor"],answer:1,explanation:"List comprehensions: [expression for item in iterable if condition]."},
  {q:"What does isinstance(5, int) return?",options:["False","True","5","int"],answer:1,explanation:"5 is an integer, so isinstance(5, int) returns True."},
  {q:"How do you write to a file?",options:["file.read('text')","file.write('text')","file.append('text')","file.add('text')"],answer:1,explanation:"file.write(string) writes the string to an open file."},
  {q:"What does super() call in a child class?",options:["The child's own method","A method from the parent class","A static method","Nothing"],answer:1,explanation:"super() gives access to the parent class's methods and constructor."},
  {q:"What does dict.keys() return?",options:["All values","All key-value pairs","All keys","Length of dict"],answer:2,explanation:"dict.keys() returns a view of all the keys."},
  {q:"What is the output of: print(bool([]))?",options:["True","False","[]","error"],answer:1,explanation:"An empty list is falsy in Python, so bool([]) returns False."},
  {q:"What does 'pass' do?",options:["Exits a loop","Returns None","Acts as a no-op placeholder","Prints nothing"],answer:2,explanation:"pass does nothing. It is used where Python requires a statement but no action is needed."},
  {q:"What does sorted('hello') return?",options:["['h','e','l','l','o']","['e','h','l','l','o']","'ehllo'","error"],answer:1,explanation:"sorted() on a string sorts characters alphabetically and returns a list."},
  {q:"Which keyword makes a local variable accessible globally inside a function?",options:["local","extern","global","nonlocal"],answer:2,explanation:"The global keyword allows you to read and modify a global variable inside a function."},
  {q:"What is inheritance in Python?",options:["Copying code","A child class obtaining attributes and methods from a parent class","Creating many instances","Using functions"],answer:1,explanation:"Inheritance allows a class to reuse and extend the functionality of another class."},
  {q:"What does the 'in' operator do with a list?",options:["Adds an element","Checks if an element is in the list","Removes an element","Counts occurrences"],answer:1,explanation:"'x in list' returns True if x is found in the list."},
  {q:"What does raise ValueError('msg') do?",options:["Catches an error","Prints a message","Triggers a ValueError with message 'msg'","Defines an error"],answer:2,explanation:"raise triggers the specified exception."}
];

// ─── QUESTION GENERATION ─────────────────────────────────────────────────────

const PROGRAMMING_SUBJECT_IDS = [60, 61, 62, 63, 64, 65, 66, 67];

const PROGRAMMING_QUESTION_BANKS = {
  60: PY_BASICS,
  61: PY_CONTROL,
  62: PY_FUNCTIONS,
  63: PY_LISTS,
  64: PY_DICTS,
  65: PY_OOP,
  66: PY_FILES,
  67: PY_MIXED
};

window.PROGRAMMING_SUBJECT_IDS = PROGRAMMING_SUBJECT_IDS;
window.PROGRAMMING_QUESTION_BANKS = PROGRAMMING_QUESTION_BANKS;